package Presentacion;

import Negocio.Empleado;
import Negocio.ReconocimientoUsuario;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
import Paneles.*;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.RoundRectangle2D;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @GRUPO 4
 */
public class FormPrincipal extends javax.swing.JFrame {

    Panel_Mantenimiento pm = new Panel_Mantenimiento();
    Panel_Operaciones pt = new Panel_Operaciones();
    Panel_Reportes pr = new Panel_Reportes();
    Panel_Blanco pb = new Panel_Blanco();

    ReconocimientoUsuario recono = new ReconocimientoUsuario();

    private float opacity = 0.0f; // Inicia la opacidad en 0 para el efecto de fade-in
    private float scale = 0.1f;

    int radius = 50;
    
    public FormPrincipal() {
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        initComponents();
        setTitle("Menú principal");
        setearFechaHoraActual();
        setIconImage(obtenerImagen());
        this.setShape(new RoundRectangle2D.Double(0, 0, this.getWidth(), this.getHeight(), radius, radius));
    }

    private void updateDateTime() {
        Date now = new Date();

        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        SimpleDateFormat timeFormat = new SimpleDateFormat("hh:mm a");

        lblFecha.setText(dateFormat.format(now));
        lblHora.setText(timeFormat.format(now));
    }

    private void setearFechaHoraActual() {
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                updateDateTime();
            }
        });
        timer.start();
    }

    //Intercambiar paneles
    public void showPanel(String panelName) {
        mainPanel.removeAll();
        if (null != panelName) {
            switch (panelName) {
                case "panelM" ->
                    mainPanel.add(pm);
                case "panelT" ->
                    mainPanel.add(pt);
                case "panelR" ->
                    mainPanel.add(pr);
                case "panelB" ->
                    mainPanel.add(pb);
                default -> {
                }
            }
        }
        mainPanel.revalidate();
        mainPanel.repaint();
    }

    public void identificarUsuario(JTextField usuario) throws Exception {
        Object[] datos = recono.identificarUsuario(usuario);

        lblPuestoUsuario.setText(datos[0].toString().toUpperCase());
        lblNombreUsuario.setText(datos[1].toString());

        switch (lblPuestoUsuario.getText()) {
            case "ADMINISTRADOR" -> {
                String imagePath = "/Imagenes/administrador.jpg";
                ImageIcon icon = new ImageIcon(getClass().getResource(imagePath));
                img_tipo_usuario.setIcon(icon);
                habilitarOpciones("ADMINISTRADOR");
            }
            case "JEFE DE RR.HH." -> {
                String imagePath = "/Imagenes/RH_1.png";
                ImageIcon icon = new ImageIcon(getClass().getResource(imagePath));
                img_tipo_usuario.setIcon(icon);
                habilitarOpciones("JEFE DE RR.HH.");
            }
            default -> {
                String imagePath = "/Imagenes/GOperaciones.png";
                ImageIcon icon = new ImageIcon(getClass().getResource(imagePath));
                img_tipo_usuario.setIcon(icon);
                habilitarOpciones("JEFE DE OPERACIONES");
                //
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Round_JWC1 = new swing.Panel_Round_JWC();
        panel_Round_JWC2 = new swing.Panel_Round_JWC();
        btnReportes = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        btnMantenimiento = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        btnOperaciones = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        btnInicio = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        jPanel2 = new javax.swing.JPanel();
        btn_Round_JWC1 = new swing.Btn_Round_JWC();
        img_tipo_usuario = new img_redondo_degradado_jwc.imagen_redondo_degradado_JWC();
        lblNombreUsuario = new javax.swing.JLabel();
        lblPuestoUsuario = new javax.swing.JLabel();
        panel_Round_Degradado_JWC1 = new panel_degradado_jwc.Panel_Round_Degradado_JWC();
        panel_Round_Degradado_JWC2 = new panel_degradado_jwc.Panel_Round_Degradado_JWC();
        btnCambiarUsuario = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        btnCerrarSesion = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        btnGestionarCredenciales = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        mainPanel = new javax.swing.JPanel();
        panel_inferior = new panel_degradado_jwc.Panel_Round_Degradado_JWC();
        jLabel2 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_Round_JWC1.setBackground(new java.awt.Color(249, 249, 249));
        panel_Round_JWC1.setEsqInferiorDerecha(50);
        panel_Round_JWC1.setEsqInferiorIzquierda(50);
        panel_Round_JWC1.setEsqSuperiorDerecha(50);
        panel_Round_JWC1.setEsqSuperiorIzquierda(50);
        panel_Round_JWC1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_Round_JWC2.setBackground(new java.awt.Color(51, 51, 51));
        panel_Round_JWC2.setEsqInferiorIzquierda(50);
        panel_Round_JWC2.setEsqSuperiorIzquierda(50);
        panel_Round_JWC2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setText("REPORTES");
        btnReportes.setBackground_Hover_1(new java.awt.Color(75, 216, 176));
        btnReportes.setBackground_Hover_2(new java.awt.Color(249, 249, 249));
        btnReportes.setBackground_No_Hover_1(new java.awt.Color(51, 51, 51));
        btnReportes.setBackground_No_Hover_2(new java.awt.Color(51, 51, 51));
        btnReportes.setBtn_abajo(btnMantenimiento);
        btnReportes.setBtn_arriba(btnOperaciones);
        btnReportes.setBtn_arriba_abajo_esquina_ovalado(50);
        btnReportes.setColor_Hover_text(new java.awt.Color(0, 0, 0));
        btnReportes.setEsquina_inferior_izquierdo(40);
        btnReportes.setEsquina_superior_izquierdo(40);
        btnReportes.setFocusPainted(false);
        btnReportes.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnReportes.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        panel_Round_JWC2.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 230, 40));

        btnMantenimiento.setForeground(new java.awt.Color(255, 255, 255));
        btnMantenimiento.setText("MANTENIMIENTO");
        btnMantenimiento.setBackground_Hover_1(new java.awt.Color(75, 216, 176));
        btnMantenimiento.setBackground_Hover_2(new java.awt.Color(249, 249, 249));
        btnMantenimiento.setBackground_No_Hover_1(new java.awt.Color(51, 51, 51));
        btnMantenimiento.setBackground_No_Hover_2(new java.awt.Color(51, 51, 51));
        btnMantenimiento.setBtn_arriba(btnReportes);
        btnMantenimiento.setBtn_arriba_abajo_esquina_ovalado(50);
        btnMantenimiento.setColor_Hover_text(new java.awt.Color(0, 0, 0));
        btnMantenimiento.setEsquina_inferior_izquierdo(40);
        btnMantenimiento.setEsquina_superior_izquierdo(40);
        btnMantenimiento.setFocusPainted(false);
        btnMantenimiento.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnMantenimiento.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenimientoActionPerformed(evt);
            }
        });
        panel_Round_JWC2.add(btnMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 230, 40));

        btnOperaciones.setForeground(new java.awt.Color(255, 255, 255));
        btnOperaciones.setText("OPERACIONES");
        btnOperaciones.setBackground_Hover_1(new java.awt.Color(75, 216, 176));
        btnOperaciones.setBackground_Hover_2(new java.awt.Color(249, 249, 249));
        btnOperaciones.setBackground_No_Hover_1(new java.awt.Color(51, 51, 51));
        btnOperaciones.setBackground_No_Hover_2(new java.awt.Color(51, 51, 51));
        btnOperaciones.setBtn_abajo(btnReportes);
        btnOperaciones.setBtn_arriba(btnInicio);
        btnOperaciones.setBtn_arriba_abajo_esquina_ovalado(50);
        btnOperaciones.setColor_Hover_text(new java.awt.Color(0, 0, 0));
        btnOperaciones.setEsquina_inferior_izquierdo(40);
        btnOperaciones.setEsquina_superior_izquierdo(40);
        btnOperaciones.setFocusPainted(false);
        btnOperaciones.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnOperaciones.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnOperaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperacionesActionPerformed(evt);
            }
        });
        panel_Round_JWC2.add(btnOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 230, 40));

        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("INICIO");
        btnInicio.setBackground_Hover_1(new java.awt.Color(75, 216, 176));
        btnInicio.setBackground_Hover_2(new java.awt.Color(249, 249, 249));
        btnInicio.setBackground_No_Hover_1(new java.awt.Color(51, 51, 51));
        btnInicio.setBackground_No_Hover_2(new java.awt.Color(51, 51, 51));
        btnInicio.setBtn_abajo(btnOperaciones);
        btnInicio.setBtn_arriba_abajo_esquina_ovalado(50);
        btnInicio.setColor_Hover_text(new java.awt.Color(0, 0, 0));
        btnInicio.setEsquina_inferior_izquierdo(40);
        btnInicio.setEsquina_superior_izquierdo(40);
        btnInicio.setFocusPainted(false);
        btnInicio.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnInicio.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        panel_Round_JWC2.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 230, 40));

        jPanel2.setBackground(new java.awt.Color(249, 249, 249));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        panel_Round_JWC2.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, 160));

        btn_Round_JWC1.setBackground(new java.awt.Color(86, 201, 170));
        btn_Round_JWC1.setForeground(new java.awt.Color(255, 255, 255));
        btn_Round_JWC1.setText("SALIR");
        btn_Round_JWC1.setArco_esquina(20);
        btn_Round_JWC1.setColor_Hover(new java.awt.Color(255, 102, 0));
        btn_Round_JWC1.setColor_Normal(new java.awt.Color(86, 201, 170));
        btn_Round_JWC1.setFocusPainted(false);
        btn_Round_JWC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Round_JWC1ActionPerformed(evt);
            }
        });
        panel_Round_JWC2.add(btn_Round_JWC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 190, 50));

        img_tipo_usuario.setBorderSize(2);
        img_tipo_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GOperaciones.png"))); // NOI18N
        panel_Round_JWC2.add(img_tipo_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 170, 120));

        lblNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreUsuario.setText("NOMBRE DE USUARIO");
        panel_Round_JWC2.add(lblNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 210, 20));

        lblPuestoUsuario.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        lblPuestoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblPuestoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPuestoUsuario.setText("CARGO DE USUARIO");
        panel_Round_JWC2.add(lblPuestoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 210, 30));

        panel_Round_JWC1.add(panel_Round_JWC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 710));

        panel_Round_Degradado_JWC1.setColor1(new java.awt.Color(0, 102, 255));
        panel_Round_Degradado_JWC1.setColor2(new java.awt.Color(0, 102, 255));
        panel_Round_Degradado_JWC1.setEnabled(false);
        panel_Round_Degradado_JWC1.setSuperior_derecho(50);

        panel_Round_Degradado_JWC2.setBackground_Color_1(new java.awt.Color(0, 102, 255));
        panel_Round_Degradado_JWC2.setBackground_Color_2(new java.awt.Color(0, 102, 255));
        panel_Round_Degradado_JWC2.setColor1(new java.awt.Color(0, 102, 255));
        panel_Round_Degradado_JWC2.setColor2(new java.awt.Color(0, 102, 255));
        panel_Round_Degradado_JWC2.setEnabled(false);
        panel_Round_Degradado_JWC2.setSuperior_derecho(50);

        btnCambiarUsuario.setBackground(new java.awt.Color(86, 201, 170));
        btnCambiarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnCambiarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/btn_cambiar_usuario~1.png"))); // NOI18N
        btnCambiarUsuario.setText("<html>CAMBIAR USUARIO</html>");
        btnCambiarUsuario.setBackground_Hover_1(new java.awt.Color(255, 102, 0));
        btnCambiarUsuario.setBackground_Hover_2(new java.awt.Color(255, 153, 51));
        btnCambiarUsuario.setBackground_No_Hover_1(new java.awt.Color(69, 161, 137));
        btnCambiarUsuario.setBackground_No_Hover_2(new java.awt.Color(86, 201, 170));
        btnCambiarUsuario.setEsquina_inferior_derecho(40);
        btnCambiarUsuario.setEsquina_inferior_izquierdo(40);
        btnCambiarUsuario.setEsquina_superior_derecho(40);
        btnCambiarUsuario.setEsquina_superior_izquierdo(40);
        btnCambiarUsuario.setFocusPainted(false);
        btnCambiarUsuario.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btnCambiarUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCambiarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarUsuarioActionPerformed(evt);
            }
        });

        btnCerrarSesion.setBackground(new java.awt.Color(86, 201, 170));
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/btn_cerrar_sesion~1.png"))); // NOI18N
        btnCerrarSesion.setText("<html>CERRAR SESIÓN</html>");
        btnCerrarSesion.setBackground_Hover_1(new java.awt.Color(255, 102, 0));
        btnCerrarSesion.setBackground_Hover_2(new java.awt.Color(255, 153, 51));
        btnCerrarSesion.setBackground_No_Hover_1(new java.awt.Color(69, 161, 137));
        btnCerrarSesion.setBackground_No_Hover_2(new java.awt.Color(86, 201, 170));
        btnCerrarSesion.setEsquina_inferior_derecho(40);
        btnCerrarSesion.setEsquina_inferior_izquierdo(40);
        btnCerrarSesion.setEsquina_superior_derecho(40);
        btnCerrarSesion.setEsquina_superior_izquierdo(40);
        btnCerrarSesion.setFocusPainted(false);
        btnCerrarSesion.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btnCerrarSesion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        btnGestionarCredenciales.setBackground(new java.awt.Color(86, 201, 170));
        btnGestionarCredenciales.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarCredenciales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/btn_gestionar_credenciales~1.png"))); // NOI18N
        btnGestionarCredenciales.setText("CREDENCIALES");
        btnGestionarCredenciales.setBackground_Hover_1(new java.awt.Color(255, 102, 0));
        btnGestionarCredenciales.setBackground_Hover_2(new java.awt.Color(255, 153, 51));
        btnGestionarCredenciales.setBackground_No_Hover_1(new java.awt.Color(69, 161, 137));
        btnGestionarCredenciales.setBackground_No_Hover_2(new java.awt.Color(86, 201, 170));
        btnGestionarCredenciales.setEsquina_inferior_derecho(50);
        btnGestionarCredenciales.setEsquina_inferior_izquierdo(40);
        btnGestionarCredenciales.setEsquina_superior_derecho(40);
        btnGestionarCredenciales.setEsquina_superior_izquierdo(40);
        btnGestionarCredenciales.setFocusPainted(false);
        btnGestionarCredenciales.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btnGestionarCredenciales.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGestionarCredenciales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarCredencialesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_Round_Degradado_JWC2Layout = new javax.swing.GroupLayout(panel_Round_Degradado_JWC2);
        panel_Round_Degradado_JWC2.setLayout(panel_Round_Degradado_JWC2Layout);
        panel_Round_Degradado_JWC2Layout.setHorizontalGroup(
            panel_Round_Degradado_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Round_Degradado_JWC2Layout.createSequentialGroup()
                .addContainerGap(679, Short.MAX_VALUE)
                .addComponent(btnCambiarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGestionarCredenciales, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        panel_Round_Degradado_JWC2Layout.setVerticalGroup(
            panel_Round_Degradado_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Round_Degradado_JWC2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(panel_Round_Degradado_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGestionarCredenciales, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCambiarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout panel_Round_Degradado_JWC1Layout = new javax.swing.GroupLayout(panel_Round_Degradado_JWC1);
        panel_Round_Degradado_JWC1.setLayout(panel_Round_Degradado_JWC1Layout);
        panel_Round_Degradado_JWC1Layout.setHorizontalGroup(
            panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panel_Round_Degradado_JWC2, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_Round_Degradado_JWC1Layout.setVerticalGroup(
            panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panel_Round_Degradado_JWC2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel_Round_JWC1.add(panel_Round_Degradado_JWC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 1080, 120));

        mainPanel.setBackground(new java.awt.Color(249, 249, 249));
        panel_Round_JWC1.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 1080, 510));

        panel_inferior.setBackground_Color_1(new java.awt.Color(0, 102, 255));
        panel_inferior.setColor1(new java.awt.Color(0, 102, 255));
        panel_inferior.setColor2(new java.awt.Color(0, 102, 255));
        panel_inferior.setEnabled(false);
        panel_inferior.setInferior_derecho(50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icono_fecha_hora_1.png"))); // NOI18N

        lblFecha.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFecha.setText("--------------");
        lblFecha.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblHora.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHora.setText("--------------");
        lblHora.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout panel_inferiorLayout = new javax.swing.GroupLayout(panel_inferior);
        panel_inferior.setLayout(panel_inferiorLayout);
        panel_inferiorLayout.setHorizontalGroup(
            panel_inferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_inferiorLayout.createSequentialGroup()
                .addContainerGap(882, Short.MAX_VALUE)
                .addGroup(panel_inferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(22, 22, 22))
        );
        panel_inferiorLayout.setVerticalGroup(
            panel_inferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_inferiorLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(panel_inferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(panel_inferiorLayout.createSequentialGroup()
                        .addComponent(lblFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHora)))
                .addGap(17, 17, 17))
        );

        panel_Round_JWC1.add(panel_inferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 630, 1080, 80));

        getContentPane().add(panel_Round_JWC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Round_JWC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Round_JWC1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_Round_JWC1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jdLogin inicio = new jdLogin(this, true);
        inicio.setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    private void btnMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenimientoActionPerformed
        showPanel("panelM");
    }//GEN-LAST:event_btnMantenimientoActionPerformed

    private void btnOperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperacionesActionPerformed
        showPanel("panelT");
    }//GEN-LAST:event_btnOperacionesActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        showPanel("panelR");
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnCambiarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarUsuarioActionPerformed
        jdLogin obj = new jdLogin(this, true);
        obj.setVisible(true);
    }//GEN-LAST:event_btnCambiarUsuarioActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "¿Cerrar Sesión?", "Aviso", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(rootPane, "Sesión finalizada", "", JOptionPane.INFORMATION_MESSAGE);
            mainPanel.removeAll();
            showPanel("panelB");
            mainPanel.revalidate();
            mainPanel.repaint();
            jdLogin obj = new jdLogin(this, true);
            obj.setVisible(true);
            Empleado.ID_USUARIO_LOGGEADO = -1;
        }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void btnGestionarCredencialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarCredencialesActionPerformed
        jdGestionCredenciales obj = new jdGestionCredenciales(this, true);
        obj.setVisible(true);
    }//GEN-LAST:event_btnGestionarCredencialesActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        showPanel("panelB");
    }//GEN-LAST:event_btnInicioActionPerformed


    private void habilitarOpciones(String puesto) {
        switch (puesto) {
            case "ADMINISTRADOR":
                //Tiene acceso a todo
                btnGestionarCredenciales.setEnabled(true);
                btnMantenimiento.setEnabled(true);
                pm.accesoManteArea(true);
                pm.accesoManteBeneficio(true);
                pm.accesoManteDeduccion(true);
                pm.accesoManteDescuento(true);
                pm.accesoManteEmpleado(true);
                pm.accesoManteHorarioTrabajo(true);
                pm.accesoMantePeriodoPago(true);
                pm.accesoManteTipoContrato(true);
                pm.accesoManteTipoDeduccion(true);
                pm.accesoManteTipoDocumento(true);
                pm.accesoManteTipoEmpleado(true);
                pm.accesoManteTipoPermiso(true);

                btnOperaciones.setEnabled(true);
                pt.accesoControlAsistencia(true);
                pt.accesoCulminacionContrato(true);
                pt.accesoGestionFechaVacaciones(true);
                pt.accesoGestionFondoPensionSeguroSalud(true);
                pt.accesoGestionPagoTrabajador(true);
                pt.accesoGestionPermisos(true);
                pt.accesoRegistroContrato(true);
                
                break;
            case "JEFE DE RR.HH.":
                //Acceso a contratos, operaciones relacionadas a ellos, y acceso a ciertos reportes:
                btnGestionarCredenciales.setEnabled(false);
                btnMantenimiento.setEnabled(false); //Ningún acceso a mantenimiento
             

                btnOperaciones.setEnabled(true); //Acceso a todos menos a gestión de retenciones por ley y gestión de pago de trabajadores
                pt.accesoControlAsistencia(true);
                pt.accesoCulminacionContrato(true);
                pt.accesoGestionFechaVacaciones(true);
                pt.accesoGestionFondoPensionSeguroSalud(false);
                pt.accesoGestionPagoTrabajador(false);
                pt.accesoGestionPermisos(true);
                pt.accesoRegistroContrato(true);
                
                break;
            
            case "JEFE DE OPERACIONES":
                
                //Jefe de Operaciones: Acceso a gestión de pagos y reportes de gastos
                btnGestionarCredenciales.setEnabled(false);
                btnMantenimiento.setEnabled(false);
                btnOperaciones.setEnabled(true); //Acceso a todos menos a gestión de retenciones por ley y gestión de pago de trabajadores
                pt.accesoControlAsistencia(false);
                pt.accesoCulminacionContrato(false);
                pt.accesoGestionFechaVacaciones(false);
                pt.accesoGestionFondoPensionSeguroSalud(true);
                pt.accesoGestionPagoTrabajador(true);
                pt.accesoGestionPermisos(false);
                pt.accesoRegistroContrato(false);
                
                break;
                
            default:
                throw new AssertionError();
        }
    }

    public static Image obtenerImagen() {

        Image icono = null;
        try {
            icono = new ImageIcon(jdVentanaResumenContrato.class.getResource("/Recursos/micasahomedecor.jpeg")).getImage();
        } catch (Exception e) {
            System.out.println("No se pudo cargar la imagen: " + e.getMessage());
        }
        return icono;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnCambiarUsuario;
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnCerrarSesion;
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnGestionarCredenciales;
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnInicio;
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnMantenimiento;
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnOperaciones;
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnReportes;
    private swing.Btn_Round_JWC btn_Round_JWC1;
    private img_redondo_degradado_jwc.imagen_redondo_degradado_JWC img_tipo_usuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblPuestoUsuario;
    private javax.swing.JPanel mainPanel;
    private panel_degradado_jwc.Panel_Round_Degradado_JWC panel_Round_Degradado_JWC1;
    private panel_degradado_jwc.Panel_Round_Degradado_JWC panel_Round_Degradado_JWC2;
    private swing.Panel_Round_JWC panel_Round_JWC1;
    private swing.Panel_Round_JWC panel_Round_JWC2;
    private panel_degradado_jwc.Panel_Round_Degradado_JWC panel_inferior;
    // End of variables declaration//GEN-END:variables
}
