package Presentacion;

import Negocio.Reporte;
import java.awt.BorderLayout;
import java.awt.Container;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @SANCHEZ MERA FALU
 */
public class jd_REPORTE_ASISTENCIAS_REGISTRADAS extends javax.swing.JDialog {

    public jd_REPORTE_ASISTENCIAS_REGISTRADAS(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.jdpReporte.setVisible(false);
        setLocationRelativeTo(this);
    }

    public static String codigoEstado(JComboBox estadoSeleccionado) {
        if (estadoSeleccionado.getSelectedItem().equals("Con Permiso")) {
            return "CP";
        } else if (estadoSeleccionado.getSelectedItem().equals("Asistio")) {
            return "A";
        } else if (estadoSeleccionado.getSelectedItem().equals("Falto")) {
            return "F";
        } else if (estadoSeleccionado.getSelectedItem().equals("Tardanza")) {
            return "T";
        } else if (estadoSeleccionado.getSelectedItem().equals("Tardanza Justificada")) {
            return "TJ";
        } else if (estadoSeleccionado.getSelectedItem().equals("Falta Justificada")) {
            return "FJ";
        } else if (estadoSeleccionado.getSelectedItem().equals("Vacaciones")) {
            return "V";
        } else {
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbxMes = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JComboBox<>();
        btnGenerarReporte = new javax.swing.JButton();
        jdpReporte = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Informe de Récord de Aisstencia de Empleados");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("MES:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, 20));

        cbxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------------", "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE" }));
        jPanel1.add(cbxMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jLabel4.setText("ESTADO:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, 20));

        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----------------", "Con Permiso", "Asistio", "Falto", "Tardanza", "Tardanza Justificada", "Falta Justificada", "Vacaciones" }));
        jPanel1.add(cbxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, -1));

        btnGenerarReporte.setText("Generar Reporte");
        btnGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteActionPerformed(evt);
            }
        });
        jPanel1.add(btnGenerarReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, -1, 30));

        javax.swing.GroupLayout jdpReporteLayout = new javax.swing.GroupLayout(jdpReporte);
        jdpReporte.setLayout(jdpReporteLayout);
        jdpReporteLayout.setHorizontalGroup(
            jdpReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1140, Short.MAX_VALUE)
        );
        jdpReporteLayout.setVerticalGroup(
            jdpReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        jPanel1.add(jdpReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1140, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1162, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteActionPerformed
        try {
            if (cbxMes.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Por favor seleccione un Mes");
            } else {
                if (cbxEstado.getSelectedIndex() == 0) {
                    JOptionPane.showMessageDialog(this, "Por favor seleccione un Estado");
                } else {
                    Container contenedor = this.jdpReporte;
                    contenedor.setLayout(new BorderLayout());
                    //JOptionPane.showMessageDialog(this, "Procesando Reporte");
                    Map<String, Object> parametros = new HashMap<>();
                    parametros.put("pmt_Mes", cbxMes.getSelectedIndex());
                    //parametros.put("pmt_Dia", cbxDia.getSelectedIndex());
                    parametros.put("pmt_Estado", codigoEstado(cbxEstado));

                    System.out.println("Mes seleccionado: " + cbxMes.getSelectedIndex());
                    //System.out.println("Día seleccionado: " + cbxDia.getSelectedIndex());
                    System.out.println("Estado seleccionado: " + codigoEstado(cbxEstado));

                    JRViewer objReporte = new Reporte().reporteInterno("rptEMPLEADO_CON_TARDANZA_O_INASISTENCIA_X_MES.jasper", parametros);
                    contenedor.add(objReporte);
                    objReporte.setVisible(true);
                    //Mostrar el reporte
                    this.jdpReporte.setVisible(true);
                    //JOptionPane.showMessageDialog(this, "Reporte Mostrado");
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage() + "ERROR en Reporte", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnGenerarReporteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JComboBox<String> cbxMes;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JDesktopPane jdpReporte;
    // End of variables declaration//GEN-END:variables
}
