package Presentacion;

import Negocio.*;
import java.awt.Color;
import java.awt.Frame;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.Ellipse2D;
import javax.swing.SwingUtilities;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author jefer
 */
public class jdContratacionPersonal extends javax.swing.JDialog {

    String tipoemp;

    //Contrato
    String tipocont; //
    String fechainicio;
    String fechatermino;
    String periodopago;
    String turno;
    String horariotrabajo;
    String derechovacas;
    String responsabilidades;
    //opcionales
    String fechainivacas;
    String fechafinvacas;

    public jdContratacionPersonal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(obtenerImagen());
        setLocationRelativeTo(this);

        try {
            cargarCboTipoContrato();
            cargarCboHorariosPorTipoContrato();
            cargarCboPeriodoPago();
            validarFechaContrato();
        } catch (Exception ex) {
            Logger.getLogger(jdContratacionPersonal.class.getName()).log(Level.SEVERE, null, ex);
        }
        UIManager.put("jdGenerarContrato.background", Color.WHITE);
        UIManager.put("jdGenerarContrato.foreground", Color.BLACK);
        btnContinuar.setEnabled(false);

    }

    private void limpiar() {
        lblNombres.setText("");
        lblApeMaterno.setText("");
        lblApeMaterno.setText("");
        lblTipoEmpleado.setText("");
        lblNumDocumento.setText("");
        lblTipoDoc.setText("");
        lblArea.setText("");
        dchsrFechaInicio.setDate(null);
        cboTipoContrato.setSelectedIndex(0);
        lblFechaTermino.setText("");
        cboHorario.setSelectedIndex(0);
        cboPeriodoPago.setSelectedIndex(0);
        lblDerechoVacaciones.setText("");
        txtResponsabilidades.setText("");
        btnContinuar.setEnabled(false);
    }

    private void validarFechaContrato() {
        Calendar calendar = Calendar.getInstance();
        Date minDate = calendar.getTime(); // Fecha actual
        dchsrFechaInicio.getJCalendar().setMinSelectableDate(minDate);
    }

    //Datos de contrato
    public void instanciarDatosContrato() throws ParseException {
        this.tipocont = cboTipoContrato.getSelectedItem().toString();

        SimpleDateFormat inputFormat = new SimpleDateFormat("dd MMM yyyy");
        SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy");

        //Formatear fecha de inicio a dd-mm-yyyy
        this.fechainicio = formato.format((Date) dchsrFechaInicio.getDate());

        //Formatear fecha de término a dd-mm-yyyy
        Date fechaTerm = inputFormat.parse(lblFechaTermino.getText());
        this.fechatermino = formato.format(fechaTerm);

        this.periodopago = cboPeriodoPago.getSelectedItem().toString();

        //Obtener valores para el turno y el horario
        //turno
        String[] parts = cboHorario.getSelectedItem().toString().split(" \\(");
        this.turno = parts[0];

        //horario
        String[] parts2 = cboHorario.getSelectedItem().toString().split(" \\(");
        if (parts2.length > 1) {
            // Remover el paréntesis de cierre al final
            this.horariotrabajo = parts2[1].replace(")", "");
        }

        this.derechovacas = lblDerechoVacaciones.getText();
        this.responsabilidades = txtResponsabilidades.getText();

    }

    TipoContrato objTC = new TipoContrato();
    PeriodoPago objPP = new PeriodoPago();
    Empleado objE = new Empleado();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnVolver = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNumDocumento = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTipoDoc = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblApePaterno = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblApeMaterno = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblTipoEmpleado = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblArea = new javax.swing.JLabel();
        btnBuscarEmpleado = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dchsrFechaInicio = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        lblFechaTermino = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cboTipoContrato = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cboHorario = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cboPeriodoPago = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        lblDerechoVacaciones = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResponsabilidades = new javax.swing.JTextArea();
        btnContinuar = new btn_efecto01_jwc.btn_efecto_V1_JWC();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Contrato");
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("CONTRATACION DE PERSONAL");

        btnVolver.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton-x.png"))); // NOI18N
        btnVolver.setText("");
        btnVolver.setBackground_Hover_1(new java.awt.Color(255, 51, 51));
        btnVolver.setBackground_Hover_2(new java.awt.Color(204, 0, 0));
        btnVolver.setBackground_No_Hover_1(new java.awt.Color(255, 51, 51));
        btnVolver.setBackground_No_Hover_2(new java.awt.Color(204, 0, 0));
        btnVolver.setEsquina_inferior_derecho(20);
        btnVolver.setEsquina_inferior_izquierdo(20);
        btnVolver.setEsquina_superior_derecho(20);
        btnVolver.setEsquina_superior_izquierdo(20);
        btnVolver.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnVolver.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVolver.setIconTextGap(8);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Número de documento:");

        lblNumDocumento.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblNumDocumento.setForeground(new java.awt.Color(255, 255, 255));
        lblNumDocumento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumDocumento.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblNumDocumentoPropertyChange(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo de documento:");

        lblTipoDoc.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblTipoDoc.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoDoc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apellido paterno:");

        lblApePaterno.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblApePaterno.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellido materno:");

        lblApeMaterno.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblApeMaterno.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombres:");

        lblNombres.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblNombres.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tipo de empleado:");

        lblTipoEmpleado.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblTipoEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoEmpleado.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblTipoEmpleadoPropertyChange(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Área:");

        lblArea.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblArea.setForeground(new java.awt.Color(255, 255, 255));
        lblArea.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        btnBuscarEmpleado.setBackground(new java.awt.Color(102, 102, 102));
        btnBuscarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/btn_buscar_empleado.png"))); // NOI18N
        btnBuscarEmpleado.setText("Buscar Empleado");
        btnBuscarEmpleado.setAutoscrolls(true);
        btnBuscarEmpleado.setBackground_Hover_1(new java.awt.Color(69, 161, 137));
        btnBuscarEmpleado.setBackground_Hover_2(new java.awt.Color(86, 201, 170));
        btnBuscarEmpleado.setBackground_No_Hover_1(new java.awt.Color(69, 161, 137));
        btnBuscarEmpleado.setBackground_No_Hover_2(new java.awt.Color(86, 201, 170));
        btnBuscarEmpleado.setEsquina_inferior_derecho(20);
        btnBuscarEmpleado.setEsquina_inferior_izquierdo(20);
        btnBuscarEmpleado.setEsquina_superior_derecho(20);
        btnBuscarEmpleado.setEsquina_superior_izquierdo(20);
        btnBuscarEmpleado.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnBuscarEmpleado.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnBuscarEmpleado.setIconTextGap(8);
        btnBuscarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(522, 522, 522))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTipoEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblApeMaterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblApePaterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNombres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnBuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblArea, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblTipoDoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                            .addComponent(lblNumDocumento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel8))))
                        .addGap(22, 22, 22))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lblNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26))
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblApePaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                        .addComponent(lblNumDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblTipoDoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                    .addComponent(lblApeMaterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTipoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblArea, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(69, 161, 137));

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha de inicio:");

        dchsrFechaInicio.setForeground(new java.awt.Color(255, 255, 255));
        dchsrFechaInicio.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        dchsrFechaInicio.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dchsrFechaInicioPropertyChange(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fecha de término:");

        lblFechaTermino.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblFechaTermino.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tipo de contrato:");

        cboTipoContrato.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        cboTipoContrato.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTipoContratoItemStateChanged(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Horario:");

        cboHorario.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Periodo de pago:");

        cboPeriodoPago.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        cboPeriodoPago.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboPeriodoPagoItemStateChanged(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Derecho a vacaciones pagadas:");

        lblDerechoVacaciones.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblDerechoVacaciones.setForeground(new java.awt.Color(255, 255, 255));
        lblDerechoVacaciones.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDerechoVacaciones.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblDerechoVacacionesPropertyChange(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Responsabilidades:");

        txtResponsabilidades.setColumns(20);
        txtResponsabilidades.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        txtResponsabilidades.setRows(5);
        jScrollPane1.setViewportView(txtResponsabilidades);

        btnContinuar.setBackground(new java.awt.Color(255, 204, 0));
        btnContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/btn_calcular_sueldo.png"))); // NOI18N
        btnContinuar.setText("Continuar");
        btnContinuar.setBackground_Hover_1(new java.awt.Color(255, 204, 0));
        btnContinuar.setBackground_Hover_2(new java.awt.Color(255, 204, 0));
        btnContinuar.setBackground_No_Hover_1(new java.awt.Color(255, 204, 0));
        btnContinuar.setBackground_No_Hover_2(new java.awt.Color(255, 204, 0));
        btnContinuar.setEsquina_inferior_derecho(20);
        btnContinuar.setEsquina_inferior_izquierdo(20);
        btnContinuar.setEsquina_superior_derecho(20);
        btnContinuar.setEsquina_superior_izquierdo(20);
        btnContinuar.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnContinuar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnContinuar.setIconTextGap(8);
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel9))
                                        .addGap(24, 24, 24))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(39, 39, 39)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboPeriodoPago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dchsrFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                    .addComponent(lblFechaTermino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboTipoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboHorario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDerechoVacaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dchsrFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(cboTipoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboPeriodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblDerechoVacaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //botón de buscar empleado
    private void buscarEmpleado() {
        jdVentanaBuscarEmpleado obj = new jdVentanaBuscarEmpleado((Frame) SwingUtilities.getWindowAncestor(this), true);
        obj.setLocationRelativeTo(this);
        obj.setVisible(true);

        if (obj.getApepat() != null && obj.getApepat() != null && obj.getNomarea() != null && obj.getNombres() != null && obj.getNumdoc() != null
                && obj.getTipodoc() != null && obj.getTipoemp() != null) {
            lblApeMaterno.setText(obj.getApemat());
            lblApePaterno.setText(obj.getApepat());
            lblArea.setText(obj.getNomarea());
            lblNombres.setText(obj.getNombres());
            lblNumDocumento.setText(obj.getNumdoc());
            lblTipoDoc.setText(obj.getTipodoc());
            lblTipoEmpleado.setText(obj.getTipoemp());
            try {
                int id = objE.obtenerIdEmpleado(lblNumDocumento.getText(), lblTipoDoc.getText());
                setearLblVacacionesPagadas(id);
            } catch (Exception ex) {
                Logger.getLogger(jdContratacionPersonal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void setearLblVacacionesPagadas(int idemp) throws Exception {
        boolean cumple = objE.tieneContratosAnterioresValidos(idemp);
        if (cumple) {
            lblDerechoVacaciones.setText("Sí");
        } else {
            lblDerechoVacaciones.setText("No");
        }
    }

    private String getTextoTurno(String cboHorarioItem) {

        Pattern pattern = Pattern.compile("^(Mañana|Tarde|Noche) \\(");
        Matcher matcher = pattern.matcher(cboHorarioItem);
        if (matcher.find()) {
            return matcher.group(1); // Grupo 1 es el turno (Mañana o Tarde)
        }
        return ""; // Retornar cadena vacía si no se encuentra coincidencia
    }

    private void cboTipoContratoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTipoContratoItemStateChanged
        try {
            cargarCboHorariosPorTipoContrato();
        } catch (Exception ex) {
            Logger.getLogger(jdContratacionPersonal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cboTipoContratoItemStateChanged

    private void dchsrFechaInicioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dchsrFechaInicioPropertyChange
        Date selectedDate = (Date) dchsrFechaInicio.getDate();
        if (selectedDate != null) {
            Calendar calendar = Calendar.getInstance();
            calendar.setTime(selectedDate);
            calendar.add(Calendar.YEAR, 1);
            Date oneYearLater = (Date) calendar.getTime();

            SimpleDateFormat dateFormat = new SimpleDateFormat("d MMM y");
            String formattedDate = dateFormat.format(oneYearLater);
            lblFechaTermino.setText(formattedDate);
        }
    }//GEN-LAST:event_dchsrFechaInicioPropertyChange

    private void cboPeriodoPagoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboPeriodoPagoItemStateChanged

    }//GEN-LAST:event_cboPeriodoPagoItemStateChanged

    private void lblDerechoVacacionesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblDerechoVacacionesPropertyChange

    }//GEN-LAST:event_lblDerechoVacacionesPropertyChange

    private void lblTipoEmpleadoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblTipoEmpleadoPropertyChange

    }//GEN-LAST:event_lblTipoEmpleadoPropertyChange

    private void pasarDatos() throws ParseException {
        SimpleDateFormat formato = new SimpleDateFormat("dd MMM yyyy");

        tipoemp = lblTipoEmpleado.getText();

        jdVentanaCalcularRetencionesPorLey obj = new jdVentanaCalcularRetencionesPorLey((Frame) SwingUtilities.getWindowAncestor(this), true);
        obj.setTipoEmp(tipoemp);
        obj.setTipoContrato(cboTipoContrato.getSelectedItem().toString());
        obj.setPeriodo(cboPeriodoPago.getSelectedItem().toString());

        //Trabajador
        obj.setApepatRSMN(lblApePaterno.getText());
        obj.setApematRSMN(lblApeMaterno.getText());
        obj.setNombresRSMN(lblNombres.getText());
        obj.setTipoempRSMN(lblTipoEmpleado.getText());
        obj.setNumdocRSMN(lblNumDocumento.getText());
        obj.setTipdocRSMN(lblTipoDoc.getText());
        obj.setAreaRSMN(lblArea.getText());

        //Contrato
        //Formatear fecha de inicio
        obj.setFechainicioRSMN(formato.format(dchsrFechaInicio.getDate()));

        //Formatear fecha de término
        Date fechaTerm = null;
        fechaTerm = formato.parse(lblFechaTermino.getText());
        obj.setFechaterminoRSMN(formato.format(fechaTerm));

        obj.setTipocontRSMN(cboTipoContrato.getSelectedItem().toString());

        //Obtener valores para el turno y el horario
        //turno
        String cboitemhorario = cboHorario.getSelectedItem().toString();
        obj.setTurnoRSMN(getTextoTurno(cboitemhorario));

        //horario
        String[] parts2 = cboHorario.getSelectedItem().toString().split(" \\(");
        if (parts2.length > 1) {
            // Remover el paréntesis de cierre al final
            obj.setHorariotrabajoRSMN(parts2[1].replace(")", ""));
        }

        obj.setPeriodopagoRSMN(cboPeriodoPago.getSelectedItem().toString());
        obj.setDerechovacasRSMN(lblDerechoVacaciones.getText());

        obj.setResponsabilidadesRSMN(txtResponsabilidades.getText());

        obj.setLocationRelativeTo(this);
        obj.setVisible(true);
    }

    private void calcularSueldo() throws ParseException {
        if (dchsrFechaInicio.getDate() == null) {
            JOptionPane.showMessageDialog(rootPane, "Especifique la duración del contrato");
        } else {
            pasarDatos();
        }
    }

    private void lblNumDocumentoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblNumDocumentoPropertyChange
        if (!lblNumDocumento.getText().isBlank()) {
            btnContinuar.setEnabled(true);
        } else {
            btnContinuar.setEnabled(false);
        }
    }//GEN-LAST:event_lblNumDocumentoPropertyChange

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated

    }//GEN-LAST:event_formWindowDeactivated

    private void btnBuscarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEmpleadoActionPerformed
        buscarEmpleado();
    }//GEN-LAST:event_btnBuscarEmpleadoActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        try {
            calcularSueldo();
            int idempleado = objE.obtenerIdEmpleado(lblNumDocumento.getText(), lblTipoDoc.getText());
            boolean existe = objE.existeContratoVigente(idempleado);
            if (existe) {
                limpiar();
            }
        } catch (ParseException ex) {
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void cargarCboTipoContrato() throws Exception {
        ResultSet rs = objTC.cargarTipoContratos();
        while (rs.next()) {
            cboTipoContrato.addItem(rs.getString("nombre"));
        }
    }

    //Según el tipo de contrato seleccionado, mostrar los horarios disponibles:
    private void cargarCboHorariosPorTipoContrato() throws Exception {
        cboHorario.removeAllItems();
        SimpleDateFormat timeFormat = new SimpleDateFormat("h:mm a");

        String tipocontrato = cboTipoContrato.getSelectedItem().toString();
        ResultSet rs = objTC.cargarHorariosDeTipoContrato(tipocontrato);
        while (rs.next()) {
            String turno = rs.getString("turno");
            String horainicio = timeFormat.format(rs.getTime("horaentrada"));
            String horafin = timeFormat.format(rs.getTime("horasalida"));
            cboHorario.addItem(turno + " (" + horainicio + " - " + horafin + ")");
        }
    }

    private void cargarCboPeriodoPago() throws Exception {
        ResultSet rs = objPP.cargarPeriodosPago();
        while (rs.next()) {
            cboPeriodoPago.addItem(rs.getString("nombre"));
        }
    }

    //Ícono a un jdialog
    public static Image obtenerImagen() {

        Image icono = null;
        try {
            icono = new ImageIcon(jdContratacionPersonal.class.getResource("/Recursos/btn_registro_contrato.png")).getImage();
        } catch (Exception e) {
            System.out.println("No se pudo cargar la imagen: " + e.getMessage());
        }
        return icono;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnBuscarEmpleado;
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnContinuar;
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnVolver;
    private javax.swing.JComboBox<String> cboHorario;
    private javax.swing.JComboBox<String> cboPeriodoPago;
    private javax.swing.JComboBox<String> cboTipoContrato;
    private com.toedter.calendar.JDateChooser dchsrFechaInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApeMaterno;
    private javax.swing.JLabel lblApePaterno;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblDerechoVacaciones;
    private javax.swing.JLabel lblFechaTermino;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblNumDocumento;
    private javax.swing.JLabel lblTipoDoc;
    private javax.swing.JLabel lblTipoEmpleado;
    private javax.swing.JTextArea txtResponsabilidades;
    // End of variables declaration//GEN-END:variables
}
