/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Presentacion;

import java.awt.Frame;
import javax.swing.SwingUtilities;
import java.sql.ResultSet;
import Negocio.Contrato;
import Negocio.Deduccion;
import Negocio.TipoDocumento;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jefer
 */
public class jdCulminacionContrato extends javax.swing.JDialog {

    private String apepaterno;
    private String apematerno;
    private String nombresemp;
    private String numdocum;
    private String tipodocum;
    private String tipoempleado;
    private String areasignada;

    public void setApepaterno(String apepaterno) {
        this.apepaterno = apepaterno;
    }

    public void setApematerno(String apematerno) {
        this.apematerno = apematerno;
    }

    public void setNombresemp(String nombresemp) {
        this.nombresemp = nombresemp;
    }

    public void setNumdocum(String numdocum) {
        this.numdocum = numdocum;
    }

    public void setTipodocum(String tipodocum) {
        this.tipodocum = tipodocum;
    }

    public void setTipoempleado(String tipoempleado) {
        this.tipoempleado = tipoempleado;
    }

    public void setAreasignada(String areasignada) {
        this.areasignada = areasignada;
    }

    Contrato objc = new Contrato();
    Deduccion objD = new Deduccion();
    TipoDocumento objTD = new TipoDocumento();

    private int codigocontrato = -1;

    jdVentanaBuscarEmpleadoContratoVigente jdBECV = new jdVentanaBuscarEmpleadoContratoVigente((Frame) SwingUtilities.getWindowAncestor(this), true);

    public jdCulminacionContrato(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Tipo de retención");
        modelo.addColumn("Retención");
        modelo.addColumn("Monto retenido (S/.)");
        tblDetallesDeduccion.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTipoDoc = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblNumDocumento = new javax.swing.JLabel();
        lblApeMat = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        lblTipoEmp = new javax.swing.JLabel();
        lblArea = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblApePat = new javax.swing.JLabel();
        btnBuscarEmpleadoContratoVigente = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        jPanel3 = new javax.swing.JPanel();
        lblDatosContrato = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblTipoContrato = new javax.swing.JLabel();
        lblFechaInicio = new javax.swing.JLabel();
        lblFechaTermino = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblPeriodoPago = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblTurno = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblHorarioTrabajo = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblDerechoVacaciones = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResponsabilidades = new javax.swing.JTextArea();
        btnVerPagosPendientes = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        btnVolver1 = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        lblSalarioAcordado = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetallesDeduccion = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CULMINACION DE CONTRATO");

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Datos del trabajador");

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido materno:");

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombres:");

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("N° documento:");

        lblTipoDoc.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblTipoDoc.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tipo de documento:");

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tipo de empleado:");

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Área asignada:");

        lblNumDocumento.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblNumDocumento.setForeground(new java.awt.Color(255, 255, 255));

        lblApeMat.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblApeMat.setForeground(new java.awt.Color(255, 255, 255));

        lblNombres.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblNombres.setForeground(new java.awt.Color(255, 255, 255));

        lblTipoEmp.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblTipoEmp.setForeground(new java.awt.Color(255, 255, 255));

        lblArea.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblArea.setForeground(new java.awt.Color(255, 255, 255));

        jLabel19.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Apellido paterno:");

        lblApePat.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblApePat.setForeground(new java.awt.Color(255, 255, 255));

        btnBuscarEmpleadoContratoVigente.setBackground(new java.awt.Color(102, 102, 102));
        btnBuscarEmpleadoContratoVigente.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarEmpleadoContratoVigente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/btn_buscar_empleado.png"))); // NOI18N
        btnBuscarEmpleadoContratoVigente.setText("Buscar");
        btnBuscarEmpleadoContratoVigente.setAutoscrolls(true);
        btnBuscarEmpleadoContratoVigente.setBackground_Hover_1(new java.awt.Color(69, 161, 137));
        btnBuscarEmpleadoContratoVigente.setBackground_Hover_2(new java.awt.Color(86, 201, 170));
        btnBuscarEmpleadoContratoVigente.setBackground_No_Hover_1(new java.awt.Color(69, 161, 137));
        btnBuscarEmpleadoContratoVigente.setBackground_No_Hover_2(new java.awt.Color(86, 201, 170));
        btnBuscarEmpleadoContratoVigente.setEsquina_inferior_derecho(20);
        btnBuscarEmpleadoContratoVigente.setEsquina_inferior_izquierdo(20);
        btnBuscarEmpleadoContratoVigente.setEsquina_superior_derecho(20);
        btnBuscarEmpleadoContratoVigente.setEsquina_superior_izquierdo(20);
        btnBuscarEmpleadoContratoVigente.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnBuscarEmpleadoContratoVigente.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnBuscarEmpleadoContratoVigente.setIconTextGap(8);
        btnBuscarEmpleadoContratoVigente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEmpleadoContratoVigenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblApePat, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblArea, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTipoEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblApeMat, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(72, 72, 72)
                        .addComponent(btnBuscarEmpleadoContratoVigente, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarEmpleadoContratoVigente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(lblApePat, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblApeMat, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNumDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTipoDoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTipoEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblArea, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(69, 161, 137));

        lblDatosContrato.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        lblDatosContrato.setForeground(new java.awt.Color(255, 255, 255));
        lblDatosContrato.setText("Datos del contrato");

        jLabel10.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tipo de contrato:");

        jLabel11.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Fecha de inicio:");

        jLabel12.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Fecha de término:");

        lblTipoContrato.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblTipoContrato.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoContrato.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTipoContrato.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblTipoContratoPropertyChange(evt);
            }
        });

        lblFechaInicio.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblFechaInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblFechaTermino.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblFechaTermino.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaTermino.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel13.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Periodo de pago:");

        lblPeriodoPago.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblPeriodoPago.setForeground(new java.awt.Color(255, 255, 255));
        lblPeriodoPago.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel14.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Turno:");

        lblTurno.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblTurno.setForeground(new java.awt.Color(255, 255, 255));
        lblTurno.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel15.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Horario de trabajo:");

        lblHorarioTrabajo.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblHorarioTrabajo.setForeground(new java.awt.Color(255, 255, 255));
        lblHorarioTrabajo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel16.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Derecho a vacaciones pagadas:");

        lblDerechoVacaciones.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblDerechoVacaciones.setForeground(new java.awt.Color(255, 255, 255));
        lblDerechoVacaciones.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel17.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Responsabilidades asignadas:");

        txtResponsabilidades.setColumns(20);
        txtResponsabilidades.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        txtResponsabilidades.setRows(5);
        txtResponsabilidades.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtResponsabilidades.setEnabled(false);
        jScrollPane1.setViewportView(txtResponsabilidades);

        btnVerPagosPendientes.setBackground(new java.awt.Color(0, 0, 0));
        btnVerPagosPendientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/btn_ver_pagos_pendientes.png"))); // NOI18N
        btnVerPagosPendientes.setText("Ver pagos pendientes");
        btnVerPagosPendientes.setBackground_Hover_1(new java.awt.Color(255, 204, 0));
        btnVerPagosPendientes.setBackground_Hover_2(new java.awt.Color(255, 204, 0));
        btnVerPagosPendientes.setBackground_No_Hover_1(new java.awt.Color(255, 204, 0));
        btnVerPagosPendientes.setBackground_No_Hover_2(new java.awt.Color(255, 204, 0));
        btnVerPagosPendientes.setColor_Hover_text(new java.awt.Color(0, 0, 0));
        btnVerPagosPendientes.setColor_NoHover_text(new java.awt.Color(0, 0, 0));
        btnVerPagosPendientes.setEsquina_inferior_derecho(20);
        btnVerPagosPendientes.setEsquina_inferior_izquierdo(20);
        btnVerPagosPendientes.setEsquina_superior_derecho(20);
        btnVerPagosPendientes.setEsquina_superior_izquierdo(20);
        btnVerPagosPendientes.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btnVerPagosPendientes.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVerPagosPendientes.setIconTextGap(8);
        btnVerPagosPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPagosPendientesActionPerformed(evt);
            }
        });
        btnVerPagosPendientes.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                btnVerPagosPendientesPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(lblDatosContrato))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblHorarioTrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPeriodoPago, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFechaInicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTipoContrato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFechaTermino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVerPagosPendientes, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(lblDerechoVacaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatosContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerPagosPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(lblTipoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(lblFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(lblFechaTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblPeriodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHorarioTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDerechoVacaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16))
                .addGap(24, 24, 24)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        btnVolver1.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver1.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton-x.png"))); // NOI18N
        btnVolver1.setText("");
        btnVolver1.setBackground_Hover_1(new java.awt.Color(255, 51, 51));
        btnVolver1.setBackground_Hover_2(new java.awt.Color(204, 0, 0));
        btnVolver1.setBackground_No_Hover_1(new java.awt.Color(255, 51, 51));
        btnVolver1.setBackground_No_Hover_2(new java.awt.Color(204, 0, 0));
        btnVolver1.setEsquina_inferior_derecho(20);
        btnVolver1.setEsquina_inferior_izquierdo(20);
        btnVolver1.setEsquina_superior_derecho(20);
        btnVolver1.setEsquina_superior_izquierdo(20);
        btnVolver1.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnVolver1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVolver1.setIconTextGap(8);
        btnVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver1ActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(86, 201, 170));

        jLabel20.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Salario acordado:");

        lblSalarioAcordado.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        lblSalarioAcordado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel18.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Retenciones por ley:");

        tblDetallesDeduccion.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        tblDetallesDeduccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tipo de retención", "Retención", "Monto retenido (S/.)"
            }
        ));
        jScrollPane2.setViewportView(tblDetallesDeduccion);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel20))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblSalarioAcordado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(27, 27, 27))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSalarioAcordado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolver1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVolver1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolver1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void btnVerPagosPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPagosPendientesActionPerformed
        try {
            jdVentanaPagosPendientes obj = new jdVentanaPagosPendientes((Frame) SwingUtilities.getWindowAncestor(this), true);
            obj.setCodigocontrato(this.codigocontrato);
            obj.setNumdoc(lblNumDocumento.getText());
            obj.setTipodoc(lblTipoDoc.getText());
            obj.setPeriodo(lblPeriodoPago.getText());
            obj.setDialogoAnularContrato(this);
            obj.setVisible(true);
            
            if (objc.contratoAnulado(this.codigocontrato)) {
                limpiarDialogo();
            }
        } catch (Exception ex) {
            Logger.getLogger(jdCulminacionContrato.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVerPagosPendientesActionPerformed

    private void btnBuscarEmpleadoContratoVigenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEmpleadoContratoVigenteActionPerformed
        try {
            jdVentanaBuscarEmpleadoContratoVigente_AnularContrato obj
                    = new jdVentanaBuscarEmpleadoContratoVigente_AnularContrato((Frame) SwingUtilities.getWindowAncestor(this), true);
            obj.setVisible(true);
            if (obj.getApepat() != null && obj.getApepat() != null && obj.getNomarea() != null && obj.getNombres() != null && obj.getNumdoc() != null
                    && obj.getTipodoc() != null && obj.getTipoemp() != null) {
                lblApePat.setText(obj.getApepat());
                lblApeMat.setText(obj.getApemat());
                lblNombres.setText(obj.getNombres());
                lblNumDocumento.setText(obj.getNumdoc());
                lblTipoDoc.setText(obj.getTipodoc());
                lblTipoEmp.setText(obj.getTipoemp());
                lblArea.setText(obj.getNomarea());
                obtenerDatos();
            }

        } catch (Exception ex) {
            Logger.getLogger(jdCulminacionContrato.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarEmpleadoContratoVigenteActionPerformed

    private void btnVerPagosPendientesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_btnVerPagosPendientesPropertyChange

    }//GEN-LAST:event_btnVerPagosPendientesPropertyChange

    private void lblTipoContratoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblTipoContratoPropertyChange
        if (lblTipoContrato.getText().isBlank()) {
            btnVerPagosPendientes.setEnabled(false);
        } else {
            btnVerPagosPendientes.setEnabled(true);
        }
    }//GEN-LAST:event_lblTipoContratoPropertyChange

    private void obtenerDatos() throws Exception {
        //Seteamos los datos pasados del jdialog buscar empleado contrato vigente

        int idtipodoc = objTD.obtenerIdTipoDocumento(lblTipoDoc.getText());

        //Obtenemos los datos de contrato del trabajador:
        ResultSet rsDC = objc.obtenerDatosContratoTrabajador(lblNumDocumento.getText(), idtipodoc);
        while (rsDC.next()) {
            this.codigocontrato = rsDC.getInt("codigocontrato"); //Me servirá más adelante para otra consulta y para poder actualizar el estado del contrato (anularlo)
            lblTipoContrato.setText(rsDC.getString("tipocontrato"));
            //Formatear las fechas:
            SimpleDateFormat formatoFechas = new SimpleDateFormat("d MMM y");
            java.sql.Date fechaI = rsDC.getDate("fechainicio");
            java.sql.Date fechaF = rsDC.getDate("fechatermino");
            String fechatxtI = formatoFechas.format(fechaI);
            String fechaTxtF = formatoFechas.format(fechaF);
            lblFechaInicio.setText(fechatxtI);
            lblFechaTermino.setText(fechaTxtF);
            lblPeriodoPago.setText(rsDC.getString("periodopago"));
            lblTurno.setText(rsDC.getString("turno"));
            lblHorarioTrabajo.setText(cadenaHorarioTrabajo(rsDC.getString("horario_trabajo")));
            lblDerechoVacaciones.setText(rsDC.getString("derechovacas"));
            txtResponsabilidades.setText(rsDC.getString("responsabilidades"));
            String formatoSalario = String.format("%.2f", rsDC.getDouble("salarioacordado"));
            lblSalarioAcordado.setText("S/. " + formatoSalario);
        }

        //Obtenemos los detalles de las deducciones del contrato:
        ResultSet rsDD = objD.obtenerDetallesDeduccionesContrato(this.codigocontrato);

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Tipo de retención");
        modelo.addColumn("Retención");
        modelo.addColumn("Monto retenido (S/.)");

        Object datos[] = new Object[3];

        while (rsDD.next()) {
            datos[0] = rsDD.getString("tipodeduccion");
            datos[1] = rsDD.getString("retencion");
            datos[2] = String.format("%.2f", rsDD.getDouble("monto_retenido"));
            modelo.addRow(datos);
        }
        tblDetallesDeduccion.setModel(modelo);
    }

    private String cadenaHorarioTrabajo(String text) {
        String[] parts = text.split(" - ");
        StringBuilder formattedText = new StringBuilder();

        for (int i = 0; i < parts.length; i++) {
            // Divide cada parte por espacio para separar la hora del indicador AM/PM
            String[] timeParts = parts[i].split(" ");
            String time = timeParts[0];
            String amPm = timeParts[1].toLowerCase(); // Convierte AM/PM a minúsculas

            // Añade ".m." al indicador AM/PM
            if (amPm.equals("am")) {
                amPm = "a.m.";
            } else if (amPm.equals("pm")) {
                amPm = "p.m.";
            }

            // Vuelve a ensamblar la parte formateada
            formattedText.append(time).append(" ").append(amPm);

            // Añade el separador " - " entre las partes si no es la última parte
            if (i < parts.length - 1) {
                formattedText.append(" - ");
            }
        }
        return formattedText.toString();
    }
    
    public void limpiarDialogo(){
        lblApeMat.setText("");
        lblApePat.setText("");
        lblArea.setText("");
        lblDerechoVacaciones.setText("");
        lblFechaInicio.setText("");
        lblFechaTermino.setText("");
        lblHorarioTrabajo.setText("");
        lblNombres.setText("");
        lblNumDocumento.setText("");
        lblPeriodoPago.setText("");
        lblSalarioAcordado.setText("");
        lblTipoContrato.setText("");
        lblTipoDoc.setText("");
        lblTipoEmp.setText("");
        lblTurno.setText("");
        txtResponsabilidades.setText("");
        
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Tipo de retención");
        modelo.addColumn("Retención");
        modelo.addColumn("Monto retenido (S/.)");
        tblDetallesDeduccion.setModel(modelo);
        
        btnVerPagosPendientes.setEnabled(false);
        txtResponsabilidades.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnBuscarEmpleadoContratoVigente;
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnVerPagosPendientes;
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnVolver1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblApeMat;
    private javax.swing.JLabel lblApePat;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblDatosContrato;
    private javax.swing.JLabel lblDerechoVacaciones;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblFechaTermino;
    private javax.swing.JLabel lblHorarioTrabajo;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblNumDocumento;
    private javax.swing.JLabel lblPeriodoPago;
    private javax.swing.JLabel lblSalarioAcordado;
    private javax.swing.JLabel lblTipoContrato;
    private javax.swing.JLabel lblTipoDoc;
    private javax.swing.JLabel lblTipoEmp;
    private javax.swing.JLabel lblTurno;
    private javax.swing.JTable tblDetallesDeduccion;
    private javax.swing.JTextArea txtResponsabilidades;
    // End of variables declaration//GEN-END:variables
}
