/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Presentacion;

import Negocio.Contrato;
import Negocio.Deduccion;
import Negocio.Empleado;
import java.awt.Frame;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.JLabel;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author jefer
 */
public class jdGestionFondoPensionSeguroSalud extends javax.swing.JDialog {

    Deduccion objD = new Deduccion();
    Empleado objE = new Empleado();
    Contrato objC = new Contrato();

    public jdGestionFondoPensionSeguroSalud(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVolver5 = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        btnBuscarEmpleado = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        jLabel4 = new javax.swing.JLabel();
        lblApePaterno = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblNumDocumento = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblApeMaterno = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTipoDoc = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblTipoEmpleado = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblArea = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRetenciones = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        lblSalarioNeto = new javax.swing.JLabel();
        btnAsignarSeguroSalud = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        btnCambiarAseguradora = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        jLabel12 = new javax.swing.JLabel();
        lblSalarioBruto = new javax.swing.JLabel();
        btnGuardarCambios = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("GESTION DE FONDO DE PENSIONES Y SEGURO DE SALUD");

        btnVolver5.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver5.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton-x.png"))); // NOI18N
        btnVolver5.setText("");
        btnVolver5.setBackground_Hover_1(new java.awt.Color(255, 51, 51));
        btnVolver5.setBackground_Hover_2(new java.awt.Color(204, 0, 0));
        btnVolver5.setBackground_No_Hover_1(new java.awt.Color(255, 51, 51));
        btnVolver5.setBackground_No_Hover_2(new java.awt.Color(204, 0, 0));
        btnVolver5.setEsquina_inferior_derecho(20);
        btnVolver5.setEsquina_inferior_izquierdo(20);
        btnVolver5.setEsquina_superior_derecho(20);
        btnVolver5.setEsquina_superior_izquierdo(20);
        btnVolver5.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnVolver5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVolver5.setIconTextGap(8);
        btnVolver5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver5ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombres:");

        lblNombres.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblNombres.setForeground(new java.awt.Color(255, 255, 255));

        btnBuscarEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/btn_buscar_empleado.png"))); // NOI18N
        btnBuscarEmpleado.setText("Buscar Empleado");
        btnBuscarEmpleado.setAutoscrolls(true);
        btnBuscarEmpleado.setBackground_Hover_1(new java.awt.Color(69, 161, 137));
        btnBuscarEmpleado.setBackground_Hover_2(new java.awt.Color(86, 201, 170));
        btnBuscarEmpleado.setBackground_No_Hover_1(new java.awt.Color(69, 161, 137));
        btnBuscarEmpleado.setBackground_No_Hover_2(new java.awt.Color(86, 201, 170));
        btnBuscarEmpleado.setEsquina_inferior_derecho(20);
        btnBuscarEmpleado.setEsquina_inferior_izquierdo(20);
        btnBuscarEmpleado.setEsquina_superior_derecho(20);
        btnBuscarEmpleado.setEsquina_superior_izquierdo(20);
        btnBuscarEmpleado.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnBuscarEmpleado.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnBuscarEmpleado.setIconTextGap(8);
        btnBuscarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEmpleadoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apellido paterno:");

        lblApePaterno.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblApePaterno.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Número de documento:");

        lblNumDocumento.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblNumDocumento.setForeground(new java.awt.Color(255, 255, 255));
        lblNumDocumento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumDocumento.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblNumDocumentoPropertyChange(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellido materno:");

        lblApeMaterno.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblApeMaterno.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo de documento:");

        lblTipoDoc.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblTipoDoc.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoDoc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tipo de empleado:");

        lblTipoEmpleado.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblTipoEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoEmpleado.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblTipoEmpleadoPropertyChange(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Área:");

        lblArea.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblArea.setForeground(new java.awt.Color(255, 255, 255));
        lblArea.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipoEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblApeMaterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblApePaterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNombres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblArea, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblTipoDoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                    .addComponent(lblNumDocumento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8))))
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(lblNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26))
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnBuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblApePaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                        .addComponent(lblNumDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblTipoDoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                    .addComponent(lblApeMaterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblArea, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(69, 161, 137));

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Retenciones registradas en contrato:");

        tblRetenciones.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        tblRetenciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblRetenciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRetencionesMouseClicked(evt);
            }
        });
        tblRetenciones.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblRetencionesPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblRetenciones);

        jLabel11.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Remuneración:");

        lblSalarioNeto.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblSalarioNeto.setForeground(new java.awt.Color(255, 255, 255));

        btnAsignarSeguroSalud.setBackground(new java.awt.Color(255, 204, 0));
        btnAsignarSeguroSalud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/btn_asignar_seguro_salud~1.png"))); // NOI18N
        btnAsignarSeguroSalud.setText("Asignar S.S.");
        btnAsignarSeguroSalud.setBackground_Hover_1(new java.awt.Color(255, 204, 0));
        btnAsignarSeguroSalud.setBackground_Hover_2(new java.awt.Color(255, 204, 0));
        btnAsignarSeguroSalud.setBackground_No_Hover_1(new java.awt.Color(255, 204, 0));
        btnAsignarSeguroSalud.setBackground_No_Hover_2(new java.awt.Color(255, 204, 0));
        btnAsignarSeguroSalud.setColor_Hover_text(new java.awt.Color(0, 0, 0));
        btnAsignarSeguroSalud.setColor_NoHover_text(new java.awt.Color(0, 0, 0));
        btnAsignarSeguroSalud.setEsquina_inferior_derecho(20);
        btnAsignarSeguroSalud.setEsquina_inferior_izquierdo(20);
        btnAsignarSeguroSalud.setEsquina_superior_derecho(20);
        btnAsignarSeguroSalud.setEsquina_superior_izquierdo(20);
        btnAsignarSeguroSalud.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btnAsignarSeguroSalud.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAsignarSeguroSalud.setIconTextGap(8);
        btnAsignarSeguroSalud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarSeguroSaludActionPerformed(evt);
            }
        });
        btnAsignarSeguroSalud.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                btnAsignarSeguroSaludPropertyChange(evt);
            }
        });

        btnCambiarAseguradora.setBackground(new java.awt.Color(255, 204, 0));
        btnCambiarAseguradora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/btn_cambiar_aseguradora_pensiones~1.png"))); // NOI18N
        btnCambiarAseguradora.setText("Cambiar aseguradora de pensiones");
        btnCambiarAseguradora.setBackground_Hover_1(new java.awt.Color(255, 204, 0));
        btnCambiarAseguradora.setBackground_Hover_2(new java.awt.Color(255, 204, 0));
        btnCambiarAseguradora.setBackground_No_Hover_1(new java.awt.Color(255, 204, 0));
        btnCambiarAseguradora.setBackground_No_Hover_2(new java.awt.Color(255, 204, 0));
        btnCambiarAseguradora.setColor_Hover_text(new java.awt.Color(0, 0, 0));
        btnCambiarAseguradora.setColor_NoHover_text(new java.awt.Color(0, 0, 0));
        btnCambiarAseguradora.setEsquina_inferior_derecho(20);
        btnCambiarAseguradora.setEsquina_inferior_izquierdo(20);
        btnCambiarAseguradora.setEsquina_superior_derecho(20);
        btnCambiarAseguradora.setEsquina_superior_izquierdo(20);
        btnCambiarAseguradora.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btnCambiarAseguradora.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCambiarAseguradora.setIconTextGap(8);
        btnCambiarAseguradora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarAseguradoraActionPerformed(evt);
            }
        });
        btnCambiarAseguradora.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                btnCambiarAseguradoraPropertyChange(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Salario bruto:");

        lblSalarioBruto.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblSalarioBruto.setForeground(new java.awt.Color(255, 255, 255));

        btnGuardarCambios.setBackground(new java.awt.Color(51, 153, 0));
        btnGuardarCambios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/btn_guardar.png"))); // NOI18N
        btnGuardarCambios.setText("Guardar cambios");
        btnGuardarCambios.setBackground_Hover_1(new java.awt.Color(51, 153, 0));
        btnGuardarCambios.setBackground_Hover_2(new java.awt.Color(51, 153, 0));
        btnGuardarCambios.setBackground_No_Hover_1(new java.awt.Color(255, 204, 0));
        btnGuardarCambios.setBackground_No_Hover_2(new java.awt.Color(255, 204, 0));
        btnGuardarCambios.setColor_NoHover_text(new java.awt.Color(0, 0, 0));
        btnGuardarCambios.setEsquina_inferior_derecho(20);
        btnGuardarCambios.setEsquina_inferior_izquierdo(20);
        btnGuardarCambios.setEsquina_superior_derecho(20);
        btnGuardarCambios.setEsquina_superior_izquierdo(20);
        btnGuardarCambios.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btnGuardarCambios.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnGuardarCambios.setIconTextGap(8);
        btnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSalarioBruto, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSalarioNeto, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCambiarAseguradora, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAsignarSeguroSalud, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblSalarioNeto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSalarioBruto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnCambiarAseguradora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAsignarSeguroSalud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jLabel13.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("A tener en cuenta:");

        jTable1.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Retención", "Tipo de retención", "Aporte obligatorio", "Prima de seguro", "Comisión fija", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(15);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(15);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(20);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(20);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(15);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(btnVolver5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVolver5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolver5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolver5ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        llenarTablaInicial();
        llenarTablaATenerEnCuenta();
    }//GEN-LAST:event_formWindowOpened

    private void btnBuscarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEmpleadoActionPerformed
        jdVentanaBuscarEmpleadoContratoVigente obj = new jdVentanaBuscarEmpleadoContratoVigente((Frame) SwingUtilities.getWindowAncestor(this),
                true);
        obj.setVisible(true);
        if (obj.getNumdoc() != null && obj.getTipodoc() != null) {
            try {
                lblApeMaterno.setText(obj.getApemat());
                lblApePaterno.setText(obj.getApepat());
                lblArea.setText(obj.getNomarea());
                lblNombres.setText(obj.getNombres());
                lblNumDocumento.setText(obj.getNumdoc());
                lblTipoDoc.setText(obj.getTipodoc());
                lblTipoEmpleado.setText(obj.getTipoemp());
                listarDeduccionesCliente(lblNumDocumento, lblTipoDoc);
                calcularTotales();
            } catch (Exception ex) {
                Logger.getLogger(jdGestionFondoPensionSeguroSalud.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnBuscarEmpleadoActionPerformed

    private void lblNumDocumentoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblNumDocumentoPropertyChange

    }//GEN-LAST:event_lblNumDocumentoPropertyChange

    private void lblTipoEmpleadoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblTipoEmpleadoPropertyChange

    }//GEN-LAST:event_lblTipoEmpleadoPropertyChange

    private void btnAsignarSeguroSaludActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarSeguroSaludActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "¿ASignar seguro de salud?", "Confirmar cambios", JOptionPane.YES_NO_OPTION)
                == JOptionPane.YES_OPTION) {
            try {
                setearSeguroSalud();
                calcularTotales();
            } catch (Exception ex) {
                Logger.getLogger(jdGestionFondoPensionSeguroSalud.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnAsignarSeguroSaludActionPerformed

    private void btnAsignarSeguroSaludPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_btnAsignarSeguroSaludPropertyChange

    }//GEN-LAST:event_btnAsignarSeguroSaludPropertyChange

    private void btnCambiarAseguradoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarAseguradoraActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "¿Cambiar aseguradora de fondo de pensiones?", "Confirmar cambios", JOptionPane.YES_NO_OPTION)
                == JOptionPane.YES_OPTION) {
            try {
                setearNombreDiferenteFondoPension();
                calcularTotales();
            } catch (Exception ex) {
                Logger.getLogger(jdGestionFondoPensionSeguroSalud.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnCambiarAseguradoraActionPerformed

    private void btnCambiarAseguradoraPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_btnCambiarAseguradoraPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCambiarAseguradoraPropertyChange

    private void tblRetencionesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblRetencionesPropertyChange
        if (tblRetenciones.getRowCount() > 1) {
            btnAsignarSeguroSalud.setEnabled(false);
            btnCambiarAseguradora.setEnabled(true);
            btnGuardarCambios.setEnabled(true);
        } else if (tblRetenciones.getRowCount() == 1) {
            btnAsignarSeguroSalud.setEnabled(true);
            btnCambiarAseguradora.setEnabled(true);
            btnGuardarCambios.setEnabled(true);
        } else {
            btnAsignarSeguroSalud.setEnabled(false);
            btnCambiarAseguradora.setEnabled(false);
            btnGuardarCambios.setEnabled(false);
        }
    }//GEN-LAST:event_tblRetencionesPropertyChange

    private void tblRetencionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRetencionesMouseClicked
        if (tblRetenciones.getSelectedRowCount() > 0) {
            String retencion = tblRetenciones.getValueAt(tblRetenciones.getSelectedRow(), 0).toString();
            if (retencion.equals("AFP") || retencion.equals("ONP")) {
                btnAsignarSeguroSalud.setEnabled(false);
                btnCambiarAseguradora.setEnabled(true);
            } else {
                btnAsignarSeguroSalud.setEnabled(false);
                btnCambiarAseguradora.setEnabled(false);
            }
        }
    }//GEN-LAST:event_tblRetencionesMouseClicked

    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
        if (tblRetenciones.getRowCount() > 0) {
            if (JOptionPane.showConfirmDialog(rootPane, "¿Desea guardar los cambios?", "Confirmar cambios?", JOptionPane.YES_NO_OPTION)
                    == JOptionPane.YES_OPTION) {
                try {
                    int idemp = objE.obtenerIdEmpleado(lblNumDocumento.getText(), lblTipoDoc.getText());
                    String ret = tblRetenciones.getValueAt(0, 0).toString();
                    double montoRet = Double.parseDouble(tblRetenciones.getValueAt(0, 2).toString());
                    String seguro = "";
                    double montoSeg = 0;
                    if (tblRetenciones.getRowCount() > 1) {
                        seguro = tblRetenciones.getValueAt(1, 0).toString();
                        montoSeg = Double.parseDouble(tblRetenciones.getValueAt(1, 2).toString());
                    } else {
                        seguro = "";
                        montoSeg = 0;
                    }
                    double salarioNeto = Double.parseDouble(lblSalarioNeto.getText().substring(4, lblSalarioNeto.getText().length()));
                    double salarioBruto = Double.parseDouble(lblSalarioBruto.getText().substring(4, lblSalarioBruto.getText().length()));
                    objC.actualizaRetencionesContratoEmpleado(idemp, ret, montoRet, seguro, montoSeg, salarioBruto, salarioNeto);
                    JOptionPane.showMessageDialog(rootPane, "Retenciones de ley actualizadas");
                    listarDeduccionesCliente(lblNumDocumento, lblTipoDoc);
                    calcularTotales();
                } catch (Exception ex) {
                    Logger.getLogger(jdGestionFondoPensionSeguroSalud.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed

    private void llenarTablaInicial() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Retención");
        modelo.addColumn("Tipo de retención");
        modelo.addColumn("Monto retenido");

        tblRetenciones.setModel(modelo);
    }

    private void listarDeduccionesCliente(JLabel numdoc, JLabel tipodoc) throws Exception {
        int idempl = objE.obtenerIdEmpleado(numdoc.getText(), tipodoc.getText());
        ResultSet rs = objD.listarDeduccionesContratoCliente(idempl);

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Retención");
        modelo.addColumn("Tipo de retención");
        modelo.addColumn("Monto retenido");

        Object datos[] = new Object[3];

        while (rs.next()) {
            datos[0] = rs.getString("retencion");
            datos[1] = rs.getString("tiporetencion");
            datos[2] = rs.getDouble("montoretenido");
            modelo.addRow(datos);
        }

        tblRetenciones.setModel(modelo);
    }

    private double[] obtenerSalarioBrutoEmpleado() throws Exception {
        int idempl = objE.obtenerIdEmpleado(lblNumDocumento.getText(), lblTipoDoc.getText());
        double salario[] = objC.obtenerSalarioContratoEmpleado(idempl);
        return salario;
    }

    private double obtenerNvoSalarioNeto() {
        double salariobr = Double.parseDouble(lblSalarioBruto.getText().substring(4, lblSalarioBruto.getText().length()));
        double montoRet = Double.parseDouble(tblRetenciones.getValueAt(0, 2).toString());
        double montoSS = 0;
        if (tblRetenciones.getRowCount() > 1) {
            montoSS = Double.parseDouble(tblRetenciones.getValueAt(1, 2).toString());
        }
        double montoNvo = salariobr - montoRet - montoSS;
        return montoNvo;
    }

    private void calcularTotales() throws Exception {
        lblSalarioBruto.setText("S/. " + String.format("%.2f", obtenerSalarioBrutoEmpleado()[1]));
        lblSalarioNeto.setText("S/. " + String.format("%.2f", obtenerNvoSalarioNeto()));
    }

    private void setearNombreDiferenteFondoPension() throws Exception {
        String nombreDif = objD.obtenerNombreDeduccionDiferente(tblRetenciones.getValueAt(0, 0).toString()); //ONP
        double salariobr = Double.parseDouble(lblSalarioBruto.getText().substring(4, lblSalarioBruto.getText().length())); //1200

        double montoRet = 0;
        DefaultTableModel modelo = (DefaultTableModel) tblRetenciones.getModel();
        if (nombreDif.equals("AFP")) {
            montoRet = salariobr - (0.8666 * salariobr);
            modelo.setValueAt(nombreDif, 0, 0);
            modelo.setValueAt(String.format("%.2f", montoRet), 0, 2);
        } else if (nombreDif.equals("ONP")) {
            montoRet = salariobr - (0.87 * salariobr);
            modelo.setValueAt(nombreDif, 0, 0);
            modelo.setValueAt(String.format("%.2f", montoRet), 0, 2);
        }
    }

    private void setearSeguroSalud() {
        double salariobr = Double.parseDouble(lblSalarioBruto.getText().substring(4, lblSalarioBruto.getText().length()));
        double montoRetSS = salariobr - (0.91 * salariobr);
        DefaultTableModel modelo = (DefaultTableModel) tblRetenciones.getModel();
        modelo.addRow(new Object[]{"EsSalud", "Seguro de salud", montoRetSS});
    }

    private void llenarTablaATenerEnCuenta() {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.addRow(new Object[]{"AFP", "Seguro de fondo de pensiones", "10 %", "1.74 %", "1.60 %", "13.34 %"});
        modelo.addRow(new Object[]{"ONP", "Seguro de fondo de pensiones", "13 %", "0.00 %", "0.00 %", "13.00 %"});
        modelo.addRow(new Object[]{"EsSalud", "Seguro social de salud", "9 %", "No aplica", "No aplica%", "9 %"});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnAsignarSeguroSalud;
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnBuscarEmpleado;
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnCambiarAseguradora;
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnGuardarCambios;
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnVolver5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblApeMaterno;
    private javax.swing.JLabel lblApePaterno;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblNumDocumento;
    private javax.swing.JLabel lblSalarioBruto;
    private javax.swing.JLabel lblSalarioNeto;
    private javax.swing.JLabel lblTipoDoc;
    private javax.swing.JLabel lblTipoEmpleado;
    private javax.swing.JTable tblRetenciones;
    // End of variables declaration//GEN-END:variables
}
