package Presentacion;

import Negocio.Empleado2;
import Negocio.TipoDocumento;
import Negocio.TipoEmpleado;
import java.awt.Color;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.Timer;

/**
 *
 * @GRUPO 4
 */
public class jdMantenimientoEmpleado extends javax.swing.JDialog {

    TipoDocumento tdoc = new TipoDocumento();
    TipoEmpleado temple = new TipoEmpleado();
    Empleado2 mante = new Empleado2();
    
    private static final int ANIMATION_DURATION = 1000; // Duración de la animación en milisegundos
    

    public jdMantenimientoEmpleado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        try {
            tdoc.listarTipoDocumento(cbxTipoDocumento);
            temple.listarEmpleado(cbxTipoEmpleado);
            mante.listarSuperior(cbxSuperior);
            mante.listarTablaTrabajadores(tabla_Empleado);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
        
    }

    public void limpiar() {
        try {
            mante.listarTablaTrabajadores(tabla_Empleado);
            txtNumeroDocumento.setText("");
            txtNombres.setText("");
            txtApePaterno.setText("");
            txtApeMaterno.setText("");
            txtCorreo.setText("");
            txtNumTelefono.setText("");
            cbxSuperior.setSelectedIndex(0);
            cbxTipoDocumento.setSelectedIndex(0);
            cbxTipoEmpleado.setSelectedIndex(0);
            chbVigencia.setSelected(true);
            ckbTieneHijos.setEnabled(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudo limpiar el contenido: " + e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Round_JWC1 = new swing.Panel_Round_JWC();
        panel_Round_Degradado_JWC1 = new panel_degradado_jwc.Panel_Round_Degradado_JWC();
        panel_Round_JWC2 = new swing.Panel_Round_JWC();
        btnAgregar = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        btnEliminar = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        btnLimpiar = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        btnDarBaja = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        btnEditar = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        jLabel3 = new javax.swing.JLabel();
        txtNumeroDocumento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbxTipoDocumento = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtApePaterno = new javax.swing.JTextField();
        txtApeMaterno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNumTelefono = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        chbVigencia = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        cbxTipoEmpleado = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cbxSuperior = new javax.swing.JComboBox<>();
        btnBuscar = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        jLabel15 = new javax.swing.JLabel();
        ckbTieneHijos = new javax.swing.JCheckBox();
        panel_Round_Degradado_JWC2 = new panel_degradado_jwc.Panel_Round_Degradado_JWC();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_Empleado = new javax.swing.JTable();
        btnCerrar = new swing.Btn_Round_JWC();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1055, 590));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_Round_JWC1.setBackground(new java.awt.Color(255, 255, 255));
        panel_Round_JWC1.setEsqInferiorDerecha(50);
        panel_Round_JWC1.setEsqInferiorIzquierda(50);
        panel_Round_JWC1.setEsqSuperiorDerecha(50);
        panel_Round_JWC1.setEsqSuperiorIzquierda(50);
        panel_Round_JWC1.setPreferredSize(new java.awt.Dimension(1055, 590));

        panel_Round_Degradado_JWC1.setColor1(new java.awt.Color(69, 161, 137));
        panel_Round_Degradado_JWC1.setColor2(new java.awt.Color(69, 161, 137));
        panel_Round_Degradado_JWC1.setEnabled(false);
        panel_Round_Degradado_JWC1.setSuperior_derecho(50);
        panel_Round_Degradado_JWC1.setSuperior_izquierdo(50);

        panel_Round_JWC2.setBackground(new java.awt.Color(51, 51, 51));
        panel_Round_JWC2.setEsqInferiorDerecha(50);
        panel_Round_JWC2.setEsqInferiorIzquierda(50);
        panel_Round_JWC2.setEsqSuperiorDerecha(50);
        panel_Round_JWC2.setEsqSuperiorIzquierda(50);

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/anadir (2).png"))); // NOI18N
        btnAgregar.setText("");
        btnAgregar.setBackground_Hover_1(new java.awt.Color(255, 255, 255));
        btnAgregar.setBackground_Hover_2(new java.awt.Color(255, 255, 255));
        btnAgregar.setBackground_No_Hover_1(new java.awt.Color(221, 239, 168));
        btnAgregar.setBackground_No_Hover_2(new java.awt.Color(146, 161, 214));
        btnAgregar.setEsquina_inferior_derecho(50);
        btnAgregar.setEsquina_inferior_izquierdo(50);
        btnAgregar.setEsquina_superior_derecho(50);
        btnAgregar.setEsquina_superior_izquierdo(50);
        btnAgregar.setFocusPainted(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton-eliminar (1).png"))); // NOI18N
        btnEliminar.setText("");
        btnEliminar.setBackground_Hover_1(new java.awt.Color(255, 153, 153));
        btnEliminar.setBackground_Hover_2(new java.awt.Color(255, 153, 153));
        btnEliminar.setBackground_No_Hover_1(new java.awt.Color(245, 226, 226));
        btnEliminar.setBackground_No_Hover_2(new java.awt.Color(245, 226, 226));
        btnEliminar.setEsquina_inferior_derecho(50);
        btnEliminar.setEsquina_inferior_izquierdo(50);
        btnEliminar.setEsquina_superior_derecho(50);
        btnEliminar.setEsquina_superior_izquierdo(50);
        btnEliminar.setFocusPainted(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escoba (1).png"))); // NOI18N
        btnLimpiar.setText("");
        btnLimpiar.setBackground_Hover_1(new java.awt.Color(255, 255, 255));
        btnLimpiar.setBackground_Hover_2(new java.awt.Color(255, 255, 255));
        btnLimpiar.setBackground_No_Hover_1(new java.awt.Color(221, 239, 168));
        btnLimpiar.setBackground_No_Hover_2(new java.awt.Color(146, 161, 214));
        btnLimpiar.setEsquina_inferior_derecho(50);
        btnLimpiar.setEsquina_inferior_izquierdo(50);
        btnLimpiar.setEsquina_superior_derecho(50);
        btnLimpiar.setEsquina_superior_izquierdo(50);
        btnLimpiar.setFocusPainted(false);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnDarBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/bajo-rendimiento (1).png"))); // NOI18N
        btnDarBaja.setText("");
        btnDarBaja.setBackground_Hover_1(new java.awt.Color(255, 255, 255));
        btnDarBaja.setBackground_Hover_2(new java.awt.Color(255, 255, 255));
        btnDarBaja.setBackground_No_Hover_1(new java.awt.Color(221, 239, 168));
        btnDarBaja.setBackground_No_Hover_2(new java.awt.Color(146, 161, 214));
        btnDarBaja.setEsquina_inferior_derecho(50);
        btnDarBaja.setEsquina_inferior_izquierdo(50);
        btnDarBaja.setEsquina_superior_derecho(50);
        btnDarBaja.setEsquina_superior_izquierdo(50);
        btnDarBaja.setFocusPainted(false);
        btnDarBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarBajaActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/editar (1).png"))); // NOI18N
        btnEditar.setText("");
        btnEditar.setBackground_Hover_1(new java.awt.Color(255, 255, 255));
        btnEditar.setBackground_Hover_2(new java.awt.Color(255, 255, 255));
        btnEditar.setBackground_No_Hover_1(new java.awt.Color(221, 239, 168));
        btnEditar.setBackground_No_Hover_2(new java.awt.Color(146, 161, 214));
        btnEditar.setEsquina_inferior_derecho(50);
        btnEditar.setEsquina_inferior_izquierdo(50);
        btnEditar.setEsquina_superior_derecho(50);
        btnEditar.setEsquina_superior_izquierdo(50);
        btnEditar.setFocusPainted(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_Round_JWC2Layout = new javax.swing.GroupLayout(panel_Round_JWC2);
        panel_Round_JWC2.setLayout(panel_Round_JWC2Layout);
        panel_Round_JWC2Layout.setHorizontalGroup(
            panel_Round_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Round_JWC2Layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDarBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        panel_Round_JWC2Layout.setVerticalGroup(
            panel_Round_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_JWC2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_Round_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDarBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("N° DOC:");

        txtNumeroDocumento.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        txtNumeroDocumento.setSelectionColor(new java.awt.Color(0, 204, 0));
        txtNumeroDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumeroDocumentoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroDocumentoKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TIPO DOC.:");
        jLabel4.setPreferredSize(new java.awt.Dimension(173, 23));

        cbxTipoDocumento.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        cbxTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----------------" }));
        cbxTipoDocumento.setPreferredSize(new java.awt.Dimension(132, 22));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("APELLIDO P.:");
        jLabel5.setPreferredSize(new java.awt.Dimension(173, 23));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("APELLIDO M.:");

        txtApePaterno.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        txtApePaterno.setPreferredSize(new java.awt.Dimension(132, 22));
        txtApePaterno.setSelectionColor(new java.awt.Color(0, 204, 0));
        txtApePaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApePaternoKeyTyped(evt);
            }
        });

        txtApeMaterno.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        txtApeMaterno.setSelectionColor(new java.awt.Color(0, 204, 0));
        txtApeMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApeMaternoKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NOMBRES:");

        txtNombres.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        txtNombres.setPreferredSize(new java.awt.Dimension(253, 22));
        txtNombres.setSelectionColor(new java.awt.Color(0, 204, 0));
        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombresKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CORREO:");

        txtCorreo.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        txtCorreo.setPreferredSize(new java.awt.Dimension(253, 22));
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("TELEFONO:");

        txtNumTelefono.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        txtNumTelefono.setSelectionColor(new java.awt.Color(0, 204, 0));
        txtNumTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumTelefonoKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ESTADO:");

        chbVigencia.setBackground(new java.awt.Color(69, 161, 137));
        chbVigencia.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        chbVigencia.setForeground(new java.awt.Color(255, 255, 255));
        chbVigencia.setSelected(true);
        chbVigencia.setText("VIGENTE");

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("TIPO DE EMP.:");

        cbxTipoEmpleado.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        cbxTipoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------------------" }));
        cbxTipoEmpleado.setPreferredSize(new java.awt.Dimension(132, 22));

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("SUPERIOR:");

        cbxSuperior.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        cbxSuperior.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------------------" }));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/lupa (1).png"))); // NOI18N
        btnBuscar.setText("");
        btnBuscar.setBackground_No_Hover_2(new java.awt.Color(155, 170, 224));
        btnBuscar.setEsquina_inferior_derecho(20);
        btnBuscar.setEsquina_inferior_izquierdo(20);
        btnBuscar.setEsquina_superior_derecho(20);
        btnBuscar.setEsquina_superior_izquierdo(20);
        btnBuscar.setFocusPainted(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("MANTENIMIENTO DE EMPLEADO"); // NOI18N

        ckbTieneHijos.setBackground(new java.awt.Color(69, 161, 137));
        ckbTieneHijos.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        ckbTieneHijos.setForeground(new java.awt.Color(255, 255, 255));
        ckbTieneHijos.setSelected(true);
        ckbTieneHijos.setText("TIENE HIJOS");

        javax.swing.GroupLayout panel_Round_Degradado_JWC1Layout = new javax.swing.GroupLayout(panel_Round_Degradado_JWC1);
        panel_Round_Degradado_JWC1.setLayout(panel_Round_Degradado_JWC1Layout);
        panel_Round_Degradado_JWC1Layout.setHorizontalGroup(
            panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                                .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                                        .addGap(122, 122, 122)
                                        .addComponent(panel_Round_JWC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                                        .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                                                .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(chbVigencia, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                                                        .addGap(19, 19, 19)
                                                        .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                    .addGroup(panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel9)))))
                                        .addGap(12, 12, 12)
                                        .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                                                .addComponent(cbxTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                                                    .addComponent(cbxTipoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(12, 12, 12)
                                                    .addComponent(jLabel14)
                                                    .addGap(37, 37, 37)
                                                    .addComponent(cbxSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                                                    .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                                                            .addComponent(txtApePaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jLabel6))
                                                        .addGroup(panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                                                            .addComponent(txtNumTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                            .addComponent(ckbTieneHijos)
                                                            .addGap(0, 0, Short.MAX_VALUE)))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(txtApeMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGroup(panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(637, 637, 637))))
                    .addGroup(panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        panel_Round_Degradado_JWC1Layout.setVerticalGroup(
            panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                        .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                        .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApePaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtApeMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(ckbTieneHijos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cbxTipoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(cbxSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(chbVigencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(panel_Round_JWC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        panel_Round_Degradado_JWC2.setColor1(new java.awt.Color(69, 161, 137));
        panel_Round_Degradado_JWC2.setColor2(new java.awt.Color(69, 161, 137));
        panel_Round_Degradado_JWC2.setEnabled(false);
        panel_Round_Degradado_JWC2.setInferior_derecho(50);
        panel_Round_Degradado_JWC2.setInferior_izquierdo(50);

        tabla_Empleado.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        tabla_Empleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabla_Empleado.setGridColor(new java.awt.Color(0, 0, 0));
        tabla_Empleado.setSelectionBackground(new java.awt.Color(153, 153, 153));
        tabla_Empleado.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabla_Empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_EmpleadoMouseClicked(evt);
            }
        });
        tabla_Empleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabla_EmpleadoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_Empleado);

        btnCerrar.setBackground(new java.awt.Color(51, 51, 51));
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("CERRAR");
        btnCerrar.setArco_esquina(20);
        btnCerrar.setColor_Hover(new java.awt.Color(93, 93, 93));
        btnCerrar.setColor_Normal(new java.awt.Color(51, 51, 51));
        btnCerrar.setFocusPainted(false);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_Round_Degradado_JWC2Layout = new javax.swing.GroupLayout(panel_Round_Degradado_JWC2);
        panel_Round_Degradado_JWC2.setLayout(panel_Round_Degradado_JWC2Layout);
        panel_Round_Degradado_JWC2Layout.setHorizontalGroup(
            panel_Round_Degradado_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_Degradado_JWC2Layout.createSequentialGroup()
                .addGap(391, 391, 391)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(439, Short.MAX_VALUE))
            .addGroup(panel_Round_Degradado_JWC2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panel_Round_Degradado_JWC2Layout.setVerticalGroup(
            panel_Round_Degradado_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_Degradado_JWC2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panel_Round_JWC1Layout = new javax.swing.GroupLayout(panel_Round_JWC1);
        panel_Round_JWC1.setLayout(panel_Round_JWC1Layout);
        panel_Round_JWC1Layout.setHorizontalGroup(
            panel_Round_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_JWC1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_Round_Degradado_JWC2, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Round_JWC1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel_Round_Degradado_JWC1, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_Round_JWC1Layout.setVerticalGroup(
            panel_Round_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_JWC1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_Round_Degradado_JWC1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Round_Degradado_JWC2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(panel_Round_JWC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try {
            if (txtNombres.getText().isBlank() || cbxTipoDocumento.getSelectedIndex() == 0 || txtApePaterno.getText().isBlank()
                    || txtNumeroDocumento.getText().isBlank() || txtApeMaterno.getText().isBlank() || txtNumTelefono.getText().isBlank()
                    || cbxTipoEmpleado.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Por favor complete todos los campos");
            } else {
                mante.agregarTrabajador(txtNumeroDocumento, cbxTipoDocumento, txtNombres, txtApePaterno, txtApeMaterno, txtCorreo,
                        "", "", txtNumTelefono, chbVigencia, cbxTipoEmpleado, cbxSuperior, ckbTieneHijos);
                limpiar();
                JOptionPane.showMessageDialog(null, "Empleado registrado correctamente");

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "No se pudo agregar al empleado.\nError: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        try {
            if (txtNumeroDocumento.getText().isBlank() || cbxTipoDocumento.getSelectedIndex() == 0 || txtNombres.getText().isBlank() || cbxTipoDocumento.getSelectedIndex() == 0 || txtApePaterno.getText().isBlank()
                    || txtNumeroDocumento.getText().isBlank() || txtApeMaterno.getText().isBlank() || txtNumTelefono.getText().isBlank()
                    || cbxTipoEmpleado.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Por favor complete todos los campos");
            } else {
                if (JOptionPane.showConfirmDialog(rootPane, "¿Modificar datos?", "Confirmar cambios", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    mante.editarTrabajador(txtNumeroDocumento, cbxTipoDocumento, txtNombres, txtApePaterno, txtApeMaterno, txtCorreo, "", "",
                            txtNumTelefono, chbVigencia, cbxTipoEmpleado, cbxSuperior,ckbTieneHijos);
                    limpiar();
                    JOptionPane.showMessageDialog(null, "Los datos del empleado se actualizaron correctamente");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "No se pudo actualizar los datos del empleado. Intente nuevamente");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            if (txtNumeroDocumento.getText().isEmpty() | cbxTipoDocumento.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Ingrese un número y tipo de documento válidos");
            } else {
                if (JOptionPane.showConfirmDialog(rootPane, "¿Eliminar empleado?", "Confirmar cambios", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    if (!mante.existenTablasReferenciadasEmpleado(txtNumeroDocumento, cbxTipoDocumento)) {
                        mante.eliminarTrabajador(txtNumeroDocumento, cbxTipoDocumento);
                        limpiar();
                        JOptionPane.showMessageDialog(null, "El empleado fue eliminado correctamente");
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "No se puede eliminar. El empleado ya se encuentra referenciado en otras tablas");
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "No se pudo eliminar el empleado: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnDarBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarBajaActionPerformed
        try {
            if (txtNumeroDocumento.getText().isBlank() | cbxTipoDocumento.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Ingrese un número y tipo de documento válidos");
            } else {
                mante.darBajaTrabajador(txtNumeroDocumento, cbxTipoDocumento);
                limpiar();
                JOptionPane.showMessageDialog(null, "Empleado dado de baja");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "No se pudo dar de baja al trabajador");
        }
    }//GEN-LAST:event_btnDarBajaActionPerformed

    private void txtNumeroDocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroDocumentoKeyTyped
        if (txtNumeroDocumento.getText().length() >= 20) {
            evt.consume();
        }

        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtNumeroDocumentoKeyTyped

    private void txtNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyTyped
        if (txtNombres.getText().length() >= 200) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombresKeyTyped

    private void txtApePaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApePaternoKeyTyped
        if (txtApePaterno.getText().length() >= 200) {
            evt.consume();
        }
    }//GEN-LAST:event_txtApePaternoKeyTyped

    private void txtApeMaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApeMaternoKeyTyped
        if (txtApeMaterno.getText().length() >= 200) {
            evt.consume();
        }
    }//GEN-LAST:event_txtApeMaternoKeyTyped

    private void txtCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyTyped
        if (txtCorreo.getText().length() >= 200) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCorreoKeyTyped

    private void txtNumTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumTelefonoKeyTyped
        if (txtNumTelefono.getText().length() >= 20) {
            evt.consume();
        }

        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtNumTelefonoKeyTyped

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (txtNumeroDocumento.getText().isBlank() | cbxTipoDocumento.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Ingrese un número y un tipo de documento válidos");
        } else {
            try {
                //Agregar método existeEmpleado a la clase MantenimientoTrabajador:
                String numdoc = txtNumeroDocumento.getText();
                String tipodoc = cbxTipoDocumento.getSelectedItem().toString();
                if (!mante.existeEmpleado(numdoc, tipodoc)) {
                    JOptionPane.showMessageDialog(rootPane, "No se encontró el empleado");
                } else {
                    buscarTrabajador(numdoc, tipodoc);
                    txtNumeroDocumento.setText("");
                    cbxTipoDocumento.setSelectedIndex(0);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "No se pudo ejecutar la búsqueda --> " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tabla_EmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_EmpleadoMouseClicked
        if (tabla_Empleado.getSelectedRowCount() > 0) {
            String numdoc = tabla_Empleado.getValueAt(tabla_Empleado.getSelectedRow(), 0).toString();
            String tipodoc = tabla_Empleado.getValueAt(tabla_Empleado.getSelectedRow(), 1).toString();
            String nombres = tabla_Empleado.getValueAt(tabla_Empleado.getSelectedRow(), 2).toString();
            String apep = tabla_Empleado.getValueAt(tabla_Empleado.getSelectedRow(), 3).toString();
            String apem = tabla_Empleado.getValueAt(tabla_Empleado.getSelectedRow(), 4).toString();
            String correo = "";
            if (tabla_Empleado.getValueAt(tabla_Empleado.getSelectedRow(), 5) == null) {
                correo = "";
            } else {
                correo = tabla_Empleado.getValueAt(tabla_Empleado.getSelectedRow(), 5).toString();
            }
            
            String telefono = tabla_Empleado.getValueAt(tabla_Empleado.getSelectedRow(), 6).toString();
            
            if (tabla_Empleado.getValueAt(tabla_Empleado.getSelectedRow(), 7).toString().equals("Vigente")) {
                chbVigencia.setSelected(true);
            } else {
                chbVigencia.setSelected(false);
            }
            
            String tipoemp = tabla_Empleado.getValueAt(tabla_Empleado.getSelectedRow(), 8).toString();
            String superior = tabla_Empleado.getValueAt(tabla_Empleado.getSelectedRow(), 9).toString();
            
            if (tabla_Empleado.getValueAt(tabla_Empleado.getSelectedRow(), 10).toString().equals("Sí")) {
                ckbTieneHijos.setSelected(true);
            } else {
                ckbTieneHijos.setSelected(false);
            }

            txtNumeroDocumento.setText(numdoc);
            cbxTipoDocumento.setSelectedItem(tipodoc);
            txtNombres.setText(nombres);
            txtApePaterno.setText(apep);
            txtApeMaterno.setText(apem);
            txtCorreo.setText(correo);
            txtNumTelefono.setText(telefono);
            cbxTipoEmpleado.setSelectedItem(tipoemp);
            cbxSuperior.setSelectedItem(superior);
        }
    }//GEN-LAST:event_tabla_EmpleadoMouseClicked

    private void txtNumeroDocumentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroDocumentoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroDocumentoKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            tdoc.listarTipoDocumento(cbxTipoDocumento);
            temple.listarEmpleado(cbxTipoEmpleado);
            mante.listarSuperior(cbxSuperior);
            mante.listarTablaTrabajadores(tabla_Empleado);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_formWindowActivated

    private void tabla_EmpleadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabla_EmpleadoKeyReleased
        if (tabla_Empleado.getSelectedRowCount() > 0) {
            String numdoc = tabla_Empleado.getValueAt(tabla_Empleado.getSelectedRow(), 0).toString();
            String tipodoc = tabla_Empleado.getValueAt(tabla_Empleado.getSelectedRow(), 1).toString();
            String nombres = tabla_Empleado.getValueAt(tabla_Empleado.getSelectedRow(), 2).toString();
            String apep = tabla_Empleado.getValueAt(tabla_Empleado.getSelectedRow(), 3).toString();
            String apem = tabla_Empleado.getValueAt(tabla_Empleado.getSelectedRow(), 4).toString();
            String correo = "";
            if (tabla_Empleado.getValueAt(tabla_Empleado.getSelectedRow(), 5) == null) {
                correo = "";
            } else {
                correo = tabla_Empleado.getValueAt(tabla_Empleado.getSelectedRow(), 5).toString();
            }
            
            String telefono = tabla_Empleado.getValueAt(tabla_Empleado.getSelectedRow(), 6).toString();
            
            if (tabla_Empleado.getValueAt(tabla_Empleado.getSelectedRow(), 7).toString().equals("Vigente")) {
                chbVigencia.setSelected(true);
            } else {
                chbVigencia.setSelected(false);
            }
            
            String tipoemp = tabla_Empleado.getValueAt(tabla_Empleado.getSelectedRow(), 8).toString();
            String superior = tabla_Empleado.getValueAt(tabla_Empleado.getSelectedRow(), 9).toString();
            
            if (tabla_Empleado.getValueAt(tabla_Empleado.getSelectedRow(), 10).toString().equals("Sí")) {
                ckbTieneHijos.setSelected(true);
            } else {
                ckbTieneHijos.setSelected(false);
            }

            txtNumeroDocumento.setText(numdoc);
            cbxTipoDocumento.setSelectedItem(tipodoc);
            txtNombres.setText(nombres);
            txtApePaterno.setText(apep);
            txtApeMaterno.setText(apem);
            txtCorreo.setText(correo);
            txtNumTelefono.setText(telefono);
            cbxTipoEmpleado.setSelectedItem(tipoemp);
            cbxSuperior.setSelectedItem(superior);
        }
    }//GEN-LAST:event_tabla_EmpleadoKeyReleased

    private void buscarTrabajador(String numdoc, String tipodoc) throws Exception {
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("N° de Documento");
        model.addColumn("Tipo de documento");
        model.addColumn("Nombres");
        model.addColumn("Apellido paterno");
        model.addColumn("Apellido materno");
        model.addColumn("Correo");
        model.addColumn("Teléfono");
        model.addColumn("Estado");
        model.addColumn("Tipo de empleado");
        model.addColumn("Supervisor");
        model.addColumn("Con hijos");

        ResultSet rs = mante.buscarTrabajador(numdoc, tipodoc);

        Object datos[] = new Object[11];

        while (rs.next()) {
            datos[0] = rs.getString("numerodocu");
            datos[1] = rs.getString("nombre_tipo_documento");
            datos[2] = rs.getString("nombre");//nombre
            datos[3] = rs.getString("apepaterno"); //apepat
            datos[4] = rs.getString("apematerno"); //apemat
            datos[5] = rs.getString("correoempleado");
            datos[6] = rs.getString("telefonoempleado");

            switch (rs.getString("estadousuario")) {
                case "V":
                    datos[7] = "Vigente";
                    break;
                case "N":
                    datos[7] = "No vigente";
                    break;
                case "R":
                    datos[7] = "Renunció";
                    break;
                default:
                    datos[7] = "Despedido";
                    break;
            }

            datos[8] = rs.getString("nombre_tipo_empleado");//
            datos[9] = rs.getString("nombre_empleado");
            datos[10] = rs.getString("tienehijos");
            model.addRow(datos);
        }
        tabla_Empleado.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnAgregar;
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnBuscar;
    private swing.Btn_Round_JWC btnCerrar;
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnDarBaja;
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnEditar;
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnEliminar;
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnLimpiar;
    private javax.swing.JComboBox<String> cbxSuperior;
    private javax.swing.JComboBox<String> cbxTipoDocumento;
    private javax.swing.JComboBox<String> cbxTipoEmpleado;
    private javax.swing.JCheckBox chbVigencia;
    private javax.swing.JCheckBox ckbTieneHijos;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private panel_degradado_jwc.Panel_Round_Degradado_JWC panel_Round_Degradado_JWC1;
    private panel_degradado_jwc.Panel_Round_Degradado_JWC panel_Round_Degradado_JWC2;
    private swing.Panel_Round_JWC panel_Round_JWC1;
    private swing.Panel_Round_JWC panel_Round_JWC2;
    private javax.swing.JTable tabla_Empleado;
    private javax.swing.JTextField txtApeMaterno;
    private javax.swing.JTextField txtApePaterno;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtNumTelefono;
    private javax.swing.JTextField txtNumeroDocumento;
    // End of variables declaration//GEN-END:variables
}
