package Presentacion;

import Negocio.TipoDocumento;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @GRUPO 4
 */
public class jdMantenimientoTipoDocumento extends javax.swing.JDialog {

    TipoDocumento tdoc = new TipoDocumento();

    public jdMantenimientoTipoDocumento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        setLocationRelativeTo(this);
        //txtCodigoTipoDocumento.setEnabled(false);
        try {
            tdoc.listarTablaTipoDocumento(tabla_TipoDocumento);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al intetar listar: " + e.getMessage());
        }

        tabla_TipoDocumento.getSelectionModel().addListSelectionListener(e -> {
            if (e.getValueIsAdjusting()) {
                int seleccionFila = tabla_TipoDocumento.getSelectedRow();
                if (seleccionFila > -1) {
                    Object nombre = tabla_TipoDocumento.getValueAt(seleccionFila, 1);
                    txtNombreTipoDocumento.setText(nombre.toString());
                }
            }
        });
    }

    public void limpiar() {
        try {
            tdoc.listarTablaTipoDocumento(tabla_TipoDocumento);
            txtNombreTipoDocumento.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudo limpiar el contenido: " + e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Round_JWC1 = new swing.Panel_Round_JWC();
        panel_Round_Degradado_JWC1 = new panel_degradado_jwc.Panel_Round_Degradado_JWC();
        jLabel4 = new javax.swing.JLabel();
        txtNombreTipoDocumento = new javax.swing.JTextField();
        panel_Round_JWC2 = new swing.Panel_Round_JWC();
        btnAgregarTipoDocumento = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        btnEditarTipoDocumento = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        btnEliminarTipoDocumento = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        btnLimpiarTipoDocumento = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panel_Round_Degradado_JWC2 = new panel_degradado_jwc.Panel_Round_Degradado_JWC();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_TipoDocumento = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        txtBuscarPorTipo = new javax.swing.JTextField();
        panel_Round_Degradado_JWC3 = new panel_degradado_jwc.Panel_Round_Degradado_JWC();
        btnCerrar = new swing.Btn_Round_JWC();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_Round_JWC1.setBackground(new java.awt.Color(255, 255, 255));
        panel_Round_JWC1.setEsqInferiorDerecha(50);
        panel_Round_JWC1.setEsqInferiorIzquierda(50);
        panel_Round_JWC1.setEsqSuperiorDerecha(50);
        panel_Round_JWC1.setEsqSuperiorIzquierda(50);

        panel_Round_Degradado_JWC1.setBackground(new java.awt.Color(69, 161, 137));
        panel_Round_Degradado_JWC1.setColor1(new java.awt.Color(69, 161, 137));
        panel_Round_Degradado_JWC1.setColor2(new java.awt.Color(69, 161, 137));
        panel_Round_Degradado_JWC1.setEnabled(false);
        panel_Round_Degradado_JWC1.setSuperior_izquierdo(50);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TIPO DOCUMENTO:");

        txtNombreTipoDocumento.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        txtNombreTipoDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreTipoDocumentoKeyTyped(evt);
            }
        });

        panel_Round_JWC2.setBackground(new java.awt.Color(51, 51, 51));
        panel_Round_JWC2.setEsqInferiorDerecha(50);
        panel_Round_JWC2.setEsqInferiorIzquierda(50);
        panel_Round_JWC2.setEsqSuperiorDerecha(50);
        panel_Round_JWC2.setEsqSuperiorIzquierda(50);

        btnAgregarTipoDocumento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/anadir (2).png"))); // NOI18N
        btnAgregarTipoDocumento.setText("");
        btnAgregarTipoDocumento.setBackground_Hover_1(new java.awt.Color(255, 255, 255));
        btnAgregarTipoDocumento.setBackground_Hover_2(new java.awt.Color(255, 255, 255));
        btnAgregarTipoDocumento.setBackground_No_Hover_1(new java.awt.Color(221, 239, 168));
        btnAgregarTipoDocumento.setBackground_No_Hover_2(new java.awt.Color(146, 161, 214));
        btnAgregarTipoDocumento.setEsquina_inferior_derecho(50);
        btnAgregarTipoDocumento.setEsquina_inferior_izquierdo(50);
        btnAgregarTipoDocumento.setEsquina_superior_derecho(50);
        btnAgregarTipoDocumento.setEsquina_superior_izquierdo(50);
        btnAgregarTipoDocumento.setFocusPainted(false);
        btnAgregarTipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTipoDocumentoActionPerformed(evt);
            }
        });

        btnEditarTipoDocumento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/editar (1).png"))); // NOI18N
        btnEditarTipoDocumento.setText("");
        btnEditarTipoDocumento.setBackground_Hover_1(new java.awt.Color(255, 255, 255));
        btnEditarTipoDocumento.setBackground_Hover_2(new java.awt.Color(255, 255, 255));
        btnEditarTipoDocumento.setBackground_No_Hover_1(new java.awt.Color(221, 239, 168));
        btnEditarTipoDocumento.setBackground_No_Hover_2(new java.awt.Color(146, 161, 214));
        btnEditarTipoDocumento.setEsquina_inferior_derecho(50);
        btnEditarTipoDocumento.setEsquina_inferior_izquierdo(50);
        btnEditarTipoDocumento.setEsquina_superior_derecho(50);
        btnEditarTipoDocumento.setEsquina_superior_izquierdo(50);
        btnEditarTipoDocumento.setFocusPainted(false);
        btnEditarTipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarTipoDocumentoActionPerformed(evt);
            }
        });

        btnEliminarTipoDocumento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton-eliminar (1).png"))); // NOI18N
        btnEliminarTipoDocumento.setText("");
        btnEliminarTipoDocumento.setBackground_Hover_1(new java.awt.Color(255, 153, 153));
        btnEliminarTipoDocumento.setBackground_Hover_2(new java.awt.Color(255, 153, 153));
        btnEliminarTipoDocumento.setBackground_No_Hover_1(new java.awt.Color(245, 226, 226));
        btnEliminarTipoDocumento.setBackground_No_Hover_2(new java.awt.Color(245, 226, 226));
        btnEliminarTipoDocumento.setEsquina_inferior_derecho(50);
        btnEliminarTipoDocumento.setEsquina_inferior_izquierdo(50);
        btnEliminarTipoDocumento.setEsquina_superior_derecho(50);
        btnEliminarTipoDocumento.setEsquina_superior_izquierdo(50);
        btnEliminarTipoDocumento.setFocusPainted(false);
        btnEliminarTipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTipoDocumentoActionPerformed(evt);
            }
        });

        btnLimpiarTipoDocumento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escoba (1).png"))); // NOI18N
        btnLimpiarTipoDocumento.setText("");
        btnLimpiarTipoDocumento.setBackground_Hover_1(new java.awt.Color(255, 255, 255));
        btnLimpiarTipoDocumento.setBackground_Hover_2(new java.awt.Color(255, 255, 255));
        btnLimpiarTipoDocumento.setBackground_No_Hover_1(new java.awt.Color(221, 239, 168));
        btnLimpiarTipoDocumento.setBackground_No_Hover_2(new java.awt.Color(146, 161, 214));
        btnLimpiarTipoDocumento.setEsquina_inferior_derecho(50);
        btnLimpiarTipoDocumento.setEsquina_inferior_izquierdo(50);
        btnLimpiarTipoDocumento.setEsquina_superior_derecho(50);
        btnLimpiarTipoDocumento.setEsquina_superior_izquierdo(50);
        btnLimpiarTipoDocumento.setFocusPainted(false);
        btnLimpiarTipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarTipoDocumentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_Round_JWC2Layout = new javax.swing.GroupLayout(panel_Round_JWC2);
        panel_Round_JWC2.setLayout(panel_Round_JWC2Layout);
        panel_Round_JWC2Layout.setHorizontalGroup(
            panel_Round_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_JWC2Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(btnAgregarTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditarTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiarTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        panel_Round_JWC2Layout.setVerticalGroup(
            panel_Round_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_JWC2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_Round_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLimpiarTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MANTENIMIENTO "); // NOI18N

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DEL TIPO DE DOCUMENTO"); // NOI18N

        javax.swing.GroupLayout panel_Round_Degradado_JWC1Layout = new javax.swing.GroupLayout(panel_Round_Degradado_JWC1);
        panel_Round_Degradado_JWC1.setLayout(panel_Round_Degradado_JWC1Layout);
        panel_Round_Degradado_JWC1Layout.setHorizontalGroup(
            panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_Round_JWC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(48, 48, 48))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        panel_Round_Degradado_JWC1Layout.setVerticalGroup(
            panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(26, 26, 26)
                .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombreTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(panel_Round_JWC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        panel_Round_Degradado_JWC2.setBackground(new java.awt.Color(69, 161, 137));
        panel_Round_Degradado_JWC2.setColor1(new java.awt.Color(69, 161, 137));
        panel_Round_Degradado_JWC2.setColor2(new java.awt.Color(69, 161, 137));
        panel_Round_Degradado_JWC2.setEnabled(false);
        panel_Round_Degradado_JWC2.setInferior_derecho(50);
        panel_Round_Degradado_JWC2.setSuperior_derecho(50);

        tabla_TipoDocumento.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        tabla_TipoDocumento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabla_TipoDocumento.setGridColor(new java.awt.Color(0, 0, 0));
        tabla_TipoDocumento.setSelectionBackground(new java.awt.Color(153, 153, 153));
        tabla_TipoDocumento.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabla_TipoDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_TipoDocumentoMouseClicked(evt);
            }
        });
        tabla_TipoDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabla_TipoDocumentoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_TipoDocumento);

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Buscar por tipo de documento:");

        txtBuscarPorTipo.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        txtBuscarPorTipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarPorTipoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panel_Round_Degradado_JWC2Layout = new javax.swing.GroupLayout(panel_Round_Degradado_JWC2);
        panel_Round_Degradado_JWC2.setLayout(panel_Round_Degradado_JWC2Layout);
        panel_Round_Degradado_JWC2Layout.setHorizontalGroup(
            panel_Round_Degradado_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_Degradado_JWC2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_Round_Degradado_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                    .addComponent(jLabel12)
                    .addComponent(txtBuscarPorTipo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_Round_Degradado_JWC2Layout.setVerticalGroup(
            panel_Round_Degradado_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_Degradado_JWC2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarPorTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        panel_Round_Degradado_JWC3.setBackground(new java.awt.Color(69, 161, 137));
        panel_Round_Degradado_JWC3.setColor1(new java.awt.Color(69, 161, 137));
        panel_Round_Degradado_JWC3.setColor2(new java.awt.Color(69, 161, 137));
        panel_Round_Degradado_JWC3.setEnabled(false);
        panel_Round_Degradado_JWC3.setInferior_izquierdo(50);

        btnCerrar.setBackground(new java.awt.Color(51, 51, 51));
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("CERRAR");
        btnCerrar.setArco_esquina(20);
        btnCerrar.setColor_Hover(new java.awt.Color(93, 93, 93));
        btnCerrar.setColor_Normal(new java.awt.Color(51, 51, 51));
        btnCerrar.setFocusPainted(false);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_Round_Degradado_JWC3Layout = new javax.swing.GroupLayout(panel_Round_Degradado_JWC3);
        panel_Round_Degradado_JWC3.setLayout(panel_Round_Degradado_JWC3Layout);
        panel_Round_Degradado_JWC3Layout.setHorizontalGroup(
            panel_Round_Degradado_JWC3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Round_Degradado_JWC3Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        panel_Round_Degradado_JWC3Layout.setVerticalGroup(
            panel_Round_Degradado_JWC3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_Degradado_JWC3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_Round_JWC1Layout = new javax.swing.GroupLayout(panel_Round_JWC1);
        panel_Round_JWC1.setLayout(panel_Round_JWC1Layout);
        panel_Round_JWC1Layout.setHorizontalGroup(
            panel_Round_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Round_JWC1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_Round_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_Round_Degradado_JWC1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addComponent(panel_Round_Degradado_JWC3, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Round_Degradado_JWC2, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );
        panel_Round_JWC1Layout.setVerticalGroup(
            panel_Round_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_JWC1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_Round_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_Round_Degradado_JWC2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_Round_JWC1Layout.createSequentialGroup()
                        .addComponent(panel_Round_Degradado_JWC1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_Round_Degradado_JWC3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panel_Round_JWC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnLimpiarTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarTipoDocumentoActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarTipoDocumentoActionPerformed

    private void btnAgregarTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTipoDocumentoActionPerformed
        try {
            if (txtNombreTipoDocumento.getText().isBlank()) {
                JOptionPane.showMessageDialog(null, "Por favor, ingresa el nombre del tipo de documento");
            } else {
                tdoc.insertarTipoDocumento(txtNombreTipoDocumento);
                limpiar();
                JOptionPane.showMessageDialog(null, "Tipo de documento agregado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "No se pudo agregar el tipo de documento --> " + e.getMessage());
        }
    }//GEN-LAST:event_btnAgregarTipoDocumentoActionPerformed

    private void btnEditarTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarTipoDocumentoActionPerformed
        try {
            if (tabla_TipoDocumento.getSelectedRowCount() <= 0) {
                JOptionPane.showMessageDialog(rootPane, "Seleccione un tipo de documento de la lista");
            } else {
                if (txtNombreTipoDocumento.getText().isBlank()) {
                    JOptionPane.showMessageDialog(null, "Por favor, ingrese el nombre del tipo de documento");
                } else {
                    if (JOptionPane.showConfirmDialog(rootPane, "¿Modificar datos?", "Confirmar cambios", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                        tdoc.editarTipoDocumento(tabla_TipoDocumento.getValueAt(tabla_TipoDocumento.getSelectedRow(), 0).toString(), txtNombreTipoDocumento);
                        limpiar();
                        JOptionPane.showMessageDialog(null, "Datos modificados");
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "No se pudo actualizar los datos del tipo de documento. Intente nuevamente");
        }
    }//GEN-LAST:event_btnEditarTipoDocumentoActionPerformed

    private void btnEliminarTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTipoDocumentoActionPerformed
        try {
            if (tabla_TipoDocumento.getSelectedRowCount() <= 0) {
                JOptionPane.showMessageDialog(null, "Seleccione untipo de documento de la lista para eliminar");
            } else {
                if (JOptionPane.showConfirmDialog(rootPane, "¿Eliminar tipo de documento?", "Confirmar cambios", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    if (!tdoc.existenRegistrosReferenciadosTipoDoc(Integer.parseInt(tabla_TipoDocumento.getValueAt(tabla_TipoDocumento.getSelectedRow(), 0).toString()))) {
                        tdoc.eliminarTipoDocumento(tabla_TipoDocumento.getValueAt(tabla_TipoDocumento.getSelectedRow(), 0).toString());
                        limpiar();
                        JOptionPane.showMessageDialog(null, "Tipo de documento eliminado");
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "No se puede eliminar. Este tipo de documento ya se encuentra referenciado en "
                                + "otras tablas");
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "No se pudo eliminar el tipo de documento. Intente nuevamente");
        }
    }//GEN-LAST:event_btnEliminarTipoDocumentoActionPerformed

    private void txtNombreTipoDocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreTipoDocumentoKeyTyped
        if (txtNombreTipoDocumento.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreTipoDocumentoKeyTyped

    private void txtBuscarPorTipoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarPorTipoKeyReleased
        try {
            tdoc.filtrarTipoDocumento(tabla_TipoDocumento, txtBuscarPorTipo);
        } catch (Exception ex) {
            Logger.getLogger(jdMantenimientoTipoDocumento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtBuscarPorTipoKeyReleased

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            tdoc.listarTablaTipoDocumento(tabla_TipoDocumento);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al intetar listar: " + e.getMessage());
        }
    }//GEN-LAST:event_formWindowActivated

    private void tabla_TipoDocumentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_TipoDocumentoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabla_TipoDocumentoMouseClicked

    private void tabla_TipoDocumentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabla_TipoDocumentoKeyReleased
        int seleccionFila = tabla_TipoDocumento.getSelectedRow();
        if (seleccionFila > -1) {
            Object nombre = tabla_TipoDocumento.getValueAt(seleccionFila, 1);
            txtNombreTipoDocumento.setText(nombre.toString());
        }
    }//GEN-LAST:event_tabla_TipoDocumentoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnAgregarTipoDocumento;
    private swing.Btn_Round_JWC btnCerrar;
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnEditarTipoDocumento;
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnEliminarTipoDocumento;
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnLimpiarTipoDocumento;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private panel_degradado_jwc.Panel_Round_Degradado_JWC panel_Round_Degradado_JWC1;
    private panel_degradado_jwc.Panel_Round_Degradado_JWC panel_Round_Degradado_JWC2;
    private panel_degradado_jwc.Panel_Round_Degradado_JWC panel_Round_Degradado_JWC3;
    private swing.Panel_Round_JWC panel_Round_JWC1;
    private swing.Panel_Round_JWC panel_Round_JWC2;
    private javax.swing.JTable tabla_TipoDocumento;
    private javax.swing.JTextField txtBuscarPorTipo;
    private javax.swing.JTextField txtNombreTipoDocumento;
    // End of variables declaration//GEN-END:variables
}
