/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Presentacion;

import Negocio.HorarioTrabajo;
import Negocio.TipoContrato;
import java.awt.Color;
import java.sql.*;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jefer
 */
public class jdMantenimientoHorarioTrabajo extends javax.swing.JDialog {

    TipoContrato objTC = new TipoContrato();
    HorarioTrabajo objHT = new HorarioTrabajo();

    public jdMantenimientoHorarioTrabajo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        spnrHoraEntrada.setModel(new SpinnerNumberModel(0, 0, 24, 1));
        spnrHoraSalida.setModel(new SpinnerNumberModel(0, 0, 24, 1));
        setBackground(new Color(0, 0, 0, 0));
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Round_JWC1 = new swing.Panel_Round_JWC();
        panel_Round_Degradado_JWC1 = new panel_degradado_jwc.Panel_Round_Degradado_JWC();
        jLabel4 = new javax.swing.JLabel();
        panel_Round_JWC2 = new swing.Panel_Round_JWC();
        btnAgregarHorarioTrabajo = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        btnEditarHorarioTrabajo = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        btnEliminarHorarioTrabajo = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        btnLimpiar = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cboTurno = new javax.swing.JComboBox<>();
        cboHorario = new javax.swing.JComboBox<>();
        spnrHoraSalida = new javax.swing.JSpinner();
        spnrHoraEntrada = new javax.swing.JSpinner();
        panel_Round_Degradado_JWC3 = new panel_degradado_jwc.Panel_Round_Degradado_JWC();
        btnCerrar = new swing.Btn_Round_JWC();
        panel_Round_Degradado_JWC2 = new panel_degradado_jwc.Panel_Round_Degradado_JWC();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHorarioTrabajo = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        txtBuscarPorTipo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panel_Round_JWC1.setBackground(new java.awt.Color(255, 255, 255));
        panel_Round_JWC1.setEsqInferiorDerecha(50);
        panel_Round_JWC1.setEsqInferiorIzquierda(50);
        panel_Round_JWC1.setEsqSuperiorDerecha(50);
        panel_Round_JWC1.setEsqSuperiorIzquierda(50);
        panel_Round_JWC1.setPreferredSize(new java.awt.Dimension(1055, 590));

        panel_Round_Degradado_JWC1.setColor1(new java.awt.Color(69, 161, 137));
        panel_Round_Degradado_JWC1.setColor2(new java.awt.Color(69, 161, 137));
        panel_Round_Degradado_JWC1.setEnabled(false);
        panel_Round_Degradado_JWC1.setSuperior_izquierdo(50);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TURNO:");

        panel_Round_JWC2.setBackground(new java.awt.Color(51, 51, 51));
        panel_Round_JWC2.setEsqInferiorDerecha(50);
        panel_Round_JWC2.setEsqInferiorIzquierda(50);
        panel_Round_JWC2.setEsqSuperiorDerecha(50);
        panel_Round_JWC2.setEsqSuperiorIzquierda(50);

        btnAgregarHorarioTrabajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/anadir (2).png"))); // NOI18N
        btnAgregarHorarioTrabajo.setText("");
        btnAgregarHorarioTrabajo.setBackground_Hover_1(new java.awt.Color(255, 255, 255));
        btnAgregarHorarioTrabajo.setBackground_Hover_2(new java.awt.Color(255, 255, 255));
        btnAgregarHorarioTrabajo.setBackground_No_Hover_1(new java.awt.Color(221, 239, 168));
        btnAgregarHorarioTrabajo.setBackground_No_Hover_2(new java.awt.Color(146, 161, 214));
        btnAgregarHorarioTrabajo.setEsquina_inferior_derecho(50);
        btnAgregarHorarioTrabajo.setEsquina_inferior_izquierdo(50);
        btnAgregarHorarioTrabajo.setEsquina_superior_derecho(50);
        btnAgregarHorarioTrabajo.setEsquina_superior_izquierdo(50);
        btnAgregarHorarioTrabajo.setFocusPainted(false);
        btnAgregarHorarioTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarHorarioTrabajoActionPerformed(evt);
            }
        });

        btnEditarHorarioTrabajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/editar (1).png"))); // NOI18N
        btnEditarHorarioTrabajo.setText("");
        btnEditarHorarioTrabajo.setBackground_Hover_1(new java.awt.Color(255, 255, 255));
        btnEditarHorarioTrabajo.setBackground_Hover_2(new java.awt.Color(255, 255, 255));
        btnEditarHorarioTrabajo.setBackground_No_Hover_1(new java.awt.Color(221, 239, 168));
        btnEditarHorarioTrabajo.setBackground_No_Hover_2(new java.awt.Color(146, 161, 214));
        btnEditarHorarioTrabajo.setEsquina_inferior_derecho(50);
        btnEditarHorarioTrabajo.setEsquina_inferior_izquierdo(50);
        btnEditarHorarioTrabajo.setEsquina_superior_derecho(50);
        btnEditarHorarioTrabajo.setEsquina_superior_izquierdo(50);
        btnEditarHorarioTrabajo.setFocusPainted(false);
        btnEditarHorarioTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarHorarioTrabajoActionPerformed(evt);
            }
        });

        btnEliminarHorarioTrabajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton-eliminar (1).png"))); // NOI18N
        btnEliminarHorarioTrabajo.setText("");
        btnEliminarHorarioTrabajo.setBackground_Hover_1(new java.awt.Color(255, 153, 153));
        btnEliminarHorarioTrabajo.setBackground_Hover_2(new java.awt.Color(255, 153, 153));
        btnEliminarHorarioTrabajo.setBackground_No_Hover_1(new java.awt.Color(245, 226, 226));
        btnEliminarHorarioTrabajo.setBackground_No_Hover_2(new java.awt.Color(245, 226, 226));
        btnEliminarHorarioTrabajo.setEsquina_inferior_derecho(50);
        btnEliminarHorarioTrabajo.setEsquina_inferior_izquierdo(50);
        btnEliminarHorarioTrabajo.setEsquina_superior_derecho(50);
        btnEliminarHorarioTrabajo.setEsquina_superior_izquierdo(50);
        btnEliminarHorarioTrabajo.setFocusPainted(false);
        btnEliminarHorarioTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarHorarioTrabajoActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escoba (1).png"))); // NOI18N
        btnLimpiar.setText("");
        btnLimpiar.setBackground_Hover_1(new java.awt.Color(255, 255, 255));
        btnLimpiar.setBackground_Hover_2(new java.awt.Color(255, 255, 255));
        btnLimpiar.setBackground_No_Hover_1(new java.awt.Color(221, 239, 168));
        btnLimpiar.setBackground_No_Hover_2(new java.awt.Color(146, 161, 214));
        btnLimpiar.setEsquina_inferior_derecho(50);
        btnLimpiar.setEsquina_inferior_izquierdo(50);
        btnLimpiar.setEsquina_superior_derecho(50);
        btnLimpiar.setEsquina_superior_izquierdo(50);
        btnLimpiar.setFocusPainted(false);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_Round_JWC2Layout = new javax.swing.GroupLayout(panel_Round_JWC2);
        panel_Round_JWC2.setLayout(panel_Round_JWC2Layout);
        panel_Round_JWC2Layout.setHorizontalGroup(
            panel_Round_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_JWC2Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(btnAgregarHorarioTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditarHorarioTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarHorarioTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        panel_Round_JWC2Layout.setVerticalGroup(
            panel_Round_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_JWC2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_Round_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarHorarioTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarHorarioTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarHorarioTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MANTENIMIENTO "); // NOI18N

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DEL HORARIO DE TRABAJO"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("DE (24h):");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("<html>HORARIO:</html>");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("A:");

        cboTurno.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        cboTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------------------", "Mañana", "Tarde", "Noche" }));

        cboHorario.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        cboHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------------------" }));

        spnrHoraSalida.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        spnrHoraSalida.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                spnrHoraSalidaPropertyChange(evt);
            }
        });

        spnrHoraEntrada.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        spnrHoraEntrada.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                spnrHoraEntradaPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout panel_Round_Degradado_JWC1Layout = new javax.swing.GroupLayout(panel_Round_Degradado_JWC1);
        panel_Round_Degradado_JWC1.setLayout(panel_Round_Degradado_JWC1Layout);
        panel_Round_Degradado_JWC1Layout.setHorizontalGroup(
            panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel5)))
                .addGap(34, 34, 34))
            .addGroup(panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(panel_Round_JWC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(cboTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spnrHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnrHoraEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panel_Round_Degradado_JWC1Layout.setVerticalGroup(
            panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(27, 27, 27)
                .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(spnrHoraEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(spnrHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(panel_Round_JWC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        panel_Round_Degradado_JWC3.setColor1(new java.awt.Color(69, 161, 137));
        panel_Round_Degradado_JWC3.setColor2(new java.awt.Color(69, 161, 137));
        panel_Round_Degradado_JWC3.setEnabled(false);
        panel_Round_Degradado_JWC3.setInferior_izquierdo(50);

        btnCerrar.setBackground(new java.awt.Color(51, 51, 51));
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("CERRAR");
        btnCerrar.setArco_esquina(20);
        btnCerrar.setColor_Hover(new java.awt.Color(93, 93, 93));
        btnCerrar.setColor_Normal(new java.awt.Color(51, 51, 51));
        btnCerrar.setFocusPainted(false);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_Round_Degradado_JWC3Layout = new javax.swing.GroupLayout(panel_Round_Degradado_JWC3);
        panel_Round_Degradado_JWC3.setLayout(panel_Round_Degradado_JWC3Layout);
        panel_Round_Degradado_JWC3Layout.setHorizontalGroup(
            panel_Round_Degradado_JWC3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Round_Degradado_JWC3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        panel_Round_Degradado_JWC3Layout.setVerticalGroup(
            panel_Round_Degradado_JWC3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_Degradado_JWC3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panel_Round_Degradado_JWC2.setColor1(new java.awt.Color(69, 161, 137));
        panel_Round_Degradado_JWC2.setColor2(new java.awt.Color(69, 161, 137));
        panel_Round_Degradado_JWC2.setEnabled(false);
        panel_Round_Degradado_JWC2.setInferior_derecho(50);
        panel_Round_Degradado_JWC2.setSuperior_derecho(50);

        tblHorarioTrabajo.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        tblHorarioTrabajo.setForeground(new java.awt.Color(0, 0, 0));
        tblHorarioTrabajo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblHorarioTrabajo.setGridColor(new java.awt.Color(0, 0, 0));
        tblHorarioTrabajo.setSelectionBackground(new java.awt.Color(153, 153, 153));
        tblHorarioTrabajo.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblHorarioTrabajo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHorarioTrabajoMouseClicked(evt);
            }
        });
        tblHorarioTrabajo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblHorarioTrabajoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblHorarioTrabajo);

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Buscar por turno:");

        txtBuscarPorTipo.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        txtBuscarPorTipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarPorTipoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panel_Round_Degradado_JWC2Layout = new javax.swing.GroupLayout(panel_Round_Degradado_JWC2);
        panel_Round_Degradado_JWC2.setLayout(panel_Round_Degradado_JWC2Layout);
        panel_Round_Degradado_JWC2Layout.setHorizontalGroup(
            panel_Round_Degradado_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Round_Degradado_JWC2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(panel_Round_Degradado_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                    .addComponent(txtBuscarPorTipo))
                .addContainerGap())
        );
        panel_Round_Degradado_JWC2Layout.setVerticalGroup(
            panel_Round_Degradado_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_Degradado_JWC2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarPorTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_Round_JWC1Layout = new javax.swing.GroupLayout(panel_Round_JWC1);
        panel_Round_JWC1.setLayout(panel_Round_JWC1Layout);
        panel_Round_JWC1Layout.setHorizontalGroup(
            panel_Round_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Round_JWC1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_Round_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_Round_Degradado_JWC3, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addComponent(panel_Round_Degradado_JWC1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Round_Degradado_JWC2, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_Round_JWC1Layout.setVerticalGroup(
            panel_Round_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_JWC1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_Round_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panel_Round_Degradado_JWC2, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                    .addGroup(panel_Round_JWC1Layout.createSequentialGroup()
                        .addComponent(panel_Round_Degradado_JWC1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_Round_Degradado_JWC3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 936, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_Round_JWC1, javax.swing.GroupLayout.PREFERRED_SIZE, 924, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_Round_JWC1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarHorarioTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarHorarioTrabajoActionPerformed
        try {
            if (cboTurno.getSelectedIndex() == 0 || cboHorario.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Por favor, seleccione un turno o un horario válido");
            } else {
                agregar(cboTurno, spnrHoraEntrada, spnrHoraSalida, cboHorario);
                limpiar();
                JOptionPane.showMessageDialog(rootPane, "Horario de trabajo agregado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "No se pudo agregar el horario de trabajo --> " + e.getMessage());
        }
    }//GEN-LAST:event_btnAgregarHorarioTrabajoActionPerformed

    private void agregar(JComboBox cboturno, JSpinner horaentrada, JSpinner horasalida, JComboBox horario) throws Exception {
        //Convertir los números de los jspinner a tipo Time:
        int horaentr = Integer.parseInt(horaentrada.getValue().toString());
        int horasal = Integer.parseInt(horasalida.getValue().toString());
        String formatoHora = "%02d:00:00";
        String horaStr1 = String.format(formatoHora, horaentr);
        String horaStr2 = String.format(formatoHora, horasal);
        Time hora1 = Time.valueOf(horaStr1);
        Time hora2 = Time.valueOf(horaStr2);

        String turno = cboturno.getSelectedItem().toString();
        int idtipocont = objTC.obtenerIdTipoContrato(horario.getSelectedItem().toString());

        objHT.registrarHorarioTrabajo(hora1, hora2, idtipocont, turno);
    }

    private void btnEditarHorarioTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarHorarioTrabajoActionPerformed
        try {
            if (tblHorarioTrabajo.getSelectedRowCount() <= 0) {
                JOptionPane.showMessageDialog(rootPane, "Seleccione un horario de trabajo de la lista");
            } else {
                if (cboTurno.getSelectedIndex() == 0 || cboHorario.getSelectedIndex() == 0) {
                    JOptionPane.showMessageDialog(rootPane, "Por favor, seleccione un turno o un horario válido");
                } else {
                    if (JOptionPane.showConfirmDialog(rootPane, "¿Modificar datos?", "Confirmar cambios", JOptionPane.YES_NO_OPTION)
                            == JOptionPane.YES_OPTION) {
                        modificar(cboTurno, spnrHoraEntrada, spnrHoraSalida, cboHorario,
                                tblHorarioTrabajo.getValueAt(tblHorarioTrabajo.getSelectedRow(), 0).toString());
                        limpiar();
                        JOptionPane.showMessageDialog(rootPane, "Datos modificados");
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "No se pudo modificar el horario de trabajo --> " + e.getMessage());
        }
    }//GEN-LAST:event_btnEditarHorarioTrabajoActionPerformed

    private void modificar(JComboBox cboturno, JSpinner horaentrada, JSpinner horasalida, JComboBox horario, String codigo) throws Exception {
        //Convertir los números de los jspinner a tipo Time:
        int horaentr = Integer.parseInt(horaentrada.getValue().toString());
        int horasal = Integer.parseInt(horasalida.getValue().toString());
        String formatoHora = "%02d:00:00";
        String horaStr1 = String.format(formatoHora, horaentr);
        String horaStr2 = String.format(formatoHora, horasal);
        Time hora1 = Time.valueOf(horaStr1);
        Time hora2 = Time.valueOf(horaStr2);

        String turno = cboturno.getSelectedItem().toString();
        int idtipocont = objTC.obtenerIdTipoContrato(horario.getSelectedItem().toString());
        int idhorariotrabajo = Integer.parseInt(codigo);

        objHT.modificarHorarioTrabajo(hora1, hora2, idtipocont, turno, idhorariotrabajo);
    }

    private void btnEliminarHorarioTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarHorarioTrabajoActionPerformed
        try {
            if (tblHorarioTrabajo.getSelectedRowCount() <= 0) {
                JOptionPane.showMessageDialog(rootPane, "Seleccione un horario de trabajo de la lista para eliminar");
            } else {
                if (JOptionPane.showConfirmDialog(rootPane, "¿Eliminar horario de trabajo?", "Confirmar cambios", JOptionPane.YES_NO_OPTION)
                        == JOptionPane.YES_OPTION) {
                    if (!objHT.existenRegistrosReferenciados(Integer.parseInt(tblHorarioTrabajo.getValueAt(tblHorarioTrabajo.getSelectedRow(), 0).toString()))) {
                        eliminar(tblHorarioTrabajo.getValueAt(tblHorarioTrabajo.getSelectedRow(), 0).toString());
                        limpiar();
                        JOptionPane.showMessageDialog(rootPane, "Horario de trabajo eliminado");
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "No se puede eliminar. Este horario de trabajo ya se encuentra referenciado "
                                + "en otras tablas");
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "No se pudo agregar el horario de trabajo --> " + e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarHorarioTrabajoActionPerformed

    private void eliminar(String codigo) throws Exception {
        int id = Integer.parseInt(codigo);
        objHT.eliminarHorarioTrabajo(id);
    }

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        try {
            limpiar();
        } catch (Exception ex) {
            Logger.getLogger(jdMantenimientoHorarioTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void txtBuscarPorTipoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarPorTipoKeyReleased
        try {
            filtrarTurno(txtBuscarPorTipo);
        } catch (Exception ex) {
            Logger.getLogger(jdMantenimientoHorarioTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtBuscarPorTipoKeyReleased

    private void spnrHoraEntradaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_spnrHoraEntradaPropertyChange

    }//GEN-LAST:event_spnrHoraEntradaPropertyChange

    private void spnrHoraSalidaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_spnrHoraSalidaPropertyChange

    }//GEN-LAST:event_spnrHoraSalidaPropertyChange

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            cargarCboHorario();
            listarTodo();
        } catch (Exception ex) {
            Logger.getLogger(jdMantenimientoHorarioTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void tblHorarioTrabajoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHorarioTrabajoMouseClicked
        if (tblHorarioTrabajo.getSelectedRowCount() > 0) {

            Time hora1 = Time.valueOf(tblHorarioTrabajo.getValueAt(tblHorarioTrabajo.getSelectedRow(), 1).toString());
            Calendar calendar1 = Calendar.getInstance();
            calendar1.setTime(hora1);
            int hour1 = calendar1.get(Calendar.HOUR_OF_DAY);
            spnrHoraEntrada.setValue(hour1);

            Time hora2 = Time.valueOf(tblHorarioTrabajo.getValueAt(tblHorarioTrabajo.getSelectedRow(), 2).toString());
            Calendar calendar2 = Calendar.getInstance();
            calendar2.setTime(hora2);
            int hour2 = calendar2.get(Calendar.HOUR_OF_DAY);
            spnrHoraSalida.setValue(hour2);

            cboTurno.setSelectedItem(tblHorarioTrabajo.getValueAt(tblHorarioTrabajo.getSelectedRow(), 3));
            cboHorario.setSelectedItem(tblHorarioTrabajo.getValueAt(tblHorarioTrabajo.getSelectedRow(), 4));
        }
    }//GEN-LAST:event_tblHorarioTrabajoMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
    }//GEN-LAST:event_formWindowActivated

    private void tblHorarioTrabajoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblHorarioTrabajoKeyReleased
        if (tblHorarioTrabajo.getSelectedRowCount() > 0) {

            Time hora1 = Time.valueOf(tblHorarioTrabajo.getValueAt(tblHorarioTrabajo.getSelectedRow(), 1).toString());
            Calendar calendar1 = Calendar.getInstance();
            calendar1.setTime(hora1);
            int hour1 = calendar1.get(Calendar.HOUR_OF_DAY);
            spnrHoraEntrada.setValue(hour1);

            Time hora2 = Time.valueOf(tblHorarioTrabajo.getValueAt(tblHorarioTrabajo.getSelectedRow(), 2).toString());
            Calendar calendar2 = Calendar.getInstance();
            calendar2.setTime(hora2);
            int hour2 = calendar2.get(Calendar.HOUR_OF_DAY);
            spnrHoraSalida.setValue(hour2);

            cboTurno.setSelectedItem(tblHorarioTrabajo.getValueAt(tblHorarioTrabajo.getSelectedRow(), 3));
            cboHorario.setSelectedItem(tblHorarioTrabajo.getValueAt(tblHorarioTrabajo.getSelectedRow(), 4));
        }
    }//GEN-LAST:event_tblHorarioTrabajoKeyReleased

    private void cargarCboHorario() throws Exception {
        ResultSet rs = objTC.cargarTipoContratos();
        cboHorario.removeAllItems();
        cboHorario.addItem("---------------------");
        while (rs.next()) {
            cboHorario.addItem(rs.getString("nombre"));
        }
    }

    private void filtrarTurno(JTextField turno) throws Exception {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Código");
        modelo.addColumn("Hora de entrada");
        modelo.addColumn("Hora de salida");
        modelo.addColumn("Turno");
        modelo.addColumn("Tipo de horario");

        ResultSet rs = objHT.filtrarTurnoHorarioTrabajo(turno.getText());

        Object datos[] = new Object[5];

        while (rs.next()) {
            datos[0] = rs.getInt("id");
            datos[1] = rs.getTime("horaentrada");
            datos[2] = rs.getTime("horasalida");
            datos[3] = rs.getString("turno");
            datos[4] = rs.getString("tipohorario");
            modelo.addRow(datos);
        }
        tblHorarioTrabajo.setModel(modelo);
    }

    private void listarTodo() throws Exception {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Código");
        modelo.addColumn("Hora de entrada");
        modelo.addColumn("Hora de salida");
        modelo.addColumn("Turno");
        modelo.addColumn("Tipo de horario");

        ResultSet rs = objHT.listarTodo();

        Object datos[] = new Object[5];

        while (rs.next()) {
            datos[0] = rs.getInt("id");
            datos[1] = rs.getTime("horaentrada");
            datos[2] = rs.getTime("horasalida");
            datos[3] = rs.getString("turno");
            datos[4] = rs.getString("tipohorario");
            modelo.addRow(datos);
        }
        tblHorarioTrabajo.setModel(modelo);
    }

    private void limpiar() throws Exception {
        cboHorario.setSelectedIndex(0);
        cboTurno.setSelectedIndex(0);
        spnrHoraEntrada.setValue(0);
        spnrHoraSalida.setValue(0);
        listarTodo();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnAgregarHorarioTrabajo;
    private swing.Btn_Round_JWC btnCerrar;
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnEditarHorarioTrabajo;
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnEliminarHorarioTrabajo;
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnLimpiar;
    private javax.swing.JComboBox<String> cboHorario;
    private javax.swing.JComboBox<String> cboTurno;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private panel_degradado_jwc.Panel_Round_Degradado_JWC panel_Round_Degradado_JWC1;
    private panel_degradado_jwc.Panel_Round_Degradado_JWC panel_Round_Degradado_JWC2;
    private panel_degradado_jwc.Panel_Round_Degradado_JWC panel_Round_Degradado_JWC3;
    private swing.Panel_Round_JWC panel_Round_JWC1;
    private swing.Panel_Round_JWC panel_Round_JWC2;
    private javax.swing.JSpinner spnrHoraEntrada;
    private javax.swing.JSpinner spnrHoraSalida;
    private javax.swing.JTable tblHorarioTrabajo;
    private javax.swing.JTextField txtBuscarPorTipo;
    // End of variables declaration//GEN-END:variables
}
