package Presentacion;

import Negocio.TipoPermiso;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @GRUPO 4
 */
public class jdMantenimientoTipoPermiso extends javax.swing.JDialog {

    TipoPermiso perm = new TipoPermiso();

    public jdMantenimientoTipoPermiso(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);

        try {
            perm.listarTablaTipoPermiso(tabla_TipoDocumento);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al intetar listar: " + e.getMessage());
        }

        tabla_TipoDocumento.getSelectionModel().addListSelectionListener(e -> {
            if (e.getValueIsAdjusting()) {
                int seleccionFila = tabla_TipoDocumento.getSelectedRow();
                if (seleccionFila > -1) {
                    Object nombre = tabla_TipoDocumento.getValueAt(seleccionFila, 1);
                    Object descripcion = tabla_TipoDocumento.getValueAt(seleccionFila, 2);
                    Object permiso = tabla_TipoDocumento.getValueAt(seleccionFila, 3);
                    txtNombreTipoPermiso.setText(nombre.toString());
                    txtDescripcion.setText(descripcion.toString());
                    txtDiasPermiso.setText(permiso.toString());
                }
            }
        });
    }

    public void limpiar() {
        try {
            perm.listarTablaTipoPermiso(tabla_TipoDocumento);
            txtNombreTipoPermiso.setText("");
            txtDescripcion.setText("");
            txtDiasPermiso.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudo limpiar el contenido: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Round_JWC1 = new swing.Panel_Round_JWC();
        panel_Round_Degradado_JWC1 = new panel_degradado_jwc.Panel_Round_Degradado_JWC();
        jLabel4 = new javax.swing.JLabel();
        txtNombreTipoPermiso = new javax.swing.JTextField();
        panel_Round_JWC2 = new swing.Panel_Round_JWC();
        btnAgregarTipoPermiso = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        btnEditarTipoPermiso = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        btnEliminarTipoPermiso = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        btnLimpiarTipoPermiso = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        txtDiasPermiso = new javax.swing.JTextField();
        panel_Round_Degradado_JWC2 = new panel_degradado_jwc.Panel_Round_Degradado_JWC();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_TipoDocumento = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtBuscarPorTipo = new javax.swing.JTextField();
        panel_Round_Degradado_JWC4 = new panel_degradado_jwc.Panel_Round_Degradado_JWC();
        btnCerrar = new swing.Btn_Round_JWC();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_Round_JWC1.setBackground(new java.awt.Color(255, 255, 255));
        panel_Round_JWC1.setEsqInferiorDerecha(50);
        panel_Round_JWC1.setEsqInferiorIzquierda(50);
        panel_Round_JWC1.setEsqSuperiorDerecha(50);
        panel_Round_JWC1.setEsqSuperiorIzquierda(50);

        panel_Round_Degradado_JWC1.setColor1(new java.awt.Color(69, 161, 137));
        panel_Round_Degradado_JWC1.setColor2(new java.awt.Color(69, 161, 137));
        panel_Round_Degradado_JWC1.setEnabled(false);
        panel_Round_Degradado_JWC1.setSuperior_izquierdo(50);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TIPO PERMISO:");

        txtNombreTipoPermiso.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        txtNombreTipoPermiso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreTipoPermisoKeyTyped(evt);
            }
        });

        panel_Round_JWC2.setBackground(new java.awt.Color(51, 51, 51));
        panel_Round_JWC2.setEsqInferiorDerecha(50);
        panel_Round_JWC2.setEsqInferiorIzquierda(50);
        panel_Round_JWC2.setEsqSuperiorDerecha(50);
        panel_Round_JWC2.setEsqSuperiorIzquierda(50);

        btnAgregarTipoPermiso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/anadir (2).png"))); // NOI18N
        btnAgregarTipoPermiso.setText("");
        btnAgregarTipoPermiso.setBackground_Hover_1(new java.awt.Color(255, 255, 255));
        btnAgregarTipoPermiso.setBackground_Hover_2(new java.awt.Color(255, 255, 255));
        btnAgregarTipoPermiso.setBackground_No_Hover_1(new java.awt.Color(221, 239, 168));
        btnAgregarTipoPermiso.setBackground_No_Hover_2(new java.awt.Color(146, 161, 214));
        btnAgregarTipoPermiso.setEsquina_inferior_derecho(50);
        btnAgregarTipoPermiso.setEsquina_inferior_izquierdo(50);
        btnAgregarTipoPermiso.setEsquina_superior_derecho(50);
        btnAgregarTipoPermiso.setEsquina_superior_izquierdo(50);
        btnAgregarTipoPermiso.setFocusPainted(false);
        btnAgregarTipoPermiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTipoPermisoActionPerformed(evt);
            }
        });

        btnEditarTipoPermiso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/editar (1).png"))); // NOI18N
        btnEditarTipoPermiso.setText("");
        btnEditarTipoPermiso.setBackground_Hover_1(new java.awt.Color(255, 255, 255));
        btnEditarTipoPermiso.setBackground_Hover_2(new java.awt.Color(255, 255, 255));
        btnEditarTipoPermiso.setBackground_No_Hover_1(new java.awt.Color(221, 239, 168));
        btnEditarTipoPermiso.setBackground_No_Hover_2(new java.awt.Color(146, 161, 214));
        btnEditarTipoPermiso.setEsquina_inferior_derecho(50);
        btnEditarTipoPermiso.setEsquina_inferior_izquierdo(50);
        btnEditarTipoPermiso.setEsquina_superior_derecho(50);
        btnEditarTipoPermiso.setEsquina_superior_izquierdo(50);
        btnEditarTipoPermiso.setFocusPainted(false);
        btnEditarTipoPermiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarTipoPermisoActionPerformed(evt);
            }
        });

        btnEliminarTipoPermiso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton-eliminar (1).png"))); // NOI18N
        btnEliminarTipoPermiso.setText("");
        btnEliminarTipoPermiso.setBackground_Hover_1(new java.awt.Color(255, 153, 153));
        btnEliminarTipoPermiso.setBackground_Hover_2(new java.awt.Color(255, 153, 153));
        btnEliminarTipoPermiso.setBackground_No_Hover_1(new java.awt.Color(245, 226, 226));
        btnEliminarTipoPermiso.setBackground_No_Hover_2(new java.awt.Color(245, 226, 226));
        btnEliminarTipoPermiso.setEsquina_inferior_derecho(50);
        btnEliminarTipoPermiso.setEsquina_inferior_izquierdo(50);
        btnEliminarTipoPermiso.setEsquina_superior_derecho(50);
        btnEliminarTipoPermiso.setEsquina_superior_izquierdo(50);
        btnEliminarTipoPermiso.setFocusPainted(false);
        btnEliminarTipoPermiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTipoPermisoActionPerformed(evt);
            }
        });

        btnLimpiarTipoPermiso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escoba (1).png"))); // NOI18N
        btnLimpiarTipoPermiso.setText("");
        btnLimpiarTipoPermiso.setBackground_Hover_1(new java.awt.Color(255, 255, 255));
        btnLimpiarTipoPermiso.setBackground_Hover_2(new java.awt.Color(255, 255, 255));
        btnLimpiarTipoPermiso.setBackground_No_Hover_1(new java.awt.Color(221, 239, 168));
        btnLimpiarTipoPermiso.setBackground_No_Hover_2(new java.awt.Color(146, 161, 214));
        btnLimpiarTipoPermiso.setEsquina_inferior_derecho(50);
        btnLimpiarTipoPermiso.setEsquina_inferior_izquierdo(50);
        btnLimpiarTipoPermiso.setEsquina_superior_derecho(50);
        btnLimpiarTipoPermiso.setEsquina_superior_izquierdo(50);
        btnLimpiarTipoPermiso.setFocusPainted(false);
        btnLimpiarTipoPermiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarTipoPermisoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_Round_JWC2Layout = new javax.swing.GroupLayout(panel_Round_JWC2);
        panel_Round_JWC2.setLayout(panel_Round_JWC2Layout);
        panel_Round_JWC2Layout.setHorizontalGroup(
            panel_Round_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_JWC2Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(btnAgregarTipoPermiso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditarTipoPermiso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarTipoPermiso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiarTipoPermiso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        panel_Round_JWC2Layout.setVerticalGroup(
            panel_Round_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_JWC2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_Round_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLimpiarTipoPermiso, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarTipoPermiso, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarTipoPermiso, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarTipoPermiso, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MANTENIMIENTO "); // NOI18N

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DEL TIPO DE PERMISO"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DESCRIPCIÓN:");

        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        txtDescripcion.setRows(5);
        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(txtDescripcion);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DÍAS PERMISO:");

        txtDiasPermiso.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        txtDiasPermiso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiasPermisoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panel_Round_Degradado_JWC1Layout = new javax.swing.GroupLayout(panel_Round_Degradado_JWC1);
        panel_Round_Degradado_JWC1.setLayout(panel_Round_Degradado_JWC1Layout);
        panel_Round_Degradado_JWC1Layout.setHorizontalGroup(
            panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_Round_JWC2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(txtNombreTipoPermiso)
                            .addComponent(txtDiasPermiso))))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5)))
                .addGap(51, 51, 51))
        );
        panel_Round_Degradado_JWC1Layout.setVerticalGroup(
            panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_Degradado_JWC1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(32, 32, 32)
                .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombreTipoPermiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panel_Round_Degradado_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiasPermiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(panel_Round_JWC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        panel_Round_Degradado_JWC2.setColor1(new java.awt.Color(69, 161, 137));
        panel_Round_Degradado_JWC2.setColor2(new java.awt.Color(69, 161, 137));
        panel_Round_Degradado_JWC2.setEnabled(false);
        panel_Round_Degradado_JWC2.setInferior_derecho(50);
        panel_Round_Degradado_JWC2.setSuperior_derecho(50);

        tabla_TipoDocumento.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        tabla_TipoDocumento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabla_TipoDocumento.setGridColor(new java.awt.Color(0, 0, 0));
        tabla_TipoDocumento.setSelectionBackground(new java.awt.Color(153, 153, 153));
        tabla_TipoDocumento.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabla_TipoDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabla_TipoDocumentoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_TipoDocumento);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Buscar por tipo de permiso:");

        txtBuscarPorTipo.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        txtBuscarPorTipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarPorTipoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panel_Round_Degradado_JWC2Layout = new javax.swing.GroupLayout(panel_Round_Degradado_JWC2);
        panel_Round_Degradado_JWC2.setLayout(panel_Round_Degradado_JWC2Layout);
        panel_Round_Degradado_JWC2Layout.setHorizontalGroup(
            panel_Round_Degradado_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_Degradado_JWC2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_Round_Degradado_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBuscarPorTipo))
                .addContainerGap())
        );
        panel_Round_Degradado_JWC2Layout.setVerticalGroup(
            panel_Round_Degradado_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_Degradado_JWC2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarPorTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_Round_Degradado_JWC4.setColor1(new java.awt.Color(69, 161, 137));
        panel_Round_Degradado_JWC4.setColor2(new java.awt.Color(69, 161, 137));
        panel_Round_Degradado_JWC4.setEnabled(false);
        panel_Round_Degradado_JWC4.setInferior_izquierdo(50);

        btnCerrar.setBackground(new java.awt.Color(51, 51, 51));
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("CERRAR");
        btnCerrar.setArco_esquina(20);
        btnCerrar.setColor_Hover(new java.awt.Color(93, 93, 93));
        btnCerrar.setColor_Normal(new java.awt.Color(51, 51, 51));
        btnCerrar.setFocusPainted(false);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_Round_Degradado_JWC4Layout = new javax.swing.GroupLayout(panel_Round_Degradado_JWC4);
        panel_Round_Degradado_JWC4.setLayout(panel_Round_Degradado_JWC4Layout);
        panel_Round_Degradado_JWC4Layout.setHorizontalGroup(
            panel_Round_Degradado_JWC4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_Degradado_JWC4Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_Round_Degradado_JWC4Layout.setVerticalGroup(
            panel_Round_Degradado_JWC4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_Degradado_JWC4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_Round_JWC1Layout = new javax.swing.GroupLayout(panel_Round_JWC1);
        panel_Round_JWC1.setLayout(panel_Round_JWC1Layout);
        panel_Round_JWC1Layout.setHorizontalGroup(
            panel_Round_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_JWC1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_Round_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_Round_Degradado_JWC1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addComponent(panel_Round_Degradado_JWC4, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Round_Degradado_JWC2, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        panel_Round_JWC1Layout.setVerticalGroup(
            panel_Round_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Round_JWC1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_Round_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_Round_Degradado_JWC2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                    .addGroup(panel_Round_JWC1Layout.createSequentialGroup()
                        .addComponent(panel_Round_Degradado_JWC1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_Round_Degradado_JWC4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54))
        );

        getContentPane().add(panel_Round_JWC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarTipoPermisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTipoPermisoActionPerformed
        try {
            if (txtNombreTipoPermiso.getText().isBlank() || txtDescripcion.getText().isBlank() || txtDiasPermiso.getText().isBlank()) {
                JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos");
            } else {
                perm.agregarTipoPermiso(txtNombreTipoPermiso, txtDescripcion, txtDiasPermiso);
                limpiar();
                JOptionPane.showMessageDialog(null, "Tipo de permiso agregado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error al agregar tipo de permiso --> " + e.getMessage());
        }
    }//GEN-LAST:event_btnAgregarTipoPermisoActionPerformed

    private void btnEditarTipoPermisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarTipoPermisoActionPerformed
        try {
            if (tabla_TipoDocumento.getSelectedRow() <= 0) {
                JOptionPane.showMessageDialog(null, "Seleccione un tipo de permiso de la lista");
            } else {
                if (txtNombreTipoPermiso.getText().isBlank() || txtDescripcion.getText().isBlank()
                        || txtDiasPermiso.getText().isBlank()) {
                    JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos");
                } else {
                    if (JOptionPane.showConfirmDialog(rootPane, "¿Modificar datos?", "Confirmar cambios", JOptionPane.YES_NO_OPTION)
                            == JOptionPane.YES_OPTION) {
                        perm.editarTipoPermiso(tabla_TipoDocumento.getValueAt(tabla_TipoDocumento.getSelectedRow(), 0).toString(),
                                txtNombreTipoPermiso, txtDescripcion, txtDiasPermiso);
                        limpiar();
                        JOptionPane.showMessageDialog(null, "Datos modificados");
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error al modificar datos --> " + e.getMessage());
        }
    }//GEN-LAST:event_btnEditarTipoPermisoActionPerformed

    private void btnEliminarTipoPermisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTipoPermisoActionPerformed
        try {
            if (tabla_TipoDocumento.getSelectedRowCount() <= 0) {
                JOptionPane.showMessageDialog(null, "Seleccione un tipo de permiso de la lista para eliminar");
            } else {
                if (JOptionPane.showConfirmDialog(rootPane, "¿Eliminar tipo de permiso?", "Confirmar cambios", JOptionPane.YES_NO_OPTION)
                        == JOptionPane.YES_OPTION) {
                    if (!perm.existenRegistrosReferenciados(Integer.parseInt(tabla_TipoDocumento.getValueAt(tabla_TipoDocumento.getSelectedRow(), 0).toString()))) {
                        perm.eliminarTipoPermiso(tabla_TipoDocumento.getValueAt(tabla_TipoDocumento.getSelectedRow(), 0).toString());
                        limpiar();
                        JOptionPane.showMessageDialog(null, "Tipo de permiso eliminado");
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "No se puede eliminar. Este tipo de permiso ya se encuentra referenciado "
                                + "en otras tablas");
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error al eliminar tipo de permiso --> " + e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarTipoPermisoActionPerformed

    private void btnLimpiarTipoPermisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarTipoPermisoActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarTipoPermisoActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void txtNombreTipoPermisoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreTipoPermisoKeyTyped
        if (txtNombreTipoPermiso.getText().length() >= 50) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreTipoPermisoKeyTyped

    private void txtDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyTyped
        if (txtDescripcion.getText().length() >= 300) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDescripcionKeyTyped

    private void txtDiasPermisoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiasPermisoKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }

        if (txtDiasPermiso.getText().length() >= 2) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDiasPermisoKeyTyped

    private void txtBuscarPorTipoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarPorTipoKeyReleased
        try {
            perm.filtrarTipoPermiso(tabla_TipoDocumento, txtBuscarPorTipo);        // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(jdMantenimientoTipoPermiso.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtBuscarPorTipoKeyReleased

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
    }//GEN-LAST:event_formWindowActivated

    private void tabla_TipoDocumentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabla_TipoDocumentoKeyReleased
        int seleccionFila = tabla_TipoDocumento.getSelectedRow();
        if (seleccionFila > -1) {
            Object nombre = tabla_TipoDocumento.getValueAt(seleccionFila, 1);
            Object descripcion = tabla_TipoDocumento.getValueAt(seleccionFila, 2);
            Object permiso = tabla_TipoDocumento.getValueAt(seleccionFila, 3);
            txtNombreTipoPermiso.setText(nombre.toString());
            txtDescripcion.setText(descripcion.toString());
            txtDiasPermiso.setText(permiso.toString());
        }
    }//GEN-LAST:event_tabla_TipoDocumentoKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            perm.listarTablaTipoPermiso(tabla_TipoDocumento);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al intetar listar: " + e.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnAgregarTipoPermiso;
    private swing.Btn_Round_JWC btnCerrar;
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnEditarTipoPermiso;
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnEliminarTipoPermiso;
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnLimpiarTipoPermiso;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private panel_degradado_jwc.Panel_Round_Degradado_JWC panel_Round_Degradado_JWC1;
    private panel_degradado_jwc.Panel_Round_Degradado_JWC panel_Round_Degradado_JWC2;
    private panel_degradado_jwc.Panel_Round_Degradado_JWC panel_Round_Degradado_JWC4;
    private swing.Panel_Round_JWC panel_Round_JWC1;
    private swing.Panel_Round_JWC panel_Round_JWC2;
    private javax.swing.JTable tabla_TipoDocumento;
    private javax.swing.JTextField txtBuscarPorTipo;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtDiasPermiso;
    private javax.swing.JTextField txtNombreTipoPermiso;
    // End of variables declaration//GEN-END:variables
}
