/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Presentacion;

import Negocio.Beneficio;
import Negocio.BoletaPago;
import Negocio.Descuento;
import java.awt.Frame;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author jefer
 */
public class jdVentanaVerPago extends javax.swing.JDialog {

    private int idboletapago = -1;
    private int codcontrato = -1;

    private double montograti = 0;
    private double montoAF = 0;
    private double montoCTS = 0;
    
    private String descrpbnfsrv = "";
    private double montosrvbnf = 0;

    public void setCodcontrato(int codcontrato) {
        this.codcontrato = codcontrato;
    }

    BoletaPago objBP = new BoletaPago();
    Beneficio objBenf = new Beneficio();
    Descuento objDesc = new Descuento();

    public void setIdboletapago(int idboletapago) {
        this.idboletapago = idboletapago;
    }

    public jdVentanaVerPago(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVolver5 = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblFechaPactada = new javax.swing.JLabel();
        lblFechaPago = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblGratificacion = new javax.swing.JLabel();
        lblAsignacionFamiliar = new javax.swing.JLabel();
        lblCTS = new javax.swing.JLabel();
        lblCorrespondeGrati = new javax.swing.JLabel();
        lblCorrespondeAsignacionFamiliar = new javax.swing.JLabel();
        lblCorrespondeCTS = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalleBeneficio = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblNumInasistencias = new javax.swing.JLabel();
        lblNumTardanzas = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetalleDescuento = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnRegistrarBeneficioServicioAdicional1 = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        btnRegistrarBeneficioServicioAdicional = new btn_efecto01_jwc.btn_efecto_V1_JWC();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("PAGO ACTUAL");

        btnVolver5.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver5.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton-x.png"))); // NOI18N
        btnVolver5.setText("");
        btnVolver5.setBackground_Hover_1(new java.awt.Color(255, 51, 51));
        btnVolver5.setBackground_Hover_2(new java.awt.Color(204, 0, 0));
        btnVolver5.setBackground_No_Hover_1(new java.awt.Color(255, 51, 51));
        btnVolver5.setBackground_No_Hover_2(new java.awt.Color(204, 0, 0));
        btnVolver5.setEsquina_inferior_derecho(20);
        btnVolver5.setEsquina_inferior_izquierdo(20);
        btnVolver5.setEsquina_superior_derecho(20);
        btnVolver5.setEsquina_superior_izquierdo(20);
        btnVolver5.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnVolver5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVolver5.setIconTextGap(8);
        btnVolver5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver5ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(69, 161, 137));

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Información de boleta de pago");

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha pactada:");

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha de pago:");

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Estado:");

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Monto:");

        lblFechaPactada.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblFechaPactada.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaPactada.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lblFechaPago.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblFechaPago.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaPago.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lblEstado.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(255, 255, 255));
        lblEstado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lblMonto.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblMonto.setForeground(new java.awt.Color(255, 255, 255));
        lblMonto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lblFechaPactada, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(lblFechaPactada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(lblMonto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Beneficios de ley");

        lblGratificacion.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        lblGratificacion.setForeground(new java.awt.Color(255, 255, 255));
        lblGratificacion.setText("---------------------");

        lblAsignacionFamiliar.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        lblAsignacionFamiliar.setForeground(new java.awt.Color(255, 255, 255));
        lblAsignacionFamiliar.setText("---------------------");

        lblCTS.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        lblCTS.setForeground(new java.awt.Color(255, 255, 255));
        lblCTS.setText("---------------------");

        lblCorrespondeGrati.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblCorrespondeGrati.setForeground(new java.awt.Color(255, 255, 255));

        lblCorrespondeAsignacionFamiliar.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblCorrespondeAsignacionFamiliar.setForeground(new java.awt.Color(255, 255, 255));

        lblCorrespondeCTS.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblCorrespondeCTS.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(lblAsignacionFamiliar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblGratificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCTS, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblCorrespondeGrati, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(lblCorrespondeCTS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCorrespondeAsignacionFamiliar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGratificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCorrespondeGrati, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblAsignacionFamiliar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCorrespondeCTS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCTS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblCorrespondeAsignacionFamiliar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(69, 161, 137));

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Detalle de beneficios de ley:");

        tblDetalleBeneficio.setBackground(new java.awt.Color(255, 255, 255));
        tblDetalleBeneficio.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        tblDetalleBeneficio.setForeground(new java.awt.Color(0, 0, 0));
        tblDetalleBeneficio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblDetalleBeneficio);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Registro de Asistencia:");

        jLabel10.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("N° tardanzas:");

        jLabel11.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("N° inasistencias:");

        lblNumInasistencias.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblNumInasistencias.setForeground(new java.awt.Color(255, 255, 255));
        lblNumInasistencias.setText("jLabel12");

        lblNumTardanzas.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblNumTardanzas.setForeground(new java.awt.Color(255, 255, 255));
        lblNumTardanzas.setText("jLabel12");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(lblNumInasistencias, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(34, 34, 34)
                            .addComponent(lblNumTardanzas, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNumTardanzas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNumInasistencias))
                .addGap(22, 22, 22))
        );

        jPanel6.setBackground(new java.awt.Color(69, 161, 137));

        tblDetalleDescuento.setBackground(new java.awt.Color(255, 255, 255));
        tblDetalleDescuento.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        tblDetalleDescuento.setForeground(new java.awt.Color(0, 0, 0));
        tblDetalleDescuento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblDetalleDescuento);

        jLabel12.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Detalle de descuentos:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));

        btnRegistrarBeneficioServicioAdicional1.setBackground(new java.awt.Color(51, 102, 0));
        btnRegistrarBeneficioServicioAdicional1.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarBeneficioServicioAdicional1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/btn_continuar.png"))); // NOI18N
        btnRegistrarBeneficioServicioAdicional1.setText("Continuar");
        btnRegistrarBeneficioServicioAdicional1.setBackground_Hover_1(new java.awt.Color(51, 102, 0));
        btnRegistrarBeneficioServicioAdicional1.setBackground_Hover_2(new java.awt.Color(51, 102, 0));
        btnRegistrarBeneficioServicioAdicional1.setBackground_No_Hover_1(new java.awt.Color(51, 102, 0));
        btnRegistrarBeneficioServicioAdicional1.setBackground_No_Hover_2(new java.awt.Color(51, 102, 0));
        btnRegistrarBeneficioServicioAdicional1.setEsquina_inferior_derecho(20);
        btnRegistrarBeneficioServicioAdicional1.setEsquina_inferior_izquierdo(20);
        btnRegistrarBeneficioServicioAdicional1.setEsquina_superior_derecho(20);
        btnRegistrarBeneficioServicioAdicional1.setEsquina_superior_izquierdo(20);
        btnRegistrarBeneficioServicioAdicional1.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btnRegistrarBeneficioServicioAdicional1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnRegistrarBeneficioServicioAdicional1.setIconTextGap(8);
        btnRegistrarBeneficioServicioAdicional1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarBeneficioServicioAdicional1ActionPerformed(evt);
            }
        });
        btnRegistrarBeneficioServicioAdicional1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                btnRegistrarBeneficioServicioAdicional1PropertyChange(evt);
            }
        });

        btnRegistrarBeneficioServicioAdicional.setBackground(new java.awt.Color(255, 204, 0));
        btnRegistrarBeneficioServicioAdicional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/btn_asignar_seguro_salud~1.png"))); // NOI18N
        btnRegistrarBeneficioServicioAdicional.setText("<html>Registrar beneficio o servicio adicional</html>");
        btnRegistrarBeneficioServicioAdicional.setBackground_Hover_1(new java.awt.Color(255, 204, 0));
        btnRegistrarBeneficioServicioAdicional.setBackground_Hover_2(new java.awt.Color(255, 204, 0));
        btnRegistrarBeneficioServicioAdicional.setBackground_No_Hover_1(new java.awt.Color(255, 204, 0));
        btnRegistrarBeneficioServicioAdicional.setBackground_No_Hover_2(new java.awt.Color(255, 204, 0));
        btnRegistrarBeneficioServicioAdicional.setColor_Hover_text(new java.awt.Color(0, 0, 0));
        btnRegistrarBeneficioServicioAdicional.setColor_NoHover_text(new java.awt.Color(0, 0, 0));
        btnRegistrarBeneficioServicioAdicional.setEsquina_inferior_derecho(20);
        btnRegistrarBeneficioServicioAdicional.setEsquina_inferior_izquierdo(20);
        btnRegistrarBeneficioServicioAdicional.setEsquina_superior_derecho(20);
        btnRegistrarBeneficioServicioAdicional.setEsquina_superior_izquierdo(20);
        btnRegistrarBeneficioServicioAdicional.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btnRegistrarBeneficioServicioAdicional.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnRegistrarBeneficioServicioAdicional.setIconTextGap(8);
        btnRegistrarBeneficioServicioAdicional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarBeneficioServicioAdicionalActionPerformed(evt);
            }
        });
        btnRegistrarBeneficioServicioAdicional.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                btnRegistrarBeneficioServicioAdicionalPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegistrarBeneficioServicioAdicional, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(btnRegistrarBeneficioServicioAdicional1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(btnRegistrarBeneficioServicioAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrarBeneficioServicioAdicional1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolver5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVolver5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolver5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolver5ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            mostrarDatosBoletaPago();
            mostrarNombresBeneficios();
            calcularMontoBeneficios();
            listarDescuentos();
        } catch (Exception ex) {
            Logger.getLogger(jdVentanaVerPago.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnRegistrarBeneficioServicioAdicionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarBeneficioServicioAdicionalActionPerformed
        try {
            jdVentanaRegistroBeneficioServicioAdicional obj =
                    new jdVentanaRegistroBeneficioServicioAdicional((Frame)SwingUtilities.getWindowAncestor(this), true);
            obj.setCodigocontrato(this.codcontrato);
            obj.setCodboleta(this.idboletapago);
            obj.setVisible(true);
            listarDescuentos();
        } catch (Exception ex) {
            Logger.getLogger(jdVentanaVerPago.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegistrarBeneficioServicioAdicionalActionPerformed

    private void listarDescuentos() throws Exception{
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Descuento");
        modelo.addColumn("Monto");
        modelo.addColumn("Descripción adicional");
        
        int numtard = objDesc.obtenerNumTardanzas(this.codcontrato, this.idboletapago);
        int numinasist = objDesc.obtenerNumInasistencias(this.codcontrato, this.idboletapago);
        
        lblNumTardanzas.setText(String.valueOf(numtard));
        lblNumInasistencias.setText(String.valueOf(numinasist));
        
        modelo.addRow(new Object[]{"Tardanza","S/. "+String.format("%.2f", numtard*1.13),"Ninguna"});
        modelo.addRow(new Object[]{"Inasistencia","S/. "+String.format("%.2f", numinasist*1.37),"Ninguna"});
        
        //Cargar las filas con beneficios o servicios adicionales:
        ResultSet rs = objDesc.obtenerDetalleServicioBeneficioAdicional(this.idboletapago);
        
        Object datos[] = new Object[3];
        while (rs.next()) {
            datos[0] = rs.getString("nombre");
            datos[1] = "S/. "+ String.format("%.2f", rs.getDouble("monto"));
            datos[2] = rs.getString("descripcion");
            modelo.addRow(datos);
        }
        
        tblDetalleDescuento.setModel(modelo);
    }
    
    private void btnRegistrarBeneficioServicioAdicionalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_btnRegistrarBeneficioServicioAdicionalPropertyChange

    }//GEN-LAST:event_btnRegistrarBeneficioServicioAdicionalPropertyChange

    private void btnRegistrarBeneficioServicioAdicional1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarBeneficioServicioAdicional1ActionPerformed
        jdVentanaConfirmacionPagoBoleta obj = new jdVentanaConfirmacionPagoBoleta((Frame)SwingUtilities.getWindowAncestor(this), true);
        obj.setJdVentanaVerPago(this);
        obj.setTblDetalleBenef((DefaultTableModel) tblDetalleBeneficio.getModel());
        obj.setTblDetalleDesc((DefaultTableModel) tblDetalleDescuento.getModel());
        obj.setIdboletapago(this.idboletapago);
        obj.setCodcontrato(this.codcontrato);
        obj.setVisible(true);
    }//GEN-LAST:event_btnRegistrarBeneficioServicioAdicional1ActionPerformed

    private void btnRegistrarBeneficioServicioAdicional1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_btnRegistrarBeneficioServicioAdicional1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarBeneficioServicioAdicional1PropertyChange

    private void mostrarDatosBoletaPago() throws Exception {
        SimpleDateFormat formatoSalida = new SimpleDateFormat("d MMM y");
        SimpleDateFormat formatoEntrada = new SimpleDateFormat("yyyy-MM-dd");

        ResultSet rs = objBP.obtenerDatosBoletaPagoSeleccionada(this.idboletapago);

        Object datos[] = new Object[4];

        while (rs.next()) {
            if (rs.getString("montototal").equals("No registra")) {
                datos[0] = rs.getString("montototal");
            } else {
                datos[0] = "S/. " + datos[1];
            }

            Date fecUPactd = new java.sql.Date(rs.getDate("fechapactada").getTime());
            datos[1] = formatoSalida.format(fecUPactd);

            if (rs.getString("fechapago").equals("No registra")) {
                datos[2] = rs.getString("fechapago");
            } else {
                Date fecUPago = formatoEntrada.parse(rs.getString("fechapago"));
                datos[2] = formatoSalida.format(fecUPago);
            }

            datos[3] = rs.getString("estadopago");

            lblMonto.setText(datos[0].toString());
            lblFechaPactada.setText(datos[1].toString());
            lblFechaPago.setText(datos[2].toString());
            lblEstado.setText(datos[3].toString());
        }
    }

    private void mostrarNombresBeneficios() throws Exception {
        ResultSet rs = objBenf.listarNombresBeneficios();
        Object datos[] = new Object[3];
        int cont = 0;
        while (rs.next()) {
            datos[cont] = rs.getString("nombre");
            cont++;
        }
        lblGratificacion.setText(datos[0].toString() + ":");
        lblAsignacionFamiliar.setText(datos[1].toString() + ":");
        lblCTS.setText(datos[2].toString() + ":");
    }

    private void calcularMontoBeneficios() throws ParseException, Exception {
        //Gratificación (solo meses de julio y diciembre):
        /*
        Gratificación: (Sueldo bruto * número de meses trabajados desde el inicio de contrato)/6 + 9% (si es que tiene seguro de salud)
         */
        SimpleDateFormat formatoEntrada = new SimpleDateFormat("d MMM y");
        Date fecha = formatoEntrada.parse(lblFechaPactada.getText());

        Calendar calendario = Calendar.getInstance();
        calendario.setTime(fecha);
        int mes = calendario.get(Calendar.MONTH);
        mes += 1;

        if (mes == 7 || mes == 12) {
            lblCorrespondeGrati.setText("Sí");
            this.montograti = objBP.obtenerMontoGrati(this.idboletapago);
        } else {
            lblCorrespondeGrati.setText("No corresponde");
        }

        //Asignación familiar
        boolean correspondeAF = objBP.correspondeAsignacionFamiliar(this.idboletapago);
        if (correspondeAF) {
            lblCorrespondeAsignacionFamiliar.setText("Sí");
            this.montoAF = 1025 * 0.10;
        } else {
            lblCorrespondeAsignacionFamiliar.setText("No corresponde");
        }

        if (mes != 5 || mes != 11) {
            lblCorrespondeCTS.setText("No corresponde");
        } else {
            lblCorrespondeCTS.setText("Sí");
            this.montoCTS = objBP.obtenerMontoCTS(this.codcontrato, idboletapago);
        }

        //Añadir a la tabla detalle_beneficio:
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Beneficio");
        modelo.addColumn("Monto");

        if (lblCorrespondeGrati.getText().equals("Sí")) {
            modelo.addRow(new Object[]{lblGratificacion.getText().replace(":", ""),
                "S/. " + String.format("%.2f", this.montograti)});
        }

        if (lblCorrespondeAsignacionFamiliar.getText().equals("Sí")) {
            modelo.addRow(new Object[]{lblAsignacionFamiliar.getText().replace(":", ""),
                "S/. " + String.format("%.2f", this.montoAF)});
        }

        if (lblCorrespondeCTS.getText().equals("Sí")) {
            modelo.addRow(new Object[]{lblCTS.getText().replace(":", ""),
                "S/. " + String.format("%.2f", this.montoCTS)});
        }
        tblDetalleBeneficio.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnRegistrarBeneficioServicioAdicional;
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnRegistrarBeneficioServicioAdicional1;
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnVolver5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAsignacionFamiliar;
    private javax.swing.JLabel lblCTS;
    private javax.swing.JLabel lblCorrespondeAsignacionFamiliar;
    private javax.swing.JLabel lblCorrespondeCTS;
    private javax.swing.JLabel lblCorrespondeGrati;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFechaPactada;
    private javax.swing.JLabel lblFechaPago;
    private javax.swing.JLabel lblGratificacion;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblNumInasistencias;
    private javax.swing.JLabel lblNumTardanzas;
    private javax.swing.JTable tblDetalleBeneficio;
    private javax.swing.JTable tblDetalleDescuento;
    // End of variables declaration//GEN-END:variables
}
