package Presentacion;

import Negocio.*;
import java.awt.Image;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.sql.Date;
import java.sql.Time;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JDialog;

public class jdVentanaResumenContrato extends javax.swing.JDialog {

    JDialog jdRC = new JDialog();
    JDialog jdRPL = new JDialog();

    public void setJdRPL(JDialog jdRPL) {
        this.jdRPL = jdRPL;
    }

    Contrato objCont = new Contrato();
    Empleado objEmp = new Empleado();
    TipoContrato objTC = new TipoContrato();
    PeriodoPago objPerPag = new PeriodoPago();
    HorarioTrabajo objHT = new HorarioTrabajo();
    Deduccion objDed = new Deduccion();

    public jdVentanaResumenContrato(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(obtenerImagen());
        setTitle("Resumen del contrato");
    }

    private void obtenerTodosLosDatos() {
        //Trabajador (o empleado)
        lblApePat.setText(this.apepat);
        lblApeMat.setText(this.apemat);
        lblNombres.setText(this.nombres);
        lblNumDocumento.setText(this.numdoc);
        lblTipoDoc.setText(this.tipdoc);
        lblTipoEmp.setText(this.tipoemp);
        lblArea.setText(this.area);

        //Contrato (fechas en formato: dd MMM yyyy; )
        lblTipoContrato.setText(this.tipocont);
        lblFechaInicio.setText(this.fechainicio);
        lblFechaTermino.setText(this.fechatermino);
        lblPeriodoPago.setText(this.periodopago);
        lblTurno.setText(this.turno);
        lblHorarioTrabajo.setText(this.horariotrabajo);
        lblDerechoVacaciones.setText(this.derechovacas);
        txtResponsabilidades.setText(this.responsabilidades);

        //Detalles de pago
        lblSueldoNeto.setText(this.sueldoneto);
        lblMontoFondoPensiones.setText(this.montofondopensiones);
        lblMontoSeguroSalud.setText(this.montosegurosalud);
        lblFondoPensiones.setText(this.fondopensiones);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTipoDoc = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblNumDocumento = new javax.swing.JLabel();
        lblApeMat = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        lblTipoEmp = new javax.swing.JLabel();
        lblArea = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblApePat = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblTipoContrato = new javax.swing.JLabel();
        lblFechaInicio = new javax.swing.JLabel();
        lblFechaTermino = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblPeriodoPago = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblTurno = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblHorarioTrabajo = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblDerechoVacaciones = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResponsabilidades = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblSueldoNeto = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblFondoPensiones = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblMontoFondoPensiones = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblMontoSeguroSalud = new javax.swing.JLabel();
        btnConfirmarContrato = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        btnVolver1 = new btn_efecto01_jwc.btn_efecto_V1_JWC();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("RESUMEN DE CONTRATO");

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Datos del trabajador");

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido materno:");

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombres:");

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("N° documento:");

        lblTipoDoc.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblTipoDoc.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoDoc.setText("jLabel6");

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tipo de documento:");

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tipo de empleado:");

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Área asignada:");

        lblNumDocumento.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblNumDocumento.setForeground(new java.awt.Color(255, 255, 255));
        lblNumDocumento.setText("jLabel6");

        lblApeMat.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblApeMat.setForeground(new java.awt.Color(255, 255, 255));
        lblApeMat.setText("jLabel6");

        lblNombres.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblNombres.setForeground(new java.awt.Color(255, 255, 255));
        lblNombres.setText("jLabel6");

        lblTipoEmp.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblTipoEmp.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoEmp.setText("jLabel6");

        lblArea.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblArea.setForeground(new java.awt.Color(255, 255, 255));
        lblArea.setText("jLabel6");

        jLabel19.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Apellido paterno:");

        lblApePat.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblApePat.setForeground(new java.awt.Color(255, 255, 255));
        lblApePat.setText("jLabel6");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblApePat, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblArea, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTipoEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblApeMat, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(lblApePat))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblApeMat))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblNombres))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblNumDocumento))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblTipoDoc))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblTipoEmp))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblArea))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(69, 161, 137));

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Datos del contrato");

        jLabel10.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tipo de contrato:");

        jLabel11.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Fecha de inicio:");

        jLabel12.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Fecha de término:");

        lblTipoContrato.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblTipoContrato.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoContrato.setText("jLabel6");

        lblFechaInicio.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblFechaInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaInicio.setText("jLabel6");

        lblFechaTermino.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblFechaTermino.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaTermino.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFechaTermino.setText("jLabel6");

        jLabel13.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Periodo de pago:");

        lblPeriodoPago.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblPeriodoPago.setForeground(new java.awt.Color(255, 255, 255));
        lblPeriodoPago.setText("jLabel6");

        jLabel14.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Turno:");

        lblTurno.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblTurno.setForeground(new java.awt.Color(255, 255, 255));
        lblTurno.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTurno.setText("jLabel6");

        jLabel15.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Horario de trabajo:");

        lblHorarioTrabajo.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblHorarioTrabajo.setForeground(new java.awt.Color(255, 255, 255));
        lblHorarioTrabajo.setText("jLabel6");

        jLabel16.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Derecho a vacaciones pagadas:");

        lblDerechoVacaciones.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblDerechoVacaciones.setForeground(new java.awt.Color(255, 255, 255));
        lblDerechoVacaciones.setText("jLabel6");

        jLabel17.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Responsabilidades asignadas:");

        txtResponsabilidades.setColumns(20);
        txtResponsabilidades.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        txtResponsabilidades.setRows(5);
        txtResponsabilidades.setText("txtarea");
        txtResponsabilidades.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtResponsabilidades.setEnabled(false);
        jScrollPane1.setViewportView(txtResponsabilidades);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(lblDerechoVacaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblHorarioTrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(lblTipoContrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPeriodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblFechaTermino, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))))
                        .addGap(24, 24, 24))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblTipoContrato))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(lblFechaInicio)
                    .addComponent(lblFechaTermino))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblPeriodoPago)
                    .addComponent(jLabel14)
                    .addComponent(lblTurno))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lblHorarioTrabajo))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lblDerechoVacaciones))
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(86, 201, 170));

        jLabel18.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Detalles de pago:");

        jLabel20.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Sueldo neto a pagar:");

        lblSueldoNeto.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblSueldoNeto.setForeground(new java.awt.Color(0, 0, 0));
        lblSueldoNeto.setText("jLabel6");

        jLabel21.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Fondo de pensiones asegurada:");

        lblFondoPensiones.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblFondoPensiones.setForeground(new java.awt.Color(0, 0, 0));
        lblFondoPensiones.setText("jLabel6");

        jLabel22.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Monto retenido:");

        lblMontoFondoPensiones.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblMontoFondoPensiones.setForeground(new java.awt.Color(0, 0, 0));
        lblMontoFondoPensiones.setText("jLabel6");

        jLabel23.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Monto retenido por seguro de salud:");

        lblMontoSeguroSalud.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblMontoSeguroSalud.setForeground(new java.awt.Color(0, 0, 0));
        lblMontoSeguroSalud.setText("jLabel6");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSueldoNeto, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMontoSeguroSalud, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMontoFondoPensiones, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(lblFondoPensiones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(lblSueldoNeto)
                    .addComponent(jLabel21)
                    .addComponent(lblFondoPensiones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(lblMontoFondoPensiones)
                    .addComponent(jLabel23)
                    .addComponent(lblMontoSeguroSalud))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btnConfirmarContrato.setBackground(new java.awt.Color(255, 255, 255));
        btnConfirmarContrato.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmarContrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/btn_confirmar_contrato.png"))); // NOI18N
        btnConfirmarContrato.setText("Confirmar");
        btnConfirmarContrato.setBackground_Hover_1(new java.awt.Color(51, 102, 0));
        btnConfirmarContrato.setBackground_Hover_2(new java.awt.Color(51, 102, 0));
        btnConfirmarContrato.setBackground_No_Hover_1(new java.awt.Color(51, 102, 0));
        btnConfirmarContrato.setBackground_No_Hover_2(new java.awt.Color(51, 102, 0));
        btnConfirmarContrato.setEsquina_inferior_derecho(20);
        btnConfirmarContrato.setEsquina_inferior_izquierdo(20);
        btnConfirmarContrato.setEsquina_superior_derecho(20);
        btnConfirmarContrato.setEsquina_superior_izquierdo(20);
        btnConfirmarContrato.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnConfirmarContrato.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnConfirmarContrato.setIconTextGap(8);
        btnConfirmarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarContratoActionPerformed(evt);
            }
        });

        btnVolver1.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver1.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton-x.png"))); // NOI18N
        btnVolver1.setText("");
        btnVolver1.setBackground_Hover_1(new java.awt.Color(255, 51, 51));
        btnVolver1.setBackground_Hover_2(new java.awt.Color(204, 0, 0));
        btnVolver1.setBackground_No_Hover_1(new java.awt.Color(255, 51, 51));
        btnVolver1.setBackground_No_Hover_2(new java.awt.Color(204, 0, 0));
        btnVolver1.setEsquina_inferior_derecho(20);
        btnVolver1.setEsquina_inferior_izquierdo(20);
        btnVolver1.setEsquina_superior_derecho(20);
        btnVolver1.setEsquina_superior_izquierdo(20);
        btnVolver1.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnVolver1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVolver1.setIconTextGap(8);
        btnVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConfirmarContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolver1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVolver1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmarContrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void confirmarContrato() {
        if (JOptionPane.showConfirmDialog(rootPane, "¿Registrar contrato?\nEsta acción no se puede deshacer", "Confirmar registro",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try {
                registrarContrato();
                JOptionPane.showMessageDialog(rootPane, "Contrato registrado");
                jdRPL.dispose();
                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(jdVentanaResumenContrato.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void btnConfirmarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarContratoActionPerformed
        try {
            confirmarContrato();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error al registrar contrato --> " + e.getMessage());
        }
    }//GEN-LAST:event_btnConfirmarContratoActionPerformed

    private void btnVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolver1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        obtenerTodosLosDatos();
    }//GEN-LAST:event_formWindowActivated

    //Datos de resumen:
    //Datos de trabajador
    String apepat;
    String apemat;
    String nombres;
    String numdoc;
    String tipdoc;
    String tipoemp;
    String area;

    //Datos de contrato
    String tipocont;
    String fechainicio;
    String fechatermino;
    String periodopago;
    String turno;
    String horariotrabajo;
    String derechovacas;
    String responsabilidades;

    //Datos de detalles de pago (listo)
    String sueldoneto;
    String fondopensiones;
    String montofondopensiones;
    String montosegurosalud;

    public void setApepat(String apepat) {
        this.apepat = apepat;
    }

    public void setApemat(String apemat) {
        this.apemat = apemat;
    }

    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    public void setNumdoc(String numdoc) {
        this.numdoc = numdoc;
    }

    public void setTipdoc(String tipdoc) {
        this.tipdoc = tipdoc;
    }

    public void setTipoemp(String tipoemp) {
        this.tipoemp = tipoemp;
    }

    public void setArea(String area) {
        this.area = area;
    }

    public void setTipocont(String tipocont) {
        this.tipocont = tipocont;
    }

    public void setFechainicio(String fechainicio) {
        this.fechainicio = fechainicio;
    }

    public void setFechatermino(String fechatermino) {
        this.fechatermino = fechatermino;
    }

    public void setPeriodopago(String periodopago) {
        this.periodopago = periodopago;
    }

    public void setTurno(String turno) {
        this.turno = turno;
    }

    public void setHorariotrabajo(String horariotrabajo) {
        this.horariotrabajo = horariotrabajo;
    }

    public void setDerechovacas(String derechovacas) {
        this.derechovacas = derechovacas;
    }

    public void setResponsabilidades(String responsabilidades) {
        this.responsabilidades = responsabilidades;
    }

    public void setSueldoneto(String sueldoneto) {
        this.sueldoneto = sueldoneto;
    }

    public void setFondopensiones(String fondopensiones) {
        this.fondopensiones = fondopensiones;
    }

    public void setMontofondopensiones(String montofondopensiones) {
        this.montofondopensiones = montofondopensiones;
    }

    public void setMontosegurosalud(String montosegurosalud) {
        this.montosegurosalud = montosegurosalud;
    }

    private void registrarContrato() throws Exception {

        String numdocc = lblNumDocumento.getText();
        String tipodoc = lblTipoDoc.getText();
        int idempleado = objEmp.obtenerIdEmpleado(numdocc, tipodoc);

        //-----------------------------CONTRATO---------------------------
        //Para insertar en contrato:
        int idContrato = objCont.generarNumContrato(idempleado);
        Date fechaInicio = convertirFecha(lblFechaInicio.getText());
        Date fechaTermino = convertirFecha(lblFechaTermino.getText());
        int idtipocontrato = objTC.obtenerIdTipoContrato(lblTipoContrato.getText());
        double sueldonetoo = Double.parseDouble(lblSueldoNeto.getText());
        String responsabilidadesss = txtResponsabilidades.getText();
        //estado por defecto='V' (vigente)
        //idempleado ya se calculó en la línea 3 del método
        int idperiodopago = objPerPag.obtenerIdPeriodoPago(lblPeriodoPago.getText());
        //fecha_registro='current_date'

        int operadorid = Empleado.ID_USUARIO_LOGGEADO;

        String vacaspagadas = lblDerechoVacaciones.getText();
        boolean vacaspagadass = false;
        if (vacaspagadas.equals("Sí")) {
            vacaspagadass = true;
        }
        Time horaInicio = obtenerHoras()[0];
        Time horaFin = obtenerHoras()[1];
        int idhorariotrabajo = objHT.obtenerIdHorarioTrabajo(horaInicio, horaFin);

        //Para insertar en detalle_deduccion:
        //Seguro de fondo de pensiones
        int idfondo = objDed.obtenerIdDeduccion(lblFondoPensiones.getText());
        double montoRet = Double.parseDouble(lblMontoFondoPensiones.getText());
        //Seguro de salud
        double montoSegSalud = Double.parseDouble(lblMontoSeguroSalud.getText());
        
        //columna adicional de contrato:
        double salarioBruto = sueldonetoo+montoRet+montoSegSalud;

        try {
            //insert:
            objCont.registrarContratoBD(idContrato, fechaInicio, fechaTermino, idtipocontrato, sueldonetoo, responsabilidadesss, "V",
                    idempleado, idperiodopago, vacaspagadass, idhorariotrabajo, operadorid, salarioBruto);

            //-----------------------------DETALLE_DEDUCCION---------------------------
            objDed.registrarDetalleDeduccion(idContrato, idfondo, montoRet);

            if (montoSegSalud > 0) {
                int idseguro = objDed.obtenerIdDeduccion("EsSalud");
                objDed.registrarDetalleDeduccion(idContrato, idseguro, montoSegSalud);
            }
            
            //------------------------------EMPLEADO----------------------------------
            objEmp.darDeAltaEmpleado(idempleado);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error al registrar contrato -->" + e.getMessage());
        }
    }

    private Date convertirFecha(String fechaEntr) throws ParseException {
        // Formato de entrada
        SimpleDateFormat formatoEntrada = new SimpleDateFormat("dd MMM yyyy");

        // Parsear la fecha directamente utilizando el formato de entrada
        java.util.Date fechaUtil = formatoEntrada.parse(fechaEntr);

        // Convertir la fecha util a java.sql.Date
        java.sql.Date fechaSql = new java.sql.Date(fechaUtil.getTime());

        return fechaSql;
    }

    private Time[] obtenerHoras() throws ParseException {
        Time[] horas = new Time[2];

        // Formato de entrada y salida
        SimpleDateFormat formato12Horas = new SimpleDateFormat("h:mm a");
        SimpleDateFormat formato24Horas = new SimpleDateFormat("HH:mm");

        String horarioTexto = lblHorarioTrabajo.getText();

        // Extraer las partes de la hora
        String[] horasTexto = horarioTexto.split(" - ");
        String txthoraInicio = horasTexto[0];
        String txthoraFin = horasTexto[1];

        // Convertir horas de 12 horas a 24 horas
        java.util.Date hora1 = formato12Horas.parse(txthoraInicio);
        java.util.Date hora2 = formato12Horas.parse(txthoraFin);

        String horasstr1 = formato24Horas.format(hora1);
        String horasstr2 = formato24Horas.format(hora2);

        // Convertir las cadenas de 24 horas a objetos Time
        horas[0] = Time.valueOf(horasstr1 + ":00");
        horas[1] = Time.valueOf(horasstr2 + ":00");

        return horas;
    }

    public static Image obtenerImagen() {

        Image icono = null;
        try {
            icono = new ImageIcon(jdVentanaResumenContrato.class.getResource("/Recursos/icono_resumen_contrato.png")).getImage();
        } catch (Exception e) {
            System.out.println("No se pudo cargar la imagen: " + e.getMessage());
        }
        return icono;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnConfirmarContrato;
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnVolver1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApeMat;
    private javax.swing.JLabel lblApePat;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblDerechoVacaciones;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblFechaTermino;
    private javax.swing.JLabel lblFondoPensiones;
    private javax.swing.JLabel lblHorarioTrabajo;
    private javax.swing.JLabel lblMontoFondoPensiones;
    private javax.swing.JLabel lblMontoSeguroSalud;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblNumDocumento;
    private javax.swing.JLabel lblPeriodoPago;
    private javax.swing.JLabel lblSueldoNeto;
    private javax.swing.JLabel lblTipoContrato;
    private javax.swing.JLabel lblTipoDoc;
    private javax.swing.JLabel lblTipoEmp;
    private javax.swing.JLabel lblTurno;
    private javax.swing.JTextArea txtResponsabilidades;
    // End of variables declaration//GEN-END:variables
}
