/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Presentacion;

import Negocio.Empleado;
import java.awt.Frame;
import java.awt.Image;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author jefer
 */
public class jdVentanaBuscarEmpleado extends javax.swing.JDialog {

    String numdoc, tipodoc, nombres, apepat, apemat, tipoemp, nomarea;

    public String getNumdoc() {
        return numdoc;
    }

    public String getTipodoc() {
        return tipodoc;
    }

    public String getNombres() {
        return nombres;
    }

    public String getApepat() {
        return apepat;
    }

    public String getApemat() {
        return apemat;
    }

    public String getTipoemp() {
        return tipoemp;
    }

    public String getNomarea() {
        return nomarea;
    }

    Empleado objE = new Empleado();

    public jdVentanaBuscarEmpleado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(obtenerImagen());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNumDocEmpleado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        btnVolver1 = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        btnNuevoEmpleado = new btn_efecto01_jwc.btn_efecto_V1_JWC();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar empleado por Número de documento");
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(69, 161, 137));

        txtNumDocEmpleado.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        txtNumDocEmpleado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtNumDocEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumDocEmpleadoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumDocEmpleadoKeyTyped(evt);
            }
        });

        jScrollPane1.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N

        tblEmpleados.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblEmpleados.setGridColor(new java.awt.Color(0, 0, 0));
        tblEmpleados.setSelectionBackground(new java.awt.Color(153, 153, 153));
        tblEmpleados.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmpleados);

        jLabel13.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("BUSCAR POR N° DOCUMENTO Y SELECCIONAR");

        btnVolver1.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver1.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton-x.png"))); // NOI18N
        btnVolver1.setText("");
        btnVolver1.setBackground_Hover_1(new java.awt.Color(255, 51, 51));
        btnVolver1.setBackground_Hover_2(new java.awt.Color(204, 0, 0));
        btnVolver1.setBackground_No_Hover_1(new java.awt.Color(255, 51, 51));
        btnVolver1.setBackground_No_Hover_2(new java.awt.Color(204, 0, 0));
        btnVolver1.setEsquina_inferior_derecho(20);
        btnVolver1.setEsquina_inferior_izquierdo(20);
        btnVolver1.setEsquina_superior_derecho(20);
        btnVolver1.setEsquina_superior_izquierdo(20);
        btnVolver1.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnVolver1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVolver1.setIconTextGap(8);
        btnVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver1ActionPerformed(evt);
            }
        });

        btnNuevoEmpleado.setBackground(new java.awt.Color(255, 204, 0));
        btnNuevoEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/btn_registrar_nuevo_empleado.png"))); // NOI18N
        btnNuevoEmpleado.setText("");
        btnNuevoEmpleado.setBackground_Hover_1(new java.awt.Color(255, 204, 0));
        btnNuevoEmpleado.setBackground_Hover_2(new java.awt.Color(255, 204, 0));
        btnNuevoEmpleado.setBackground_No_Hover_1(new java.awt.Color(255, 204, 0));
        btnNuevoEmpleado.setBackground_No_Hover_2(new java.awt.Color(255, 204, 0));
        btnNuevoEmpleado.setColor_Hover_text(new java.awt.Color(0, 0, 0));
        btnNuevoEmpleado.setColor_NoHover_text(new java.awt.Color(0, 0, 0));
        btnNuevoEmpleado.setEsquina_inferior_derecho(20);
        btnNuevoEmpleado.setEsquina_inferior_izquierdo(20);
        btnNuevoEmpleado.setEsquina_superior_derecho(20);
        btnNuevoEmpleado.setEsquina_superior_izquierdo(20);
        btnNuevoEmpleado.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btnNuevoEmpleado.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnNuevoEmpleado.setIconTextGap(8);
        btnNuevoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoEmpleadoActionPerformed(evt);
            }
        });
        btnNuevoEmpleado.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                btnNuevoEmpleadoPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolver1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNumDocEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNuevoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVolver1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNumDocEmpleado)
                    .addComponent(btnNuevoEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumDocEmpleadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDocEmpleadoKeyReleased
        try {
            listarEmpleados();
        } catch (Exception ex) {
            Logger.getLogger(jdVentanaBuscarEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtNumDocEmpleadoKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void tblEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpleadosMouseClicked
        try {
            String numdocc = tblEmpleados.getValueAt(tblEmpleados.getSelectedRow(), 0).toString();
            String tipodocc = tblEmpleados.getValueAt(tblEmpleados.getSelectedRow(), 1).toString();
            int idempleado = objE.obtenerIdEmpleado(numdocc, tipodocc);
            boolean existe = objE.existeContratoVigente(idempleado);

            if (existe) {
                JOptionPane.showMessageDialog(rootPane, "El empleado ya tiene un contrato vigente");
            } else {
                if (tblEmpleados.getSelectedRowCount() > 0) {
                    this.numdoc = tblEmpleados.getValueAt(tblEmpleados.getSelectedRow(), 0).toString();
                    this.tipodoc = tblEmpleados.getValueAt(tblEmpleados.getSelectedRow(), 1).toString();
                    this.apepat = tblEmpleados.getValueAt(tblEmpleados.getSelectedRow(), 2).toString();
                    this.apemat = tblEmpleados.getValueAt(tblEmpleados.getSelectedRow(), 3).toString();
                    this.nombres = tblEmpleados.getValueAt(tblEmpleados.getSelectedRow(), 4).toString();
                    this.tipoemp = tblEmpleados.getValueAt(tblEmpleados.getSelectedRow(), 5).toString();
                    this.nomarea = tblEmpleados.getValueAt(tblEmpleados.getSelectedRow(), 6).toString();

                    jdContratacionPersonal obj = new jdContratacionPersonal((Frame) SwingUtilities.getWindowAncestor(this), true);
                    obj.setLocationRelativeTo(this);
                }
                dispose();
            }
        } catch (Exception ex) {
            Logger.getLogger(jdVentanaBuscarEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblEmpleadosMouseClicked

    private void btnVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolver1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            listarEmpleados();
        } catch (Exception ex) {
            Logger.getLogger(jdVentanaBuscarEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowActivated

    private void txtNumDocEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDocEmpleadoKeyTyped
        if (txtNumDocEmpleado.getText().length()>=20) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNumDocEmpleadoKeyTyped

    private void btnNuevoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoEmpleadoActionPerformed
        jdVentanaNuevoEmpleado obj = new jdVentanaNuevoEmpleado((Frame)SwingUtilities.getWindowAncestor(this), true);
        obj.setVisible(true);
    }//GEN-LAST:event_btnNuevoEmpleadoActionPerformed

    private void btnNuevoEmpleadoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_btnNuevoEmpleadoPropertyChange

    }//GEN-LAST:event_btnNuevoEmpleadoPropertyChange

    private void listarEmpleados() throws Exception {

        DefaultTableModel modelo = new DefaultTableModel();

        modelo.addColumn("Número de documento");
        modelo.addColumn("Tipo de documento");
        modelo.addColumn("Apellido paterno");
        modelo.addColumn("Apellido materno");
        modelo.addColumn("Nombres");
        modelo.addColumn("Tipo de empleado");
        modelo.addColumn("Área");

        String nombre = txtNumDocEmpleado.getText();
        ResultSet rs = objE.filtrarEmpleado(nombre);

        Object datos[] = new Object[7];

        while (rs.next()) {
            datos[0] = rs.getString("numdocumento");
            datos[1] = rs.getString("nombretipodoc");
            datos[2] = rs.getString("ape_paterno");
            datos[3] = rs.getString("ape_materno");
            datos[4] = rs.getString("nombres");
            datos[5] = rs.getString("nombretipoempleado");
            datos[6] = rs.getString("nombrearea");
            modelo.addRow(datos);
        }
        tblEmpleados.setModel(modelo);

    }
    
    public static Image obtenerImagen() {
    
    Image icono = null;
        try {
            icono = new ImageIcon(jdVentanaBuscarEmpleado.class.getResource("/Recursos/btn_buscar_empleado.png")).getImage();
        } catch (Exception e) {
            System.out.println("No se pudo cargar la imagen: " + e.getMessage());
        }
        return icono;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnNuevoEmpleado;
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnVolver1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmpleados;
    private javax.swing.JTextField txtNumDocEmpleado;
    // End of variables declaration//GEN-END:variables
}
