/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Presentacion;

import Negocio.BoletaPago;
import Negocio.Contrato;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jefer
 */
public class jdVentanaConfirmacionPagoBoleta extends javax.swing.JDialog {

    private DefaultTableModel tblDetalleBenef;
    private DefaultTableModel tblDetalleDesc;
    private JDialog jdVentanaVerPago;
    private int idboletapago = 0;
    private int codcontrato = 0;

    public void setTblDetalleBenef(DefaultTableModel tblDetalleBenef) {
        this.tblDetalleBenef = tblDetalleBenef;
    }

    public void setTblDetalleDesc(DefaultTableModel tblDetalleDesc) {
        this.tblDetalleDesc = tblDetalleDesc;
    }

    public void setJdVentanaVerPago(JDialog jdVentanaVerPago) {
        this.jdVentanaVerPago = jdVentanaVerPago;
    }

    public void setIdboletapago(int idboletapago) {
        this.idboletapago = idboletapago;
    }

    public void setCodcontrato(int codcontrato) {
        this.codcontrato = codcontrato;
    }
    
    Contrato objC = new Contrato();
    BoletaPago objBP = new BoletaPago();
    
    public jdVentanaConfirmacionPagoBoleta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVolver5 = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalleBeneficio = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        lblFechaPago = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetalleDescuento = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lblSalarioNeto = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblMontoTotal = new javax.swing.JLabel();
        btnConfirmarPago = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        jLabel13 = new javax.swing.JLabel();
        lblTotalBeneficios = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblTotalDescuentos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CONFIRMACION DE PAGO");

        btnVolver5.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver5.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton-x.png"))); // NOI18N
        btnVolver5.setText("");
        btnVolver5.setBackground_Hover_1(new java.awt.Color(255, 51, 51));
        btnVolver5.setBackground_Hover_2(new java.awt.Color(204, 0, 0));
        btnVolver5.setBackground_No_Hover_1(new java.awt.Color(255, 51, 51));
        btnVolver5.setBackground_No_Hover_2(new java.awt.Color(204, 0, 0));
        btnVolver5.setEsquina_inferior_derecho(20);
        btnVolver5.setEsquina_inferior_izquierdo(20);
        btnVolver5.setEsquina_superior_derecho(20);
        btnVolver5.setEsquina_superior_izquierdo(20);
        btnVolver5.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnVolver5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVolver5.setIconTextGap(8);
        btnVolver5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver5ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(69, 161, 137));

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Beneficios de ley:");

        tblDetalleBeneficio.setBackground(new java.awt.Color(255, 255, 255));
        tblDetalleBeneficio.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        tblDetalleBeneficio.setForeground(new java.awt.Color(0, 0, 0));
        tblDetalleBeneficio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblDetalleBeneficio);

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fecha de pago:");

        lblFechaPago.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblFechaPago.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaPago.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaPago, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel6.setBackground(new java.awt.Color(69, 161, 137));

        tblDetalleDescuento.setBackground(new java.awt.Color(255, 255, 255));
        tblDetalleDescuento.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        tblDetalleDescuento.setForeground(new java.awt.Color(0, 0, 0));
        tblDetalleDescuento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblDetalleDescuento);

        jLabel12.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Descuentos:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel15.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Salario neto:");

        lblSalarioNeto.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblSalarioNeto.setForeground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Monto total a pagar:");

        lblMontoTotal.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblMontoTotal.setForeground(new java.awt.Color(255, 255, 255));

        btnConfirmarPago.setBackground(new java.awt.Color(51, 102, 0));
        btnConfirmarPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/btn_asistencia.png"))); // NOI18N
        btnConfirmarPago.setText("Confirmar");
        btnConfirmarPago.setBackground_Hover_1(new java.awt.Color(51, 102, 0));
        btnConfirmarPago.setBackground_Hover_2(new java.awt.Color(51, 102, 0));
        btnConfirmarPago.setBackground_No_Hover_1(new java.awt.Color(255, 204, 0));
        btnConfirmarPago.setBackground_No_Hover_2(new java.awt.Color(255, 204, 0));
        btnConfirmarPago.setColor_NoHover_text(new java.awt.Color(0, 0, 0));
        btnConfirmarPago.setEsquina_inferior_derecho(20);
        btnConfirmarPago.setEsquina_inferior_izquierdo(20);
        btnConfirmarPago.setEsquina_superior_derecho(20);
        btnConfirmarPago.setEsquina_superior_izquierdo(20);
        btnConfirmarPago.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btnConfirmarPago.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnConfirmarPago.setIconTextGap(8);
        btnConfirmarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarPagoActionPerformed(evt);
            }
        });
        btnConfirmarPago.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                btnConfirmarPagoPropertyChange(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Total beneficios:");

        lblTotalBeneficios.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblTotalBeneficios.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalBeneficios.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel14.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Total dsctos.:");

        lblTotalDescuentos.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblTotalDescuentos.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalDescuentos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblSalarioNeto, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addComponent(lblTotalBeneficios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addComponent(lblTotalDescuentos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConfirmarPago, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(lblMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblSalarioNeto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15))
                    .addComponent(jLabel16)
                    .addComponent(lblMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTotalBeneficios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTotalDescuentos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnConfirmarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolver5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVolver5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolver5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolver5ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            setearFechaActual();
            listarTablasYMontos();
            calcularMontoTotalPago();
        } catch (Exception ex) {
            Logger.getLogger(jdVentanaConfirmacionPagoBoleta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnConfirmarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarPagoActionPerformed
        int opcion = JOptionPane.showConfirmDialog(rootPane, "¿Registrar pago de boleta?\n\nEsta acción es irreversible", "Confirmar cambios",
                JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            try {
                double sueldopagado = Double.parseDouble(lblSalarioNeto.getText().replace("S/. ", ""));
                double montototalbenef = Double.parseDouble(lblTotalBeneficios.getText().replace("S/. ", ""));
                double montototaldsctos = Double.parseDouble(lblTotalDescuentos.getText().replace("S/. ", ""));
                double montototalpagar = Double.parseDouble(lblMontoTotal.getText().replace("S/. ", ""));
                int idboleta = this.idboletapago;
                objBP.registrarPagoBoleta(tblDetalleBeneficio, tblDetalleDescuento, sueldopagado, montototalbenef, montototaldsctos, montototalpagar, idboletapago);
                JOptionPane.showMessageDialog(rootPane, "El pago de la boleta ha sido registrado", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                jdVentanaVerPago.dispose();
                this.dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, "Error al registrar pago de boleta --> "+ex.getMessage(), "Ha ocurrido un error",
                JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnConfirmarPagoActionPerformed

    private void btnConfirmarPagoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_btnConfirmarPagoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmarPagoPropertyChange

    private void listarTablasYMontos(){
        tblDetalleBeneficio.setModel(this.tblDetalleBenef);
        tblDetalleDescuento.setModel(this.tblDetalleDesc);
        
        double totalBenef=0;
        for (int i = 0; i < tblDetalleBeneficio.getRowCount(); i++) {
            double montoP = Double.parseDouble(tblDetalleBeneficio.getValueAt(i, 1).toString().replace("S/. ", ""));
            totalBenef+=montoP;
        }
        
        double totalDesc = 0;
        for (int i = 0; i < tblDetalleDescuento.getRowCount(); i++) {
            double montoP = Double.parseDouble(tblDetalleDescuento.getValueAt(i, 1).toString().replace("S/. ", ""));
            totalDesc += montoP;
        }
        
        lblTotalBeneficios.setText("S/. "+String.format("%.2f", totalBenef));
        lblTotalDescuentos.setText("S/. "+String.format("%.2f", totalDesc));
    }
    
    private void setearFechaActual(){
        Calendar cal = Calendar.getInstance();
        Date fechaActual = cal.getTime();
        SimpleDateFormat formato = new SimpleDateFormat("d MMM y");
        lblFechaPago.setText(formato.format(fechaActual));
    }
    
    private void calcularMontoTotalPago() throws Exception{
        double salariobr = objC.obtenerSalarioNetoEmpleado(this.codcontrato);
        lblSalarioNeto.setText("S/. "+String.format("%.2f", salariobr));
        double montoTotalBnf = Double.parseDouble(lblTotalBeneficios.getText().replace("S/. ", ""));
        double montoTotalDsc = Double.parseDouble(lblTotalDescuentos.getText().replace("S/. ", ""));
        double montoTotal = salariobr+montoTotalBnf-montoTotalDsc;
        
        lblMontoTotal.setText("S/. "+String.format("%.2f", montoTotal));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnConfirmarPago;
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnVolver5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFechaPago;
    private javax.swing.JLabel lblMontoTotal;
    private javax.swing.JLabel lblSalarioNeto;
    private javax.swing.JLabel lblTotalBeneficios;
    private javax.swing.JLabel lblTotalDescuentos;
    private javax.swing.JTable tblDetalleBeneficio;
    private javax.swing.JTable tblDetalleDescuento;
    // End of variables declaration//GEN-END:variables
}
