/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Presentacion;

import Negocio.Contrato;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import Negocio.TipoPermiso;
import Negocio.Empleado;
import Negocio.Permiso;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author jefer
 */
public class jdVentanaRegistrarNuevoPermiso extends javax.swing.JDialog {

    Permiso objPermiso = new Permiso();
    Contrato objC = new Contrato();

    private int idemp = -1;

    public void setIdemp(int idemp) {
        this.idemp = idemp;
    }

    public jdVentanaRegistrarNuevoPermiso(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            initComponents();
            setearFechaActual();
            setLocationRelativeTo(this);
        } catch (Exception ex) {
            Logger.getLogger(jdVentanaRegistrarNuevoPermiso.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblDuracionTipoPermiso = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cboTipoPermiso = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        lblEmpleado = new javax.swing.JLabel();
        lblDescripcionTipoPermiso = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblFechaSolicitud = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcionTipoPermiso = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        lblFechaMaxima = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        dchsrFechaInicio = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        lblFechaTermino = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcionSolicitud = new javax.swing.JTextArea();
        btnConfirmar = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        lblAvisoExcede = new javax.swing.JLabel();
        btnVolver1 = new btn_efecto01_jwc.btn_efecto_V1_JWC();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Empleado:");

        lblDuracionTipoPermiso.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblDuracionTipoPermiso.setForeground(new java.awt.Color(255, 255, 255));
        lblDuracionTipoPermiso.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblDuracionTipoPermisoPropertyChange(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tipo de permiso:");

        cboTipoPermiso.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        cboTipoPermiso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTipoPermisoItemStateChanged(evt);
            }
        });
        cboTipoPermiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoPermisoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Duración máxima:");

        lblEmpleado.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblEmpleado.setForeground(new java.awt.Color(255, 255, 255));

        lblDescripcionTipoPermiso.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        lblDescripcionTipoPermiso.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcionTipoPermiso.setText("Descripción del tipo de permiso:");

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fecha de solicitud:");

        lblFechaSolicitud.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblFechaSolicitud.setForeground(new java.awt.Color(255, 255, 255));

        txtDescripcionTipoPermiso.setColumns(20);
        txtDescripcionTipoPermiso.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        txtDescripcionTipoPermiso.setRows(5);
        txtDescripcionTipoPermiso.setToolTipText("<html></html>");
        txtDescripcionTipoPermiso.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDescripcionTipoPermiso.setEnabled(false);
        jScrollPane2.setViewportView(txtDescripcionTipoPermiso);

        jLabel14.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Fecha máxima:");

        lblFechaMaxima.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblFechaMaxima.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaMaxima.setText("dd mmm. YYYY");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboTipoPermiso, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblDescripcionTipoPermiso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblFechaMaxima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFechaSolicitud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDuracionTipoPermiso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 36, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTipoPermiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDuracionTipoPermiso, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcionTipoPermiso)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addGap(20, 20, 20))
        );

        jLabel13.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("REGISTRAR UN NUEVO PERMISO");

        jPanel3.setBackground(new java.awt.Color(69, 161, 137));

        jLabel10.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Fecha de inicio:");

        dchsrFechaInicio.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        dchsrFechaInicio.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dchsrFechaInicioPropertyChange(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Fecha de término:");

        lblFechaTermino.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lblFechaTermino.setForeground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Descripción de la solicitud:");

        txtDescripcionSolicitud.setColumns(20);
        txtDescripcionSolicitud.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        txtDescripcionSolicitud.setRows(5);
        txtDescripcionSolicitud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripcionSolicitudKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtDescripcionSolicitud);

        btnConfirmar.setBackground(new java.awt.Color(102, 102, 102));
        btnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/btn_registrar_nuevo_permiso.png"))); // NOI18N
        btnConfirmar.setText("Registrar");
        btnConfirmar.setBackground_Hover_1(new java.awt.Color(255, 204, 0));
        btnConfirmar.setBackground_Hover_2(new java.awt.Color(255, 204, 0));
        btnConfirmar.setBackground_No_Hover_1(new java.awt.Color(255, 204, 0));
        btnConfirmar.setBackground_No_Hover_2(new java.awt.Color(255, 204, 0));
        btnConfirmar.setColor_Hover_text(new java.awt.Color(0, 0, 0));
        btnConfirmar.setColor_NoHover_text(new java.awt.Color(0, 0, 0));
        btnConfirmar.setEsquina_inferior_derecho(20);
        btnConfirmar.setEsquina_inferior_izquierdo(20);
        btnConfirmar.setEsquina_superior_derecho(20);
        btnConfirmar.setEsquina_superior_izquierdo(20);
        btnConfirmar.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btnConfirmar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnConfirmar.setIconTextGap(8);
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        lblAvisoExcede.setFont(new java.awt.Font("Nirmala UI", 2, 12)); // NOI18N
        lblAvisoExcede.setForeground(new java.awt.Color(153, 0, 0));
        lblAvisoExcede.setToolTipText("<html>");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblFechaTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 332, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(dchsrFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblAvisoExcede, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(dchsrFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(14, 14, 14))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAvisoExcede, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnVolver1.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver1.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton-x.png"))); // NOI18N
        btnVolver1.setText("");
        btnVolver1.setBackground_Hover_1(new java.awt.Color(255, 51, 51));
        btnVolver1.setBackground_Hover_2(new java.awt.Color(204, 0, 0));
        btnVolver1.setBackground_No_Hover_1(new java.awt.Color(255, 51, 51));
        btnVolver1.setBackground_No_Hover_2(new java.awt.Color(204, 0, 0));
        btnVolver1.setEsquina_inferior_derecho(20);
        btnVolver1.setEsquina_inferior_izquierdo(20);
        btnVolver1.setEsquina_superior_derecho(20);
        btnVolver1.setEsquina_superior_izquierdo(20);
        btnVolver1.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnVolver1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVolver1.setIconTextGap(8);
        btnVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolver1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVolver1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        try {
            if (txtDescripcionSolicitud.getText().isBlank()) {
                JOptionPane.showMessageDialog(rootPane, "Ingrese la descripción de la solicitud");
            } else {
                SimpleDateFormat formato = new SimpleDateFormat("dd MMM yyyy");
                //Casteamos la fecha de inicio
                Date fechautilini = dchsrFechaInicio.getDate();
                java.sql.Date fechaini = new java.sql.Date(fechautilini.getTime());
                //Casteamos la fecha de fin
                Date fechautilfin = formato.parse(lblFechaTermino.getText());
                java.sql.Date fechafin = new java.sql.Date(fechautilfin.getTime());
                //El resto de datos:
                String descr = txtDescripcionSolicitud.getText();
                int idEmp = this.idemp;
                TipoPermiso obj = new TipoPermiso();
                int idTipo = obj.obtenerIdTipoPermiso(cboTipoPermiso.getSelectedItem().toString());

                //Comprobamos si existe cruce de horarios de permisos;
                boolean existeCruce = objPermiso.existeCrucePermisos(idEmp, fechaini, fechafin);
                if (existeCruce) {
                    JOptionPane.showMessageDialog(rootPane, "El rango de fechas se cruza con otros permisos. Por favor, elija otro rango de fechas",
                            "Cruce de fechas", JOptionPane.ERROR_MESSAGE);
                } else {
                    if (JOptionPane.showConfirmDialog(rootPane, "¿Registrar solicitud de permiso?", "Confirmar", JOptionPane.YES_NO_OPTION)
                            == JOptionPane.YES_OPTION) {
                        objPermiso.registrarSolicitudPermiso(fechaini, fechafin, descr, idEmp, idTipo);
                        JOptionPane.showMessageDialog(rootPane, "Solicitud de permiso registrada", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();
                    }
                }

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "La solicitud de permiso no se pudo registrar --> " + ex.getMessage(),
                    "Error al registrar", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void dchsrFechaInicioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dchsrFechaInicioPropertyChange
        if (dchsrFechaInicio.getDate() != null) {
            try {
                calcularFechaFinPermiso();
            } catch (Exception ex) {
                Logger.getLogger(jdVentanaRegistrarNuevoPermiso.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        try {
            if (cboTipoPermiso.getSelectedItem() != null && !lblFechaTermino.getText().isBlank()) {
                if (excede()) {
                    btnConfirmar.setEnabled(false);
                    lblAvisoExcede.setText("Esta fecha excede la fecha de término de tu contrato. Selecciona otra fecha.");
                } else {
                    btnConfirmar.setEnabled(true);
                    lblAvisoExcede.setText("");
                }
            }
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_dchsrFechaInicioPropertyChange

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void cboTipoPermisoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTipoPermisoItemStateChanged
        if (cboTipoPermiso.getSelectedItem().toString() != null) {
            try {
                setearNombreEmpleado();
                setearDatosTipoPermiso();
                calcularFechaFinPermiso();
            } catch (Exception ex) {
                Logger.getLogger(jdVentanaRegistrarNuevoPermiso.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        try {
            if (cboTipoPermiso.getSelectedItem() != null && !lblFechaTermino.getText().isBlank()) {
                if (excede()) {
                    btnConfirmar.setEnabled(false);
                    lblAvisoExcede.setText("Esta fecha excede la fecha de término de tu contrato. Selecciona otra fecha.");
                } else {
                    btnConfirmar.setEnabled(true);
                    lblAvisoExcede.setText("");
                }
            }
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_cboTipoPermisoItemStateChanged

    private void lblDuracionTipoPermisoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblDuracionTipoPermisoPropertyChange
        if (lblDuracionTipoPermiso.getText().equals("---")) {
            dchsrFechaInicio.setEnabled(false);
        } else {
            dchsrFechaInicio.setEnabled(true);
        }
    }//GEN-LAST:event_lblDuracionTipoPermisoPropertyChange

    private void cboTipoPermisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoPermisoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTipoPermisoActionPerformed

    private void btnVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolver1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            cargarCboTipoPermiso();
            setearDatosTipoPermiso();
            validarFechaInicioPermiso();
        } catch (Exception ex) {
            Logger.getLogger(jdVentanaRegistrarNuevoPermiso.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowActivated

    private void txtDescripcionSolicitudKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionSolicitudKeyTyped
        if (txtDescripcionSolicitud.getText().length() >= 300) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDescripcionSolicitudKeyTyped

    private void cargarCboTipoPermiso() throws Exception {
        TipoPermiso obj = new TipoPermiso();
        ResultSet rs = obj.listarTiposPermisos();
        while (rs.next()) {
            cboTipoPermiso.addItem(rs.getString("nombre"));
        }
    }

    private void setearDatosTipoPermiso() throws Exception {
        TipoPermiso obj = new TipoPermiso();
        String tipoperm = cboTipoPermiso.getSelectedItem().toString();
        Object datos[] = obj.obtenerDiasDescrTipoPerm(tipoperm);
        lblDuracionTipoPermiso.setText(String.valueOf(datos[0]) + " días");
        txtDescripcionTipoPermiso.setLineWrap(true); // Habilitar saltos de línea automáticos
        txtDescripcionTipoPermiso.setWrapStyleWord(true);
        txtDescripcionTipoPermiso.setText(datos[1].toString());
    }

    private void setearNombreEmpleado() throws Exception {
        //De empleado obtenemos sus datos:
        Empleado objE = new Empleado();
        String nombre = objE.obtenerNombresEmpleado(this.idemp);
        lblEmpleado.setText(nombre);
    }

    private void validarFechaInicioPermiso() throws Exception {
        SimpleDateFormat format = new SimpleDateFormat("d MMM y");
        SimpleDateFormat format2 = new SimpleDateFormat("yyyy-MM-dd");
        
        Calendar calendar = Calendar.getInstance();
        Date minDate = calendar.getTime(); // Fecha actual
        dchsrFechaInicio.getJCalendar().setMinSelectableDate(minDate);
        
        java.sql.Date fechaTermino = objC.obtenerFechaTerminoContratoVigenteEmpleado(this.idemp);
        Date fechaUtilT = new java.sql.Date(fechaTermino.getTime());
        Calendar cal2 = Calendar.getInstance();
        cal2.setTime(fechaUtilT);
        cal2.add(Calendar.MONTH, -1);
        Date fechaValida = cal2.getTime();
        dchsrFechaInicio.getJCalendar().setMaxSelectableDate(fechaValida);
        
        String formattedDate = format.format(fechaUtilT);
        lblFechaMaxima.setText(formattedDate);
    }

    private void setearFechaActual() {
        LocalDate now = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("d MMM y");
        String formattedDate = now.format(formatter);
        lblFechaSolicitud.setText(formattedDate);
    }

    private void calcularFechaFinPermiso() {
        if (dchsrFechaInicio.getDate() != null && !lblDuracionTipoPermiso.getText().equals("---")) {
            int numdias = extractNumber(lblDuracionTipoPermiso.getText());
            Date fechainicio = dchsrFechaInicio.getDate();
            Calendar cal = Calendar.getInstance();
            cal.setTime(fechainicio);
            cal.add(Calendar.DATE, numdias);
            Date fechafin = cal.getTime();

            SimpleDateFormat dateFormat = new SimpleDateFormat("d MMM y");
            String formattedDate = dateFormat.format(fechafin);
            lblFechaTermino.setText(formattedDate);
        }
    }

    //Extraer el número del lbl de número de días:
    public static int extractNumber(String text) {
        // Definir el patrón de la expresión regular para encontrar números
        Pattern pattern = Pattern.compile("\\d+");
        Matcher matcher = pattern.matcher(text);

        // Buscar el número en la cadena
        if (matcher.find()) {
            // Convertir el número encontrado de String a int
            return Integer.parseInt(matcher.group());
        } else {
            // Si no se encuentra ningún número, devolver un valor por defecto, por ejemplo 0
            return 0;
        }
    }

    private boolean excede() throws ParseException, Exception {
        SimpleDateFormat formato = new SimpleDateFormat("dd MMM yyyy");
        Date fechautil = formato.parse(lblFechaTermino.getText());
        java.sql.Date fechaterminopermiso = new java.sql.Date(fechautil.getTime());

        Permiso objp = new Permiso();
        boolean excede = objp.fechaFinPermisoExcedeFechaFinContrato(fechaterminopermiso, this.idemp);
        return excede;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnConfirmar;
    private btn_efecto01_jwc.btn_efecto_V1_JWC btnVolver1;
    private javax.swing.JComboBox<String> cboTipoPermiso;
    private com.toedter.calendar.JDateChooser dchsrFechaInicio;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAvisoExcede;
    private javax.swing.JLabel lblDescripcionTipoPermiso;
    private javax.swing.JLabel lblDuracionTipoPermiso;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblFechaMaxima;
    private javax.swing.JLabel lblFechaSolicitud;
    private javax.swing.JLabel lblFechaTermino;
    private javax.swing.JTextArea txtDescripcionSolicitud;
    private javax.swing.JTextArea txtDescripcionTipoPermiso;
    // End of variables declaration//GEN-END:variables
}
